<!DOCTYPE html>
<html>
<head>
    <title><?php echo $this->titleHead?></title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <link rel="stylesheet" href="<?php echo $this->basePath("/Jobs/templates/default/job.css")?>" type="text/css">
    <link href='http://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet' type='text/css'>
    <style>
        form > div:hover {
            background-color: #eee;
            -webkit-box-shadow: 0px 0px 9px 3px rgba(0,0,0,0.55);
            -moz-box-shadow: 0px 0px 9px 3px rgba(0,0,0,0.55);
            box-shadow: 0px 0px 9px 3px rgba(0,0,0,0.55);
            cursor: pointer;
        }
    </style>
</head>
<body>
<div class="container">

    <main itemscope itemtype="http://schema.org/JobPosting">
        <!--
          This the *default* Template. Templates are quite easy to create. Take a look at the sources:
 
          https://github.com/cross-solution/YAWIK/blob/develop/module/Jobs/public/templates/default/index.phtml
        -->
        <div class="row">
            <div class="one-half column" itemscope itemtype="http://schema.org/Organization">
                <div itemprop="logo">
                    <img src="<?php echo $this->uriLogo?>" alt="<?php echo $this->organizationName?>">
                </div>
            </div>
            <div class="one-half column right">
            </div>
        </div>

        <p ><?php echo $this->descriptionEditable ?></p>
        <div class="row">
            <div class="twelve columns" itemprop="title">
                <?php echo $this->title; ?>
            </div>
        </div>
        <div class="row">
            <div class="two-thirds column">
                <div class="panel">
                    <div class="panel-heading"><h4><?php echo $this->translate($this->labelRequirements);?></h4></div>
                    <div class="panel-body" itemprop="responsibilities"><?php echo $this->requirements;?></div>
                </div>
                <div class="panel">
                    <div class="panel-heading"><h4><?php echo $this->translate($this->labelQualifications);?></h4></div>
                    <div class="panel-body" itemprop="qualifications"><?php echo $this->qualifications;?></div>
                </div>

            </div>
            <div class="one-third column">
                <div class="panel">
                    <div class="panel-heading"><h4><?php echo $this->translate($this->labelBenefits);?></h4></div>
                    <div class="panel-body" itemprop="jobBenefits"><?php echo $this->benefits;?></div>
                </div>
                <div itemscope itemtype="http://schema.org/Organization">
                    <strong itemprop="name">
                        <?php echo $this->organizationName?>
                    </strong><br/>
                    <address itemprop="address" itemscope itemtype="http://schema.org/PostalAddress">
                        <span itemprop="streetAddress"><?php echo $this->street?></span><br>
                        <span itemprop="postalCode"><?php echo $this->postalCode?></span>
                        <span itemprop="addressLocality"><?php echo $this->city?></span>
                        <br><br>
                        <span itemprop="telephone"><?php echo $this->phone?></span>
                    </address>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="twelve columns">
            </div>
        </div>
        <?php if ($this->applyButtons): ?>
        <div class="row">
            <div class="twelve columns">
                <div class="apply">
                    <?php foreach ($this->applyButtons as $applyButton):?>
                        <a target="_new" class="button button-primary apply-button-<?=$applyButton['type']?>" href="<?=$applyButton['url']?>" rel="nofollow">
                            <strong><?=$applyButton['label']?></strong>
                        </a>
                    <?php endforeach;?>
                </div>
            </div>
        </div>
        <?php endif; ?>
    </main>
    <footer><small>powered by <a href="http://yawik.org">YAWIK</a></small></footer>
</div>
</body>
</html>
