<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" dir="ltr" lang="de-DE">
<head>
<title></title>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<link rel="stylesheet" href="/Jobs/templates/default/style.css" type="text/css" media="screen">
<style>
form > div {
  border:1px solid rgb(84, 152, 215);
}
</style>
</head>
<body>
<div id="page">
 <div id="header">
  <div id="headerimg">
    <img src="/Jobs/templates/default/logo.gif" class="logo" border="0">
    <div class="description">This is a demo Template of a job opening</div>
  </div>
 </div>
<div id="content">
<p>
This is a demo Template of a jobad. Templates are quite easy to create. Just put <code>&lt;?php echo->requirements?&gt</code>
into your jobad and yawik will create an inline editor into your jobad.
Take a look at the <a href="https://github.com/cross-solution/YAWIK/blob/develop/module/Jobs/public/templates/default/index.phtml">sources</a>.
</p>
<p>Click below to enter the Jobtitle</p>
<h1><?echo $this->title?></h1>

<h4>Requirements:</h4>
<?php echo $this->requirements;?>
<h4>Qualifications:</h4>
<?php echo $this->qualifications;?>
<h4>Benefits:</h4>
<?php echo $this->benefits;?>

<h2><a target="_new" href="http://yawik.org/demo/de/apply/software-developer?subscriberUri=http%3A%2F%2Fcross-solution.de%2Fsubscriber%2F2"><strong>Zum Online Bewerbungsformular</strong></a></h2>


<address>
<strong>EXAMPLE Company<br>
</strong>Diemelstraße 2-4<br>
60486 Frankfurt am Main (Bockenheim)<br><br>

Tel: 0815-4711<br>
Fax: 0815-4712
</address>
</div>
</div>
</body>
</html>