<html>
<head>
<link src="style.css"  rel="stylesheet" type="text/css"/>
    <?php
    // Javascript needed by TinyMCE
    ?>
</head>
<body>
<img src="/Jobs/templates/default/img/test1.png"/>

<h1>Das hier ist der Title<?php
    echo $this->title
    ?></h1>
<h2>Anforderungen:</h2>
<?php
 echo $this->benefits;
//echo $this->requirements
?>
<h2>Qualifikation:</h2>
<?php
//echo $this->qualifications
?>
<?php

//$value = $this->value;
//$entity = $this->entity;
//
//echo 'hallo welt';
//
//$benefits = $entity->templateValues->benefits;
//echo $benefits;
//$this->input($benefits);
?>
</body></html>