<?php
$this->headstyle()->captureStart()?>
    #contact-firstname,
    #contact-lastname,
    #contact-phone,
    #contact-mobile {
        width: 300px;
    }
    
    #contact-lastname-wrapper,
    #contact-number-wrapper,
    #contact-location-wrapper,
    #contact-mobile-wrapper {
        margin-left: 5px;
    }
    
    #contact-street,
    #contact-location {
        width: 495px;
    }
    
    #contact-number,
    #contact-zipcode {
        width: 105px;
    }
    
    
<?php $this->headstyle()->captureEnd(); ?>


<div id="application-saved-message" class="hidden">
    <p><?php echo $this->translate('Your application has been saved successfully.'); ?></p>
</div>

<?php 
// $this->jquery()->addOnLoad('
//     $("fieldset > legend").click(function() {
//         $("#" + $(this).parent().attr("id") + " .fieldset-content").slideToggle();
//     });
// ');
$form->setAttributes(array(
    'action' => $this->url('lang/apply/submit', array(), true),
    'method' => 'post',
    'id' => 'application-form',
));

$form->prepare();
echo $this->form()->openTag($form);

echo $this->formHidden($form->get('jobid'));

$contact = $form->get('contact');

?>
<fieldset id="<?echo $contact->getName() ?>">
<legend><?php echo $this->translate($contact->getLabel()) ?></legend>
<div class="fieldset-content">

<div class="form-element float-left" id="contact-title-wrapper">
<?php echo $this->formRow($contact->get('title')) ?>
</div>

<div class="clear"></div>

<?php $el = $contact->get('firstname'); ?>
<div class="form-element float-left" id="<?php echo $el->getAttribute('id') ?>-wrapper">
    <?php echo $this->formRow($el); ?>
</div>

<?php $el = $contact->get('lastname'); ?>
<div class="form-element float-left" id="<?php echo $el->getAttribute('id') ?>-wrapper">
    <?php echo $this->formRow($el) ?>
</div>



<div class="clear"></div>

<?php $el = $contact->get('street') ?>
<div class="form-element float-left" id="<?php echo $el->getAttribute('id') ?>-wrapper">
    <?php echo $this->formRow($el) ?>
</div>

<?php $el = $contact->get('houseNumber') ?>
<div class="form-element float-left" id="<?php echo $el->getAttribute('id') ?>-wrapper">
    <?php echo $this->formRow($el) ?>
</div>

<div class="clear"></div>

<?php $el = $contact->get('zipCode') ?>
<div class="form-element float-left" id="<?php echo $el->getAttribute('id') ?>-wrapper">
    <?php echo $this->formRow($el) ?>
</div>

<?php $el = $contact->get('location') ?>
<div class="form-element float-left" id="<?php echo $el->getAttribute('id') ?>-wrapper">
    <?php echo $this->formRow($el) ?>
</div>

<div class="clear"></div>

<?php $el = $contact->get('phoneNumber') ?>
<div class="form-element float-left" id="<?php echo $el->getAttribute('id') ?>-wrapper">
    <?php echo $this->formRow($el) ?>
</div>

<div class="clear"></div>

<?php $el = $contact->get('mobileNumber') ?>
<div class="form-element float-left" id="<?php echo $el->getAttribute('id') ?>-wrapper">
    <?php echo $this->formRow($el) ?>
</div>

<div class="clear"></div>

<?php $el = $contact->get('email') ?>
<div class="form-element" id="<?php echo $el->getAttribute('id') ?>-wrapper">
    <?php echo $this->formRow($el) ?>
</div>

<div class="clear"></div>

</div> <!--  /fieldset-content -->
</fieldset>

<?php 

$work = $form->get('work');

?>

<fieldset id="<?echo $work->getName() ?>">
<legend><?php echo $this->translate($work->getLabel()) ?></legend>

</fieldset>

<?php 

$education = $form->get('education');

?>

<fieldset id="<?echo $education->getName() ?>">
<legend><?php echo $this->translate($education->getLabel()) ?></legend>
zb.
<pre>
OrganizationContact = Wo war die Ausbildung
StartDate
EndDate
EducationDegree
</pre>
</fieldset>
<?php 

$skill = $form->get('skills');

?>

<fieldset id="<?echo $skill->getName() ?>">
<legend><?php echo $this->translate($skill->getLabel()) ?></legend>
<?php  $el = $skill->get('skills'); ?>
<div class="form-element float-left" id="<?php echo $el->getAttribute('id') ?>-wrapper">
    <?php echo $this->formCollection($skill->get('skills')); ?>
</div>
</fieldset>
<button onclick="return add_skill()">Add a new Skill</button>

<script>
    function add_skill() {
        var currentCount = $('form > fieldset#skills > div > fieldset > input').length;
        var template = $('form > fieldset#skills > div > fieldset > span').data('template');
        template = template.replace(/__index__/g, currentCount);
        $('form > fieldset#skills > div > fieldset').append(template);
        
        return false;
    }
</script>
<div class="clear"></div>

<?php 

$attachment = $form->get('attachment');

?>

<fieldset id="<?echo $attachment->getName() ?>">
<legend><?php echo $this->translate($attachment->getLabel()) ?></legend>
</fieldset>


<?php $fs = $form->get('buttons') ?>
<fieldset id="<?php echo $fs->getName() ?>" class="buttons">

<?php 

# https://zf2-docs.readthedocs.org/en/release-2.0.0rc2/modules/zend.form.element.csrf.html
echo $this->formHidden($form->get('csrf')) 

?>
<?php echo $this->formsubmit($fs->get('submit')) ?>

</fieldset>
<?php echo $this->form()->closeTag() ?>

