<?php
$this->headstyle()->captureStart()?>

    
    #contact-firstname-wrapper,
    #contact-street-wrapper,
    #contact-zipcode-wrapper {
        float: left;
        margin-right: 5px;
    }
    
    #contact-title-wrapper,
    #contact-firstname-wrapper,
    #contact-street-wrapper,
    #contact-phone-wrapper,
    #contact-mobile-wrapper,
    #contact-email-wrapper {
        clear: left !important;
    }
    
    #contact-firstname,
    #contact-lastname,
    #contact-phone,
    #contact-mobile {
        width: 300px;
    }
    
    #contact-lastname-wrapper,
    #contact-number-wrapper,
    #contact-location-wrapper,
    #contact-mobile-wrapper {
        margin-left: 5px;
    }
    
    #contact-street,
    #contact-location {
        width: 495px;
    }
    
    #contact-number,
    #contact-zipcode {
        width: 105px;
    }
    
    
<?php $this->headstyle()->captureEnd(); ?>


<div id="application-saved-message" class="hidden">
    <p><?php echo $this->translate('Your application has been saved successfully.'); ?></p>
</div>

<?php 
// $this->jquery()->addOnLoad('
//     $("fieldset > legend").click(function() {
//         $("#" + $(this).parent().attr("id") + " .fieldset-content").slideToggle();
//     });
// ');
$form->setAttributes(array(
    'action' => $this->url('lang/apply/submit', array(), true),
    'method' => 'post',
    'id' => 'application-form',
));

echo $this->partial('form', array(
    'form' => $form,
    'splitFirstFieldset' => true
));
return;
$form->prepare();
echo $this->form()->openTag($form);

echo $this->formHidden($form->get('application')->get('jobid'));

$contact = $form->get('application');

?>
<fieldset id="<?echo $contact->getName() ?>">
<legend><?php echo $this->translate('Contact details') ?>
    <span class="ui-icon ui-icon-triangle-1-n float-right"></span></legend>
<div class="fieldset-content">

<div class="form-element float-left" id="contact-title-wrapper">
<?php echo $this->formRow($contact->get('title')) ?>
</div>

<div class="clear"></div>

<?php $el = $contact->get('firstname'); ?>
<div class="form-element float-left" id="<?php echo $el->getAttribute('id') ?>-wrapper">
    <?php echo $this->formRow($el); ?>
</div>

<?php $el = $contact->get('lastname'); ?>
<div class="form-element float-left" id="<?php echo $el->getAttribute('id') ?>-wrapper">
    <?php echo $this->formRow($el) ?>
</div>



<div class="clear"></div>

<?php $el = $contact->get('street') ?>
<div class="form-element float-left" id="<?php echo $el->getAttribute('id') ?>-wrapper">
    <?php echo $this->formRow($el) ?>
</div>

<?php $el = $contact->get('houseNumber') ?>
<div class="form-element float-left" id="<?php echo $el->getAttribute('id') ?>-wrapper">
    <?php echo $this->formRow($el) ?>
</div>

<div class="clear"></div>

<?php $el = $contact->get('zipCode') ?>
<div class="form-element float-left" id="<?php echo $el->getAttribute('id') ?>-wrapper">
    <?php echo $this->formRow($el) ?>
</div>

<?php $el = $contact->get('location') ?>
<div class="form-element float-left" id="<?php echo $el->getAttribute('id') ?>-wrapper">
    <?php echo $this->formRow($el) ?>
</div>

<div class="clear"></div>

<?php $el = $contact->get('phoneNumber') ?>
<div class="form-element float-left" id="<?php echo $el->getAttribute('id') ?>-wrapper">
    <?php echo $this->formRow($el) ?>
</div>

<div class="clear"></div>

<?php $el = $contact->get('mobileNumber') ?>
<?php echo $this->partial('form/row', array('element' => $el))?>

<div class="form-element float-left" id="<?php echo $el->getAttribute('id') ?>-wrapper">
    <?php echo $this->formRow($el) ?>
</div>

<div class="clear"></div>

<?php $el = $contact->get('email') ?>
<div class="form-element" id="<?php echo $el->getAttribute('id') ?>-wrapper">
    <?php echo $this->formRow($el) ?>
</div>

<div class="clear"></div>

</div> <!--  /fieldset-content -->
</fieldset>


<?php echo $this->partial('form/collection', array('collection' => $contact->get('educations'))) ?>


<fieldset id="buttons">
<div class="fieldset-content">
<?php echo $this->formButton($form->get('submit'), $this->translate('Apply'))?>
</div>
</fieldset>
<?php echo $this->form()->closeTag() ?>

