<?php
$this->headstyle()->captureStart()?>

    
    #application-firstname-wrapper,
    #application-street-wrapper,
    #application-zipcode-wrapper {
        float: left;
        margin-right: 5px;
    }
    
    #application-title-wrapper,
    #application-firstname-wrapper,
    #application-street-wrapper,
    #application-phone-wrapper,
    #application-mobile-wrapper,
    #application-email-wrapper {
        clear: left !important;
    }
    
    #application-firstname,
    #application-lastname,
    #application-phone,
    #application-mobile {
        width: 300px;
    }
    
    #application-lastname-wrapper,
    #application-number-wrapper,
    #application-location-wrapper,
    #application-mobile-wrapper {
        margin-left: 5px;
    }
    
    #application-street,
    #application-location {
        width: 495px;
    }
    
    #application-housenumber,
    #application-zipcode {
        width: 105px;
    }
    
    #application-languages .language-select {
        width: 190x;
    }
    
    #application-languages .level-select {
        width: 620px;
    }

    
    
    
<?php $this->headstyle()->captureEnd();
$this->headLink()->appendStylesheet($this->basePath('css/jquery.ui.selectmenu.css')); ?>
<?php $this->headScript()->appendFile($this->basePath('js/Core/jquery.daterange.js'))
                        ->appendFile($this->basePath('js/Core/jquery.initform.js'))
                        ->appendFile($this->basePath('js/Core/jquery.formcollection.js'))
                        ->appendFile($this->basePath('js/jquery.ui.selectmenu.js'));
      $this->headScript()->appendFile($this->basePath('js/jquery.ui.datepicker-' . $this->params('lang') . '.js'));


?>
<div id="application-saved-message" class="alert alert-success hide">
    <?php echo $this->translate('Your application has been saved successfully.'); ?>
</div>

<?php 
// $this->jquery()->addOnLoad('
//     $("fieldset > legend").click(function() {
//         $("#" + $(this).parent().attr("id") + " .fieldset-content").slideToggle();
//     });
// ');
$form->setAttributes(array(
    'action' => $this->url('lang/apply/submit', array(), true),
    'method' => 'post',
    'id' => 'application-form',
));

echo $this->form($form, 'application');
return;
$form->prepare();
$fs = array();
$base = $form->get('application');
foreach ($base->getIterator() as $elementOrFieldset):
    if ($elementOrFieldset instanceOf \Zend\Form\FieldsetInterface) {
        $fs[] = $elementOrFieldset;
        $base->remove(substr($elementOrFieldset->getName(), 12, -1));
    }
endforeach;
        

echo $this->form()->openTag($form);
echo $this->formCollection($base);
foreach ($fs as $collection): echo $this->formCollection($collection); endforeach;
echo $this->formCollection($form->get('buttons'));
echo $this->form()->closeTag();
return;
$form->prepare();
echo $this->form()->openTag($form);

echo $this->formHidden($form->get('application')->get('jobid'));

$contact = $form->get('application');

?>
<fieldset id="<?echo $contact->getName() ?>">
<legend><?php echo $this->translate('Contact details') ?>
    <span class="ui-icon ui-icon-triangle-1-n float-right"></span></legend>
<div class="fieldset-content">

<div class="form-element float-left" id="contact-title-wrapper">
<?php echo $this->formRow($contact->get('title')) ?>
</div>

<div class="clear"></div>

<?php $el = $contact->get('firstname'); ?>
<div class="form-element float-left" id="<?php echo $el->getAttribute('id') ?>-wrapper">
    <?php echo $this->formRow($el); ?>
</div>

<?php $el = $contact->get('lastname'); ?>
<div class="form-element float-left" id="<?php echo $el->getAttribute('id') ?>-wrapper">
    <?php echo $this->formRow($el) ?>
</div>



<div class="clear"></div>

<?php $el = $contact->get('street') ?>
<div class="form-element float-left" id="<?php echo $el->getAttribute('id') ?>-wrapper">
    <?php echo $this->formRow($el) ?>
</div>

<?php $el = $contact->get('houseNumber') ?>
<div class="form-element float-left" id="<?php echo $el->getAttribute('id') ?>-wrapper">
    <?php echo $this->formRow($el) ?>
</div>

<div class="clear"></div>

<?php $el = $contact->get('zipCode') ?>
<div class="form-element float-left" id="<?php echo $el->getAttribute('id') ?>-wrapper">
    <?php echo $this->formRow($el) ?>
</div>

<?php $el = $contact->get('location') ?>
<div class="form-element float-left" id="<?php echo $el->getAttribute('id') ?>-wrapper">
    <?php echo $this->formRow($el) ?>
</div>

<div class="clear"></div>

<?php $el = $contact->get('phoneNumber') ?>
<div class="form-element float-left" id="<?php echo $el->getAttribute('id') ?>-wrapper">
    <?php echo $this->formRow($el) ?>
</div>

<div class="clear"></div>

<?php $el = $contact->get('mobileNumber') ?>
<?php echo $this->partial('form/row', array('element' => $el))?>

<div class="form-element float-left" id="<?php echo $el->getAttribute('id') ?>-wrapper">
    <?php echo $this->formRow($el) ?>
</div>

<div class="clear"></div>

<?php $el = $contact->get('email') ?>
<div class="form-element" id="<?php echo $el->getAttribute('id') ?>-wrapper">
    <?php echo $this->formRow($el) ?>
</div>

<div class="clear"></div>

</div> <!--  /fieldset-content -->
</fieldset>


<?php echo $this->partial('form/collection', array('collection' => $contact->get('educations'))) ?>


<fieldset id="buttons">
<div class="fieldset-content">
<?php echo $this->formButton($form->get('submit'), $this->translate('Apply'))?>
</div>
</fieldset>
<?php echo $this->form()->closeTag() ?>

