<?php
/**
 * YAWIK
 *
 * @filesource
 * @copyright (c) 2013-2104 Cross Solution (http://cross-solution.de)
 * @license   MIT
 */

?>
<html>
<head>
<script src="/js/jquery.js" type="text/javascript"></script>
</head>
<body>
<h1><?php echo $this->profile->name?></h1>
<script type="text/javascript">
$(function() {
	window.opener.$(window.opener.document).trigger('fetch_complete.socialprofiles');
});
</script>
<textarea style="display:none"><?php echo $this->profile ? \Zend\Json\Json::encode($this->profile->getData()) : '' ?></textarea>
</body>

</html>
