<?php
/**
 * Cross Applicant Management
 *
 * @filesource
 * @copyright (c) 2013 Cross Solution (http://cross-solution.de)
 * @license   AGPLv3
 */
?>
<ul class="nav nav-pills nav-stacked">
<li>
    <a href="<?php echo $this->url('lang/my-groups', array('lang' => $this->params('lang')))?>"><span class="glyphicon glyphicon-th-large"></span> <?php echo $this->translate('My groups') ?></a>
</li>
</ul>
