<?php
/**
 * YAWIK
 *
 * @filesource
 * @copyright (c) 2013-2015 Cross Solution (http://cross-solution.de)
 * @license   MIT
 */
$action = $this->action;
$class  = 'index' == $this->action ? 'active' : '';

?>
<ul class="nav nav-pills nav-stacked">
<li class="<?php echo 'index' == $this->action ? 'active' : '' ?>">
    <a href="<?php echo $this->url('lang/my-groups', array('lang' => $this->params('lang')))?>"><span class="yk-icon yk-icon-group"></span> <?php echo $this->translate('My groups') ?></a>
</li>
</ul>
