<!DOCTYPE html>
<html>
<head>
    <title><?php echo $this->titleHead?></title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <link rel="stylesheet" href="<?php echo $this->basePath("/Jobs/templates/modern/job.css")?>" type="text/css">
    <link href='http://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet' type='text/css'>
    <style>
        form > div:hover {
            background-color: #eee;
            -webkit-box-shadow: 0px 0px 9px 3px rgba(0,0,0,0.55);
            -moz-box-shadow: 0px 0px 9px 3px rgba(0,0,0,0.55);
            box-shadow: 0px 0px 9px 3px rgba(0,0,0,0.55);
            cursor: pointer;
        }
    </style>
</head>
<body>
<div class="container">

    <main>
        <!--
          This the *modern* Template. Templates are quite easy to create. Take a look at the sources:
 
          https://github.com/cross-solution/YAWIK/blob/develop/module/Jobs/public/templates/modern/index.phtml
        -->
        <div class="row">
            <div class="one-third column">
                <div>
                    <div>
                        <img src="<?php echo $this->uriLogo?>">
                    </div>

                    <p><?php echo $this->descriptionEditable ?></p>

                    <address>
                        <strong><?php echo $this->organizationName?><br></strong>
                        <?php echo $this->street?><br>
                        <?php echo $this->postalCode?> <?php echo $this->city?><br><br>
                        <?php echo $this->phone?>
                    </address>
                </div>
            </div>
            <div class="two-thirds column">

                <div class="title">
                    <?php echo $this->title; ?>
                </div>


                <div class="panel">
                    <div class="panel-heading"><h4><?php echo $this->translate($this->labelRequirements);?></h4></div>
                    <div class="panel-body"><?php echo $this->requirements;?></div>
                </div>
                <div class="panel">
                    <div class="panel-heading"><h4><?php echo $this->translate($this->labelQualifications);?></h4></div>
                    <div class="panel-body"><?php echo $this->qualifications;?></div>
                </div>
                <div class="panel">
                    <div class="panel-heading"><h4><?php echo $this->translate($this->labelBenefits);?></h4></div>
                    <div class="panel-body"><?php echo $this->benefits;?></div>
                </div>

                <?=$this->jobApplyButtons($this->applyData)?>

            </div>
        </div>
    </main>
    <footer><small>powered by <a href="http://yawik.org">YAWIK</a></small></footer>
</div>
</body>
</html>
