<?php
/**
 * YAWIK
 *
 * @filesource
 * @copyright (c) 2013 - 2016 Cross Solution (http://cross-solution.de)
 * @license   MIT
 */

$hasFacets = $jobs instanceof \Solr\FacetsProviderInterface;
?>
<?php if ($hasFacets):?>
    <div class="row">
        <div class="col-md-3">
            <div class="panel panel-default">
                <div class="panel-heading"><?=$this->translate('Region')?></div>
                <div class="panel-body">
                    <?php foreach ($jobs->getFacets()->facet_fields->regionList as $regionTitle => $regionCount):?>
                        <?=$regionTitle?> (<?=$regionCount?>)<br>
                    <?php endforeach;?>
                </div>
            </div>
        </div>
        <div class="col-md-9">
<?php endif;?>
<?php if (count($jobs)):?>
<table class="pagination-content table table-striped table-bordered table-hover" id="jobs-list">
    <thead>
    <tr>
        <th><?php echo $this->translate('Title of the job')?> / <?php echo $this->translate('Companyname')?></th>
        <th><?php echo $this->translate('Location')?> / <?php echo $this->translate('Date of receipt')?></th>
        <th><?php echo $this->translate('Apply')?></th>
    </tr>
    </thead>

<?php foreach ($jobs as $job):?>
    <tr>
        <td>
            <?php if ($job->organization && $job->organization->image &&  $job->organization->organizationName): ?>
                <div class="yk-logo-list">
                    <img class="yk-logo-sm" src="<?php echo $this->basePath().$job->organization->image->uri ?>">
                </div>
            <?php endif ?>
            <?php $href = $job->link ? $job->link : $this->url('lang/jobs/view', array(), array('query' => array('id' => $job->id)), true); ?>
            <a href="<?php echo $href ?>" target="_blank"><?php echo strip_tags($job->title)?></a>
            <br/><?php
            if (isset($job->organization) && isset($job->organization->organizationName) && isset($job->organization->organizationName->name)) {
                echo $job->organization->organizationName->name;
            }
            ?>
        </td>
        <td>
            <div><?php echo $job->location?></div>
            <small>
                <?php
                if ($job->datePublishStart): echo $this->dateFormat($job->datePublishStart, 'short', 'none');
                elseif ($job->dateCreated): echo $this->dateFormat($job->dateCreated, 'short', 'none');
                endif
                ?>
            </small>
        </td>
        <td>
            <?php
            echo $this->applyUrl($job);
            ?>
        </td>
    </tr>
<?php endforeach?>
    </table>

<?php echo $this->paginationControl($jobs, 'Sliding', 'pagination-control', array('lang' => $this->params('lang'), 'route' => 'lang/jobboard'));?>

<?php endif ?>
<?php if ($hasFacets):?>
        </div>
    </div>
<?php endif;?>