<?php
/**
 * YAWIK
 *
 * @filesource
 * @author    Carsten Bleek <bleek@cross-solution.de>
 * @copyright 2013-2016 Cross Solution (http://cross-solution.de)
 * @version   GIT: $Id$
 * @license   https://yawik.org/LICENSE.txt MIT
 */

/**
 * @see http://php.net/manual/de/class.datetime.php#datetime.constants.types
 */
$dateFormat = \DateTime::W3C;

$organizationImageCache = $this->services('Organizations\ImageFileCache\Manager');

/* @var \Zend\Paginator\Paginator $jobs */
$jobs = $this->jobs;

/* @todo move this into a view helper */
$linkNext = $jobs->getCurrentPageNumber()<$jobs->count()?
    $this->serverUrl($this->basePath($this->url('lang/export',
                                                [
                                                    'format'=>'xml',
                                                    'channel'=> $this->channel
                                                ],
                                                [
                                                    'query'=> [
                                                        'page' => ($jobs->getCurrentPageNumber()+1)
                                                    ]
                                                ]))):'';

$linkPrevious = $jobs->getCurrentPageNumber()>1?
    $this->serverUrl($this->basePath($this->url('lang/export',
                                                [
                                                    'format'=>'xml',
                                                    'channel'=> $this->channel
                                                ],
                                                [
                                                    'query'=> [
                                                        'page' => ($jobs->getCurrentPageNumber()-1)
                                                    ]
                                                ]))):'';

?>
<jobOpenings>
    <!--
    Documentation http://yawik.readthedocs.io/en/latest/modules/jobs/index.html#xml-feeds
    -->
    <head>
        <totalPagesCount><?=$jobs->count()?></totalPagesCount>
        <currentPage><?=$jobs->getCurrentPageNumber()?></currentPage>
        <link type="next"><?=$linkNext?></link>
        <link type="previous"><?=$linkPrevious?></link>
        <totalJobsCount><?=$jobs->getTotalItemCount() ?></totalJobsCount>
        <channel><?=$this->channel?></channel>
    </head>
    <jobs>
    <?php foreach ($jobs as $job): /* @var \Jobs\Entity\Job $job */ ?>
        <job>
            <id><?=$job->getId()?></id>
            <title><?= $job->getTitle() ?></title>
            <datePublishStart><?=date_format($job->getDatePublishStart(),$dateFormat)?></datePublishStart>
            <datePublishEnd><?=date_format($job->getDatePublishEnd(),$dateFormat)?></datePublishEnd>
            <dateLastModified><?=date_format($job->getDateModified(),$dateFormat)?></dateLastModified>
            <displayLocation><?= $job->getLocation() ?></displayLocation>
            <?php $locations = $job->getLocations(); ?>
            <workLocations>
                <?php foreach ($locations as $location): /* @var \Jobs\Entity\Location $location */ ?>
                <location>
                    <country><?=$location->getCountry()?></country>
                    <city><?=$location->getCity()?></city>
                    <region><?=$location->getRegion()?></region>
                    <postalCode><?=$location->getPostalCode()?></postalCode>
                </location>
                <?php endforeach ?>
            </workLocations>
            <url><?=$job->getLink()?></url>
            <email><?=$job->getContactEmail()?></email>
            <?php $organization=$job->getOrganization() /* @var \Organizations\Entity\Organization*/ ?>
            <organization>
                <name><?=is_object($organization)?$organization->getOrganizationName()->getName():""?></name>
                <logo><?=is_object($organization) && is_object($organization->getImage())?$this->serverUrl($this->basePath($organizationImageCache->getUri($organization->getImage()))):''?></logo>
            </organization>
        </job>
    <?php endforeach ?>
    </jobs>
</jobOpenings>