<?php
/*
 * YAWIK
 *
 * @filesource
 * @copyright (c) 2013 - 2016 Cross Solution (http://cross-solution.de)
 * @license   MIT
 */
/**
 * {{rtd: displays short info about publishing on YAWIK}}
 *
 * @package      YAWIK
 * @subpackage   Applications
 * @author       weitz@cross-solution.de
 */
?>
<?php
/*
 *@todo: inject the needed variables
 */

/* @var $sm \Zend\ServiceManager\ServiceManager */
$options = $this->services('Core/Options');
/* @var $provider \Jobs\Options\ProviderOptions */
$provider = $this->services('Jobs/Options/Provider');
/* @var $channel \Jobs\Options\ChannelOptions */
$channel = $provider->getChannel('fazjob');

$options = $this->services('Core/Options');

$defaultCurrencyCode = $options->defaultCurrencyCode;
?>
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">
        <span>&times;</span>
    </button>
    <h4 class="modal-title"><?php echo sprintf($this->translate('Publish on %s'),'FAZJOB.NET')?></h4>
</div>

<div class="modal-body">
    <div class="media">
        <div class="media-body">
            <h4 class="media-heading">über FAZJOB.NET</h4>
            Top-Stellenangebote für Fach- und Führungskräfte aus der F.A.Z., der Sonntagszeitung und FAZjob.NET.
            Auf FAZJOB.NET finden Sie alle Stellenangebote für Fach- und Führungskräfte des renommierten F.A.Z.-Stellenmarktes.
            Wir bringen von jeher die klugen Köpfe unter den Bewerbern mit erfolgreichen Unternehmen und Institutionen
            zusammen. Nutzen Sie dazu unser überregionales und branchenübergreifendes Onlineangebot in den Sparten:
            Management, Unternehmensführung, Wissenschaft, Ingenieure, Marketing, Finanzen, IT, EDV, Telekommunikation,
            Einkauf, Logistik, Vertrieb, Verkauf, Recht, Verwaltung, Personalmanagement, Consulting und Medizin.
            . Weitere Informationen unter <a href="http://www.fazjob.net/">FAZJOB.NET</a>.
            <h4>
                Schaltungsdauer: <?php echo $channel->getPublishDuration() ?> Tage,
                Einzelpreis: <span class="label label-default">
                <?php echo $this->currencyFormat((round($channel->getPrice('min'),2)), $defaultCurrencyCode) ?>
                </span>
            </h4>
        </div>
        <a class="media-right" href="http://fazjob.net/" target="_blank">
            <img src="<?php echo $this->basePath("/Jobs/images/screenshot-fazjob.png")?>" alt="FAZjob.NET">
        </a>
    </div>
</div>

<div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
</div>
