<?php
/**
 * YAWIK
 *
 * @filesource
 * @license MIT
 * @copyright https://yawik.org/COPYRIGHT.php
 */

if ($this->renderSummary):
    echo $this->summaryForm()->renderSummaryElement($this->element->get('typeOfApplication'));
    echo $this->summaryForm()->renderSummaryElement($this->element->get('desiredJob'));

$locations = $this->element->getObject()->getDesiredLocations();
$locElement = $this->element->get('desiredLocations');

    ?><div class="row">
    <div class="col-md-3 yk-label">
        <label><?=$this->translate($locElement->getLabel())?></label>
    </div>
    <div class="col-md-9">
        <ul>
        <?php foreach ($locations as $location) {
            /* @var \Cv\Entity\Location $location */
            echo '<li>' . $location->getCity() . '</li>';
        }?>
            </ul>
    </div>
    </div>

<?php

    echo $this->summaryForm()->renderSummaryElement($this->element->get('willingnessToTravel'));
    echo $this->summaryForm()->renderSummaryElement($this->element->get('expectedSalary'));


else: echo $this->formCollection()->render($this->element, false);

endif ?>
