<?php
/**
 * YAWIK
 *
 * @copyright (c) 2013 - 2016 Cross Solution (http://cross-solution.de)
 * @license       MIT
 */
$this->headScript()->appendFile($this->basePath('Cv/js/search-form.js'));
$translate = $this->plugin('translate');

$sm = $this->getHelperPluginManager()->getServiceLocator();
/* @var \Geo\Options\ModuleOptions $options */
$options = $sm->get('Geo/Options');
$plugin = $options->getPlugin();

$form = $this->element;
/* @var $params \Cv\Form\SearchForm */
$params = $this->element->get('params');
$options = $form->getOptions();
$action = $form->getAttribute('action');
$base = $form->getBaseFieldset();

$form->setAttributes(array(
        'action' => $action,
        'method' => 'GET',
        'class' => 'form-inline'
    )
);


echo $this->form()->openTag($form);
?>
    <div id="params-search-wrapper">
        <?php
        echo $this->formText(
            $params->get('search')
                ->setAttributes(
                    [
                        'class' => 'form-control ',
                        'placeholder' => $this->translate('Desired Work'),
                        'style' => 'width: 35%; margin-right: 4px',
                    ]
                )
        );
        ?>
        <?php if ($params->has('l')) {

            echo $this->partial(
                "geo/form/GeoHorizontal",
                [
                    'element' => $params->get('l')
                ]
            );
            echo $this->formSelect(
                $params->get('d')
                    ->setAttributes(
                        [
                            'class' => 'form-control ',
                            'placeholder' => $this->translate('Type in a location'),
                            'data-width' => '120px'
                        ]
                    )
            );
        } ?>

        <button class="btn btn-primary" type="submit"><?php echo $this->translate('Search') ?></button>
        <button id="cv-list-filter-reset" class="btn btn-secondary"
                type="reset"><?php echo $this->translate('Clear') ?></button>
    </div>

<?php echo $this->form()->closeTag(); ?>