<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Geo\Controller\IndexController'                => __DIR__ . '/Geo/Controller/IndexController.php',
    'Geo\Entity\Geometry\Point'                     => __DIR__ . '/Geo/Entity/Geometry/Point.php',
    'Geo\Factory\Controller\IndexControllerFactory' => __DIR__ . '/Geo/Factory/Controller/IndexControllerFactory.php',
    'Geo\Factory\Form\GeoSelectFactory'             => __DIR__ . '/Geo/Factory/Form/GeoSelectFactory.php',
    'Geo\Factory\Listener\AjaxQueryFactory'         => __DIR__ . '/Geo/Factory/Listener/AjaxQueryFactory.php',
    'Geo\Factory\Service\ClientFactory'             => __DIR__ . '/Geo/Factory/Service/ClientFactory.php',
    'Geo\Form\GeoSelect'                            => __DIR__ . '/Geo/Form/GeoSelect.php',
    'Geo\Form\GeoSelectHydratorStrategy'            => __DIR__ . '/Geo/Form/GeoSelectHydratorStrategy.php',
    'Geo\Form\GeoSelectSimple'                      => __DIR__ . '/Geo/Form/GeoSelectSimple.php',
    'Geo\Listener\AjaxQuery'                        => __DIR__ . '/Geo/Listener/AjaxQuery.php',
    'Geo\Options\ModuleOptions'                     => __DIR__ . '/Geo/Options/ModuleOptions.php',
    'Geo\Service\AbstractClient'                    => __DIR__ . '/Geo/Service/AbstractClient.php',
    'Geo\Service\Geo'                               => __DIR__ . '/Geo/Service/Geo.php',
    'Geo\Service\Photon'                            => __DIR__ . '/Geo/Service/Photon.php',
);
