<?php
/**
 * YAWIK
 *
 * @filesource
 * @copyright (c) 2013-2014 Cross Solution (http://cross-solution.de)
 * @license   AGPLv3
 * @author Mathias Gelhausen <gelhausen@cross-solution.de>
 */


 $info = $element->getObject();
 if (!$info->getDisplayName()) : ?>
 <div id="<?php echo $element->getAttribute('id') ?>-empty-alert" class="alert alert-info">
    <p><?php echo $this->translate('Click here to enter contact informations.') ?></p>
 </div>
        
    <?php $this->headscript()->captureStart()?>
    ;(function($) { 
        $(function() { 
            $('#<?php echo $element->getAttribute('id') ?>-empty-alert')
            .click(function() {
                console.debug($(this), $(this).parent());
                $(this).parent().find('.sf-edit').click();
            });
        });
    })(jQuery);
    <?php $this->headscript()->captureEnd();?>
 <?php else: ?>
    <div class="row">
        <div class="col-md-6">
            <?php echo $this->translate($this->salutation($info->gender))?><br>
            <strong><?php echo $info->displayName?></strong><br><br>
            <adress>
                <?php echo $info->street?> <?php echo $info->houseNumber?><br>
                <?php echo $info->postalCode?> <?php echo $info->city?>
            </adress>
            
        </div>
        <div class="col-md-6">
            <div class="row">
                <div class="col-md-2"><i class="yk-icon yk-icon-phone"></i></div>
                <div class="col-md-10"><?php echo $info->phone?></div>
            </div>
            <div class="row">
                <div class="col-md-2"><i class="yk-icon yk-icon-envelope"></i></div>
                <div class="col-md-10"><?php echo $info->email?></div>
            </div>
        </div>
    </div>
<?php endif ?>

