<?php
/**
 * YAWIK
 *
 * @filesource
 * @copyright (c) 2013-2014 Cross Solution (http://cross-solution.de)
 * @license   AGPLv3
 * @author Mathias Gelhausen <gelhausen@cross-solution.de>
 */


 $info = $element->getObject();?>
    <div class="row">
        <div class="col-md-6">
            <?php echo $this->translate($this->salutation($info->gender))?><br>
            <strong><?php echo $info->displayName?></strong><br><br>
            <adress>
                <?php echo $info->street?> <?php echo $info->houseNumber?><br>
                <?php echo $info->postalCode?> <?php echo $info->city?>
            </adress>
            
        </div>
        <div class="col-md-6">
            <div class="row">
                <div class="col-md-2"><strong><?php echo $this->translate('Phone')?></strong></div>
                <div class="col-md-10"><?php echo $info->phone?></div>
            </div>
            <div class="row">
                <div class="col-md-2"><strong><?php echo $this->translate('Email')?></strong></div>
                <div class="col-md-10"><?php echo $info->email?></div>
            </div>
        </div>
    </div>

