
<?$this->headstyle('img.user-image { max-width:150px; max-height: 250px; }'); ?>


<fieldset id="<?php echo $element->hasAttribute('id') ? $element->getAttribute('id') : 'user-info'?>">
    <legend><?php echo $this->translate($element->getLabel())?></legend>
    <div class="fieldset-content">
       <div class="row">
            
            <div class="col-md-9">
                <?php echo $this->formRow($element->get('gender')); ?>
                <?php echo $this->formRowCombined(
                    array(4 => $element->get('firstName'), 5 => $element->get('lastName'))
                );?>
                <?php echo $this->formRowCombined(
                		array(7 => $element->get('street'), 2 => $element->get('houseNumber'))
                ); ?>
                <?php echo $this->formRowCombined(
                    array(2 => $element->get('postalcode'), 7 => $element->get('city'))
                );?>
                <?php echo $this->formRow($element->get('phone'));
                      echo $this->formRow($element->get('email'));?>

                      
            </div>
            <div class="col-md-3">
                <div class="controls controls-row row">
                    <?php if ($image = $element->getObject()->getImage()): ?>
                    <div class="col-md-12 text-center">
                        <img src="/file/Auth.UserImage/<?php echo $image->getId() ?>" class="user-image img-polaroid" />
                        <?php echo $this->formRow($element->get('imageId')->setValue($image->getId())) ?>
                    </div>
                    <? endif ?>
                </div>
                <?php echo $this->formRow($element->get('image')) ?>
                
            </div>
        </div>
       
    </div>
    
</fieldset>


