<?php
/**
 * Cross Applicant Management
 *
 * @filesource
 * @copyright (c) 2013 Cross Solution (http://cross-solution.de)
 * @license   AGPLv3
 */

$this->headScript()->appendFile($this->basePath('Auth/js/form.socialprofiles.js'))
                   ->appendFile($this->basePath('Core/js/jquery.reloadable-modal.js'));

echo $this->formCollection($this->element);
?>
<div class="modal fade modal-scrollable" id="<?php echo $this->element->getAttribute('id') ?>-preview-box" data-reloadable="body" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">
            <span class="fa-spin yk-icon yk-icon-spinner"></span>
            <?php echo $this->translate('Formatting')?> ...</h4>
      </div>
      <div class="modal-body">
        
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-dismiss="modal"><?php echo $this->translate('Close') ?></button>
      </div>
    </div>
  </div>
</div>

