<?php
/**
 * YAWIK
 *
 * @filesource
 * @copyright (c) 2013 - 2016 Cross Solution (http://cross-solution.de)
 * @license   MIT
 * @author fedys
 */
 $info = $element->getObject();

$element->get('status')->setOption('summary_value', $this->translate((string) $info->getStatus()));
?>
<div>
        <?=$this->summaryForm()->renderSummaryElement($element->get('status'))?>
        <?=$this->summaryForm()->renderSummaryElement($element->get('login'))?>
</div>
