<?php
/**
 * Cross Applicant Management
 *
 * @filesource
 * @copyright (c) 2013 Cross Solution (http://cross-solution.de)
 * @license   AGPLv3
 */

$this->headScript()->appendFile($this->basePath('Core/js/loading-popup.js'));
?>
<div class="modal hide" style="top: 50%; width: auto; margin-left: -19px;" id="loading-popup" data-backdrop="static" data-keyboard="false">
    <div class="modal-body">
        <img src="/images/loader.gif">
    </div>
</div>