<?php
/**
 * YAWIK
 *
 * @filesource
 * @copyright (c) 2013-2104 Cross Solution (http://cross-solution.de)
 * @license   MIT
 */
/**
 * {{rtd: Renders default notification boxes.}}
 */

$this->headScript()->appendFile($this->basePath('Core/js/notification.js'));
$messenger = $this->flashMessenger();
$alert     = $this->plugin('alert');
$translate = $this->plugin('translate');
?>

<div class="yk-notifications">
<?php foreach (array('danger', 'warning', 'success', 'info') as $ns):
    $messages = array_merge(
        $messenger->getMessagesFromNamespace($ns),
        $messenger->getCurrentMessagesFromNamespace($ns)
    );

    $messenger->clearCurrentMessagesFromNamespace($ns);
    
    foreach ($messages as $message):
        echo $alert->render($ns, $translate($message));
    endforeach;
endforeach ?>        
</div>
