<?php 
/**
 * Cross Applicant Management
 *
 * @filesource
 * @copyright (c) 2013 Cross Solution (http://cross-solution.de)
 * @license   AGPLv3
 */

      use Applications\Entity\StatusInterface as Status;
      
      $this->headTitle($this->translate('Details'));
      $this->headScript()->appendFile($this->basePath('Applications/js/applications.manage.detail.js'));
      $this->headScript()->appendScript('$(function() { $(".rating").barrating(); });');
?>
<h1><?= $this->translate('application details') ?></h1>
<?php echo $this->form($this->commentForm) ?>

<div id="forward-email-result" class="alert" style="display:none"></div>

<nav class="navbar cam-toolbar">   
    <div id="state-actions" class="btn-group cam-action-states">
        <?php $status = $application->status->name;
        
            $actionButtons = array(
                Status::CONFIRMED => array(
                    'href' => $this->url(
                                'lang/applications/detail/status',
                                array('status' => Status::CONFIRMED),
                                true
                              ),
                    'label' => $this->translate('Confirm'),
                    'title' => $this->translate('Confirm the receipt'),
                ),
                Status::INVITED => array(
                    'href' => $this->url(
                                'lang/applications/detail/status',
                                array('status' => Status::INVITED),
                                true
                              ),
                    'label' => $this->translate('Invite'),
                    'title' => $this->translate('Invite the applicant'),
                ),
                Status::REJECTED => array(
                    'href' => $this->url(
                                'lang/applications/detail/status',
                                array('status' => Status::REJECTED),
                                true
                              ),
                    'label' => $this->translate('Reject'),
                    'title' => $this->translate('Reject the applicant'),
                ),
                    
            );

            foreach ($actionButtons as $targetStatus => $spec):
                if ($status == $targetStatus): continue; endif?>
              
            <button class="btn btn-default" 
                    data-href="<?php echo $spec['href']?>"
                    <?php if (isset($spec['title'])):?>
                    data-title="<?php echo $spec['title']?>"
                    data-toggle="modal"
                    data-target="#mail-box"
                    <?php endif ?>
            ><?php echo $spec['label'] ?></button>
            <?php endforeach ?>  
     </div>
   </div>  
   <form id="forward-email-form" action="<?php echo $this->url('lang/applications/detail',array(), true)?>" method="get">
   <div id="forward-email" class="cam-input-group input-group">
            <span class="input-group-addon"
            data-toggle="popover" 
            data-trigger="hover focus click"
            data-placement="bottom" 
            title="<?php echo $this->translate('Enter an email address')?>"
            data-content="<?php echo $this->translate('This application will be send as an email to the given address in a layout similar to that on this page with all attachments included.')?>">?
            </span>
            <input type="hidden" name="action" value="forward">
            <input class="form-control" id="forward-email-input" name="email" type="email">
            <span class="input-group-btn">
            <button class="btn btn-default" type="submit">
             <span class="cam-icon-forward"></span> <?php echo $this->translate('Forward')?>
            </button>
            </span>
      </div>
    </form>
        <div class="pull-right">
        <div class="btn-group">
          <button id="cam-applications-comments-toggle" class="btn btn-default"
                    data-title="title"
                    data-toggle="modal"
                    data-target="#cam-application-comments"
                    title="<?php echo $this->translate('View comments') ?>">
               <span class="cam-icon-comment"></span></button>
          <button id="cam-applications-comments-quickadd" class="btn btn-default"
                    data-title="title"
                    title="<?php echo $this->translate('Add comment') ?>">
           <span class="cam-icon-plus"></span></button>
          </div>
          <button class="btn btn-default"
                    data-title="title"
                    data-toggle="modal"
                    data-target="#cam-application-history"
                    title="<?php echo $this->translate('State history')?>">
          <span class="cam-icon-history"></span>
          </button>
          <a class="btn btn-default"
                    href="?format=pdf" title="<?php echo $this->translate('download as PDF')?>">
          <span class="cam-icon-download"></span>
          </a>
          <?php if ($this->acl($application, 'delete')):?>            
          <button class="btn btn-default" data-title="delete Application"
                    data-toggle="modal"
                    data-target="#cam-delete-application"
                    title="<?php echo $this->translate('Delete application')?>"> 
            <i class="cam-icon-delete"></i> Löschen
          </button>
        <?php endif ?>
        </div>
</nav>
<div id="mail-box" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
          <h3 id="mail-box-label">
            <?php echo $this->translate('Invite the applicant') ?>
          </h3>
      </div>
        <div id="mail-box-content" class="modal-body"></div>
        <div class="modal-footer">
          <button class="btn btn-default" data-dismiss="modal" aria-hidden="true"><?php echo $this->translate('Cancel') ?></button>
          <button class="btn btn-primary" onclick="$('#applicant-mail').submit()"><?php echo $this->translate('Send mail') ?></button>
        </div>
     </div>
  </div>
</div>
<div id="cam-delete-application" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="delete Application" aria-hidden="true">
  <div class="modal-dialog">
   <div class="modal-content">
     <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="history-box-label">
          <?php echo $this->translate('Delete Application') ?>:
        </h3>
      </div>
      <div class="modal-body">
      <?php echo $this->translate('Are you sure you want to delete this application?')?>
      </div>
      <div class="modal-footer">
          <button class="btn btn-default" data-dismiss="modal" aria-hidden="true"><?php echo $this->translate('Cancel') ?></button>
          <a class="btn btn-primary" href="<?php echo $this->url('lang/applications/detail', array('id' => $application->id), array('query' => 'action=delete'), true)?>" class="btn btn-mini btn-default" title="<?php echo $this->translate('delete this application')?>">
          <?php echo $this->translate('Delete application') ?></a>
      </div>
    </div>
    
  </div>
</div>

<div id="cam-application-comments" class="modal fade modal-scrollable" tabindex="-1" role="dialog" aria-hidden="true"
     data-list-errormessage="<?php echo $this->translate('Error while loading comments.')?>"
     data-list-url="<?php echo $this->url(
                        'lang/applications/comments', array('action' => 'list'), 
                        array('query' => array(
                            'applicationId' => $this->application->id
                        )), true
                    )?>"
     data-form-errormessage=<?php echo $this->translate('Error while loading comment form.')?>"
     data-form-url="<?php echo $this->url(
                        'lang/applications/comments', array('action' => 'form'),
                         true)?>"
     data-application-id="<?php echo $this->application->id ?>"`
     data-mode="list"
>
  <div class="modal-dialog">
   <div class="modal-content">
     <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3><?php echo $this->translate('Comments') ?> <img class="hide" src="/images/loader.gif" /></h3>
     </div>
     <div id="cam-application-comments-body" class="modal-body">
        <div class="cam-error hide"><p></p></div>
     </div>
     <div class="modal-footer">
         <button id="cam-application-comments-cancelbtn" class="btn btn-default hide"><?php echo $this->translate('Cancel') ?></button>
         <button id="cam-application-comments-savebtn" class="btn btn-primary hide"><?php echo $this->translate('Save') ?></button>
         
         <button id="cam-application-comments-addbtn" class="btn btn-primary" ><?php echo $this->translate('Add new comment') ?></button>
         <button id="cam-application-comments-closebtn" class="btn btn-default" data-dismiss="modal" aria-hidden="true"><?php echo $this->translate('Close') ?></button>
       
     </div>
   </div>
 </div>
</div>

<div id="cam-application-history" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
   <div class="modal-content">
     <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="history-box-label">
          <?php echo $this->translate('State history') ?>:
        </h3>
      </div>
      <div class="modal-body">
        <table class="table table-striped table-bordered">
        <thead>
            <tr>
                <th><?php echo $this->translate('Date') ?></th>
                <th><?php echo $this->translate('State') ?></th>
                <th><?php echo $this->translate('Comment') ?></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->application->history as $history): ?>
            <tr>
                <td><?php echo $this->dateFormat($history->date)?></td>
                <td><?php echo $this->translate($history->status) ?></td>
                <td><?php echo $history->message ?></td>
            </tr>
            <?php endforeach ?>
        </tbody>
        </table>     
      </div>
    </div>
  </div>
</div>

<p class="cam-job-title"><?php echo $this->link($this->application->job->link, $this->application->job->title)?></p>

<div class="row">
  <div class="col-md-6">
    <div class="col-md-12">
      <h2><?= $this->translate('personal information')?></h2>
        <div class="col-md-4">
          <div class="cam-portrait ">
          <?php if ($this->application->contact->image):?>
          <img src="<?php echo $this->basePath($this->application->contact->image->uri) ?>" class="img-thumbnail"/>
          <?php else:?>
          <span class="cam-icon-portrait img-thumbnail"></span>
          <?php endif?>
          </div>    
        </div>
        <div class="col-md-8">
        <adress>
        <strong><?php echo $this->application->contact->displayName ?></strong><br> 
        <?php echo $this->application->contact->street ?> <?php echo $this->application->contact->houseNumber ?><br>
        <?php echo $this->application->contact->postalcode ?> <?php echo $this->application->contact->city ?><br>
        <br>
        <?php if ($this->application->contact->phone):?>
        Tel.: <?php echo $this->application->contact->phone; ?><br>
        <?php endif?>
        <?php if ($this->application->contact->email):?>
        E-Mail: <?php echo $this->link($this->application->contact->email); ?><br>
        <?php endif?>
        </adress>
      </div>
    </div>
  </div>
  <div class="col-md-6">
    <div class="col-md-12">
      <div id="application-rating" class="pull-right">
      <?php echo $this->partial('applications/manage/_rating', array('application' => $this->application)) ?>
      </div>
      <p class="text-right lead cam-color-<?php echo $this->application->status ?>"><?php echo $this->translate((string) $this->application->status) ?></p> 
      <div class="row">
        <div class="col-md-6"><?= $this->translate('date of receipt')?>:</div>
        <div class="col-md-6"><?=  strftime('%x %X', $application->dateCreated->getTimestamp()); ?></div>
      </div>
      <?php if ($application->dateCreated->getTimestamp() != $application->dateModified->getTimestamp()):?>
      <div class="row">
        <div class="col-md-6"><?= $this->translate('last modification date')?>:</div>
        <div class="col-md-6"><?=  strftime('%x %X', $application->dateModified->getTimestamp()); ?></div>
      </div>
      <?php endif;?>
      <?php if(count($this->application->attachments)>0):?>
      <h2><?= $this->translate('Attachments')?></h2>
      <?php foreach( $this->application->attachments as $attachment): ?>
        <div class="row show-grid">
          <div class="col-md-3">
            <a href="<?php echo $this->basePath($attachment->uri) ?>" target="_new"><?php echo $attachment->name ?></a>
          </div>
        </div>
      <?php endforeach; // attachments?>
      <?php endif;?>
    </div>
  </div>
</div>

<h2><?=$this->translate('Summary')?></h2>
<div class="row">
<div class="col-md-12">
<?php echo nl2br($this->application->summary) ?>
</div>
</div>

<?php if(count($this->application->cv->employments)>0):?>
<h2><?= $this->translate('work experience')?></h2>
<table class="table  table-condensed table-bordered "> 
<tr>
 <th class="col-md-1"><?=$this->translate('Start')?></th>
 <th class="col-md-1"><?=$this->translate('End')?></th>
 <th><?=$this->translate('Description')?></th>
</tr>
<?php foreach( $this->application->cv->employments as $employment): ?>
<tr>
 <td><?= $employment->startDate ?></td>
 <td><?= $employment->endDate ?></td>
 <td><?=  $employment->description ?></td>
</tr>
<?php endforeach; // employments?>
</table>
<?php endif;?> 

<?php if(count($this->application->cv->educations)>0):?>
<h2><?= $this->translate('education and training')?></h2>
<table class="table table-condensed table-bordered "> 
<tr>
 <th class="col-md-1"><?=$this->translate('Start')?></th>
 <th class="col-md-1"><?=$this->translate('End')?></th>
 <th><?=$this->translate('Description')?></th>
</tr>
<?php foreach( $this->application->cv->educations as $education): ?>
  <tr>
   <td><?php echo $education->startDate ?></td>
   <td><?php echo $education->endDate ?></td>
   <td><?php echo $education->description ?></td>
  </tr>
<?php endforeach; // eucations?>    
</table>
<?php endif;?> 

<?php if(count($this->application->cv->skills)>0):?>
<h2><?= $this->translate('personal skills')?></h2>
<?php foreach( $this->application->cv->skills as $kill): ?>
  <div class="col-md-3"><?=$this->translate('native language')?></div> 
  <div class="col-md-3">TODO</div>
<?php endforeach; // skills?>
<?php endif;?>



