<?php 
/**
 * YAWIK
 *
 * @filesource
 * @copyright (c) 2013-2104 Cross Solution (http://cross-solution.de)
 * @license   MIT
 */
/**
 * {{rtd: Renders a application as a simple HTML, used in the PDF generation and the forward mail }}
 *
 * This HTML is used to generate a PDF
 * @see http://mpdf1.com/manual/index.php
 *
 * and this is used to generate the Mail, if an application is forwarded
 * or if an applicant want's to get his application via CC.
 *
 * The HTML should be standalone. No external references.
 *
 */
use Applications\Entity\StatusInterface as Status;
      
$this->headTitle($this->translate('Details'));
?>
<style>
body {
	font-family: Arial;
}
.header {
	text-align: right; 
	border-bottom: 1px solid #000000; 
	font-size: 10pt;
}
.footer {
	vertical-align: bottom; 
	font-size: 8pt;
    color: #000000; 
}
.address,
.personal-information {
	vertical-align: top;
	width: 100%;
	border-spacing: 0px;
}
.col1 {
    width:150px;
    margin-right: 10px;
    border-right: 1px solid #dedede;
}
table.list {
	width: 100%;
	border: 1px solid #e4e4e4;
	border-spacing: 0px;
}
table.list tr td {
	vertical-align: top;
	border-bottom: 1px solid #f4f4f4;
	padding: 3px;
}
th {
	background-color: #f4f4f4;
}
.photo {
 	width: 100px;
}
</style>
<!--suppress HtmlUnknownTag -->
<sethtmlpageheader name="header" value="on" show-this-page="1"/>
<!--suppress HtmlUnknownTag -->
<htmlpageheader name="header">
<div class="header"><?php echo $this->translate('Bewerbung vom')?>: <?php echo strftime('%x %X', $application->dateCreated->getTimestamp()); ?></div>
</htmlpageheader>
<!--suppress HtmlUnknownTag -->
<htmlpagefooter name="footer">
<!-- @todo the following header makes no sense in Emails. -->
<table width="100%" class="footer"><tr>
    <td width="33%">{DATE d.m.Y}</td>
    <td width="33%" align="center">{PAGENO}/{nbpg}</td>
    <td width="33%" style="text-align: right; "><?php echo $this->translate('Bewerbung')?></td>
    </tr></table>
</htmlpagefooter>
<!--suppress HtmlUnknownTag -->
<sethtmlpagefooter name="footer" value="on"/>
<h1><?php echo $this->translate('application details') ?></h1>
<h2><?php echo $this->translate('personal information')?></h2>
<table class="personal-information">
 <tr>
  <td>
   <table class="address">
    <tr>
     <td class="col1"><?php echo $this->translate('name')?>:</td>
     <td><?php echo $this->application->contact->firstName.' '.$this->application->contact->lastName ?></td>
    </tr>
    <?php if (isset($this->application->contact->street)): ?>
    <tr>
     <td class="col1"><?php echo $this->translate('Street')?>:</td>
     <td><?php echo $this->application->contact->street .' '.$this->application->contact->housenumber?></td>
    </tr>
    <?php endif; ?>
    <?php if (isset($this->application->contact->city)): ?>
    <tr>
     <td class="col1"><?php echo $this->translate('City')?>:</td>
     <td><?php echo $this->application->contact->postalcode.' '.$this->application->contact->city ?></td>
    </tr>
    <?php endif; ?>
    <tr>
     <td class="col1"><?php echo $this->translate('E-Mail')?>:</td>
     <td><?php echo $this->application->contact->email ?></td>
    </tr>
    <tr>
     <td class="col1"><?php echo  $this->translate('Phone')?>:</td>
     <td><?php echo   $this->application->contact->phone ?></td>
    </tr>
   </table>
  </td>
  <td align="right">
   <?php if ($this->application->contact->image):?>
   <img src="data:;base64,<?php echo base64_encode($this->application->contact->image->content) ?>" class="photo">
   <?php endif ?> 
  </td>
 </tr>
</table>

<?php if (isset($this->application->facts->expectedSalery) or
          isset($this->application->facts->willingnessToTravel) or
          isset($this->application->facts->earliestStartingDate)):?>

    <h2><?php echo $this->translate('Facts')?></h2>
    <table width="100%">
    <?php if(isset($this->application->facts->willingnessToTravel)):?>
        <tr>
            <td class="col1"><?php echo $this->translate('Willingness to travel')?>:</td>
            <td><?php echo $this->application->facts->willingnessToTravel ?></td>
        </tr>
    <?php endif?>
    <?php if(isset($this->application->facts->earliestStartingDate)):?>
        <tr>
            <td class="col1"><?php echo $this->translate('Earliest starting date')?>:</td>
            <td><?php echo $this->application->facts->earliestStartingDate ?></td>
        </tr>
    <?php endif?>
    <?php if(isset($this->application->facts->expectedSalary)):?>
        <tr>
            <td class="col1"><?php echo $this->translate('Expected salary')?>:</td>
            <td><?php echo $this->application->facts->expectedSalary ?></td>
        </tr>
    <?php endif?>
</table>
<?php endif?>

<h2><?php echo $this->translate('Cover Letter')?></h2>
<div class="row">
<?php echo nl2br($this->application->summary) ?>
</div>

<?php if(count($this->application->cv->employments)>0):?>
<h2><?php echo  $this->translate('work experience')?></h2>
<table class="list"> 
<tr>
 <th align="left"><?php echo $this->translate('Start')?></th>
 <th align="left"><?php echo $this->translate('End')?></th>
 <th><?php echo $this->translate('Description')?></th>
</tr>
<?php foreach( $this->application->cv->employments as $employment): ?>
<tr>
 <td><?php echo $this->DateFormat($employment->startDate,'middle','null',$this->lang,'MMM Y') ?></td>
 <td><?php echo $this->DateFormat($employment->endDate,'middle','null',$this->lang,'MMM Y') ?></td>
 <td><?php echo $employment->description ?></td>
</tr>
<?php endforeach; // employments?>
</table>
<?php endif;?> 

<?php if(count($this->application->cv->educations)>0):?>
<h2><?php echo  $this->translate('education and training')?></h2>
<table class="list"> 
<tr>
 <th align="left"><?php echo $this->translate('Start')?></th>
 <th align="left"><?php echo $this->translate('End')?></th>
 <th><?php echo $this->translate('Description')?></th>
</tr>
<?php foreach( $this->application->cv->educations as $education): ?>
  <tr>
   <td><?php echo $this->DateFormat($education->startDate,'middle','null',$this->lang,'MMM Y') ?></td>
   <td><?php echo $this->DateFormat($education->endDate,'middle','null',$this->lang,'MMM Y') ?></td>
   <td><?php echo $education->description ?></td>
  </tr>
<?php endforeach; // educations?>
</table>
<?php endif;?> 

<?php if(count($this->application->cv->skills)>0):?>
<h2><?php echo  $this->translate('personal skills')?></h2>
<?php foreach( $this->application->cv->skills as $kill): ?>
  <div class="col-md-3"><?php echo $this->translate('native language')?></div> 
  <div class="col-md-3">TODO</div>
<?php endforeach; // skills?>
<?php endif;?>

<?php if(count($this->application->profiles)>0):?>
<style>
.panel-heading {
    background-color: #F5F5F5;
    border-color: #DDDDDD;
    color: #333333;
}
tr {
     border-bottom: 1px solid rgba(0, 0, 0, 0);
}
.panel-heading {
    margin-top: 10px;
    border-bottom: 1px solid rgba(0, 0, 0, 0);
    padding: 10px 15px;
}
.yk-portrait {
    font-size: 80px;
    margin-right: 10px;
    width: 100px;
}
.pull-left {
    float: left;
    width: 20%; // needed by mpdf
}
.table {
    width: 100%;
}
</style>
  <?php foreach ($this->application->profiles as $profile): ?>
    <!--suppress HtmlUnknownTag -->
        <pagebreak />
    <?php echo $this->partial('applications/manage/social-profile/'.strtolower($profile->name).'.pdf.phtml',$profile->getData()) ?>
  <?php endforeach;?> 
<?php endif ?>

<?php if(count($this->application->attachments)>0):?>
<h2><?php echo $this->translate('Attachments')?></h2>
<?php $html=""; foreach( $this->application->attachments as $attachment): ?>
<div class="row show-grid">
    <?php 
        // the displaying of the html is in charge of the PDF-Module
        // look there at the file-rendering-method
        echo $this->InsertFile($attachment) . '<br />';
  ?>
</div>
<?php endforeach; // attachments ?>
<?php endif;?>

