<?php $this->headTitle($this->translate('Details'));?>
<h1><?= $this->translate('application details') ?></h1>


<div class="row-fluid">
    <div class="span3"><?= $this->translate('State')?>:</div>
    <div class="span6"><?=  $this->application->status; ?></div>
</div>
<div class="row-fluid">
    <div class="span3"><?= $this->translate('date of receipt')?>:</div>
    <div class="span6"><?=  strftime('%x %X', $application->dateCreated->getTimestamp()); ?></div>
</div>
<div class="row-fluid">
    <div class="span3"><?= $this->translate('last modification date')?>:</div>
    <div class="span6"><?=  strftime('%x %X', $application->dateModified->getTimestamp()); ?></div>
</div>

<h2><?= $this->translate('personal information')?></h2>
<div class="row-fluid">
<div class="span9">
<div class="row-fluid">
<div class="span3"><?= $this->translate('name')?>:</div>
<div class="span3"><?=  $this->application->contact->firstName.' '.$this->application->contact->lastName ?></div>
</div>
<div class="row-fluid">
<div class="span3"><?= $this->translate('E-Mail')?>:</div>
<div class="span3"><?=  $this->application->contact->email ?></div>
</div>
<div class="row-fluid">
<div class="span3"><?= $this->translate('Phone')?>:</div>
<div class="span3"><?=  $this->application->contact->phone ?></div>
</div>
</div>
<div class="span3">
    <?if ($this->application->contact->imageId):?>
    <img src="/file/applications/<?php echo $this->application->contact->imageId ?>" class="img-polaroid" />
    <?endif?>
</div>
</div>

<div class="row-fluid show-grid">
<h2><?= $this->translate('work experience')?></h2>
      
<?php foreach( $this->application->cv->employments as $employment): ?>
<div class="span3"><?= $employment->startDate ?></div> <div class="span3"><?= $employment->endDate ?></div>
<div><?=  $employment->description ?></div>

<?php endforeach; // employments?>    
</div>
<div class="row-fluid show-grid">

<h2><?= $this->translate('education and training')?></h2>

<?php foreach( $this->application->cv->educations as $education): ?>
  <div class="span3"><?= $education->startDate ?></div> <div class="span3"><?= $education->endDate ?></div>
  <div><?=  $education->description ?></div>
<?php endforeach; // eucations?>    
</div>


<div class="row-fluid show-grid">

<h2><?= $this->translate('personal skills')?></h2>

<?php foreach( $this->application->cv->skills as $kill): ?>
  <div class="span3"><?=$this->translate('native language')?></div> 
  <div class="span3">TODO</div>
<?php endforeach; // skills?>    
</div>
