<?php 
/**
 * Cross Applicant Management
 *
 * @filesource
 * @copyright (c) 2013 Cross Solution (http://cross-solution.de)
 * @license   AGPLv3
 */

use Applications\Entity\StatusInterface as Status;
      
$this->headTitle($this->translate('Details'));
?>
<style>
body {
	font-family: Arial;
}
.header {
	text-align: right; 
	border-bottom: 1px solid #000000; 
	font-size: 10pt;
}
.footer {
	vertical-align: bottom; 
	font-size: 8pt;
    color: #000000; 
}
.address,
.personal-information {
	vertical-align: top;
	width: 100%;
	border-spacing: 0px;
}
table.list {
	width: 100%;
	border: 1px solid #e4e4e4;
	border-spacing: 0px;
}
table.list tr td {
	vertical-align: top;
	border-bottom: 1px solid #f4f4f4;
	padding: 3px;
}
th {
	background-color: #f4f4f4;
}
</style>
<sethtmlpageheader name="header" value="on" show-this-page="1"/>
<htmlpageheader name="header">
<div class="header">Bewerbung vom: <?php echo strftime('%x %X', $application->dateCreated->getTimestamp()); ?></div>
</htmlpageheader>
<htmlpagefooter name="footer">
<table width="100%" class="footer"><tr>
    <td width="33%">{DATE d.m.Y}</td>
    <td width="33%" align="center">{PAGENO}/{nbpg}</td>
    <td width="33%" style="text-align: right; ">Bewerbung</td>
    </tr></table>
</htmlpagefooter>
<sethtmlpagefooter name="footer" value="on"/>

<h1><?php echo $this->translate('application details') ?></h1>

<h2><?php echo $this->translate('personal information')?></h2>
<table class="personal-information" width="100%">
 <tr>
  <td>
   <table class="address">
    <tr>
     <td><?php echo $this->translate('name')?>:</td>
     <td><?php echo $this->application->contact->firstName.' '.$this->application->contact->lastName ?></td>
    </tr>
    <?php if (isset($this->application->contact->street)): ?>
    <tr>
     <td><?php echo $this->translate('Street')?>:</td>
     <td><?php echo $this->application->contact->street .' '.$this->application->contact->housenumber?></td>
    </tr>
    <?php endif; ?>
    <?php if (isset($this->application->contact->city)): ?>
    <tr>
     <td><?php echo $this->translate('City')?>:</td>
     <td><?php echo $this->application->contact->postalcode.' '.$this->application->contact->city ?></td>
    </tr>
    <?php endif; ?>
    <tr>
     <td><?php echo $this->translate('E-Mail')?>:</td>
     <td><?php echo $this->application->contact->email ?></td>
    </tr>
    <tr>
     <td><?= $this->translate('Phone')?>:</td>
     <td><?=  $this->application->contact->phone ?></td>
    </tr>
   </table>
  </td>
  <td align="right">
    <img src="/tmp/ich.jpg" />
    <?php if ($this->application->contact->image):?>
    <!-- <img src="<?php echo $this->url('file', array('filestore' => 'applications', 'fileId' => $this->application->contact->image->id)) ?>" class="img-thumbnail" />-->
    <?endif?>
  </td>
 </tr>
</table>
</div>

<h2><?=$this->translate('Summary')?></h2>
<div class="row">
<?php echo nl2br($this->application->summary) ?>
</div>

<?php if(count($this->application->cv->employments)>0):?>
<h2><?= $this->translate('work experience')?></h2>
<table class="list"> 
<tr>
 <th align="left"><?=$this->translate('Start')?></th>
 <th align="left"><?=$this->translate('End')?></th>
 <th><?=$this->translate('Description')?></th>
</tr>
<?php foreach( $this->application->cv->employments as $employment): ?>
<tr>
 <td><?= $employment->startDate ?></td>
 <td><?= $employment->endDate ?></td>
 <td><?=  $employment->description ?></td>
</tr>
<?php endforeach; // employments?>
</table>
<?php endif;?> 

<?php if(count($this->application->cv->educations)>0):?>
<h2><?= $this->translate('education and training')?></h2>
<table class="list"> 
<tr>
 <th align="left"><?=$this->translate('Start')?></th>
 <th align="left"><?=$this->translate('End')?></th>
 <th><?=$this->translate('Description')?></th>
</tr>
<?php foreach( $this->application->cv->educations as $education): ?>
  <tr>
   <td><?php echo $education->startDate ?></td>
   <td><?php echo $education->endDate ?></td>
   <td><?php echo $education->description ?></td>
  </tr>
<?php endforeach; // eucations?>    
</table>
<?php endif;?> 

<?php if(count($this->application->cv->skills)>0):?>
<h2><?= $this->translate('personal skills')?></h2>
<?php foreach( $this->application->cv->skills as $kill): ?>
  <div class="col-md-3"><?=$this->translate('native language')?></div> 
  <div class="col-md-3">TODO</div>
<?php endforeach; // skills?>
<?php endif;?>

<?php if(count($this->application->attachments)>0):?>
<h2><?= $this->translate('Attachments')?></h2>
<?php foreach( $this->application->attachments as $attachment): ?>
<div class="row show-grid">
  <div class="col-md-3">
    <a href="<?php echo $this->url('file', array(
        'filestore' => 'applications', 
        'fileId' => $attachment->id,
        'fileName' => $attachment->name
    ))?>"><?php echo $attachment->name ?></a></div>
    <div class="col-md-3"><?php echo $attachment->type?></div>
    <div class="col-md-3"><?php echo $attachment->prettySize ?></div>
</div>
<?php endforeach; // skills?>
<?php endif;?>

