<?php

$columns = array(
        /*@translate*/ 'Applicant' => false,
		/*@translate*/ 'Career' => false,
		/*@translate*/ 'Attachments' => false,	
        /*@translate*/ 'Job' => false,	
        /*@translate*/ 'Status' => 'status',
        /*@translate*/ 'Modified' => 'date',
        /*@translate*/ 'Actions' => false,
);

if ('-' == $this->sort{0}) {
    $sortBy  = substr($this->sort, 1);
    $sortDir = false;
} else {
    $sortBy  = $this->sort;
    $sortDir = true;
}

?>

<table class="table table-striped table-bordered table-hover" id="application-list">
<thead>
<tr>
<?php foreach ($columns as $label => $sort):?>
    <th>
    <?php if (false === $sort): echo $this->translate($label); 
          else:
              if ($sort == $sortBy):
                  $icon = ' <span class="pull-right glyphicon glyphicon-chevron-' . ($sortDir ? 'up' : 'down') . '"></span>';
                  $dir = !$sortDir;
              else:
                  $dir = true;
                  $icon = '';
              endif;
              $sortParam = array('sort' => ($dir ? '' : '-') . $sort);
              $url = $this->url(
                  'lang/applications', array(), 
                  array('query' => array_merge($this->params()->fromQuery(), $sortParam)),
                  true
              );
            ?><a href="<?php echo $url?>"><?php echo $this->translate($label).$icon?></a>     
    <?php endif; ?>
    </th>
<?php endforeach; ?>
</tr>
</thead>

<tbody>
<?foreach ($applications as $application):?>
<tr>
    <td>
    <div class="col-md-3">
    <?php if ($application->contact->imageId):?>
    <img src="/file/applications/<?php echo $application->contact->imageId ?>" class="img-thumbnail cam-thumbnail" />
    <?php else:?>
    <span style="font-size:50px" class="glyphicon glyphicon-user"></span>
    <?php endif?>
    </div>    
       <?php echo $this->translate($this->salutation($application->contact->gender))?>
       <?php echo $application->contact->displayName?><br>
       <?php echo $application->contact->city?>
    </td>
    <td>
    <?php echo $this->translate('work experience')?>
    </td>
    <td>   
     <?php if(count($application->attachments)>0):?>
     <ul>
     <?php foreach ($application->attachments as $attachment):?>
       <li><a href="<?php echo $attachment->uri?>"><?php echo $attachment->name ?></a></li>
     <?php endforeach;?>
     </ul>
     <?php else:?>
     <?php echo $this->translate('no attachments')?>
     <?php endif;?>
    </td>
    <td>
         <a href="<?php echo $this->url('lang/applications/detail', array('id' => $application->id), /* reuse matched params*/ true)?>">
          <?php echo $application->job->title ?>
         </a>         
    </td>
    <td><?php echo $application->status ?></td>
    <td title="Created: <?php echo $this->dateFormat($application->dateCreated,'short');?>">
        <?php echo $this->dateFormat($application->dateModified);?>
    </td>
    <td>
        <div class="btn-group">
            <a href="<?php echo $this->url('lang/applications/detail', array('id' => $application->id), true)?>" class="btn btn-mini btn-success" title="<?php echo $this->translate('view')?>"><span class="glyphicon glyphicon-eye-open icon-white"></span></a>
            <?php if ($this->acl($application, 'delete')):?>
            <a href="<?php echo $this->url('lang/applications/detail', array('id' => $application->id), array('query' => 'action=delete'), true)?>" class="btn btn-mini btn-danger" title="<?php echo $this->translate('delete')?>"><span class="glyphicon glyphicon-remove icon-white"></span></a>
            <?php endif ?>
        </div>
    </td>
</tr>

<?endforeach?>
</tbody>

</table>
<?php echo $this->paginationControl($applications, 'Sliding', 'pagination-control', array('lang' => $this->params('lang'), 'route' => 'lang/applications'));?>
