<?php 
/**
 * YAWIK
 *
 * @filesource
 * @copyright (c) 2013-2104 Cross Solution (http://cross-solution.de)
 * @license   AGPLv3
 */
if ($this->job):        $subTitle = sprintf($this->translate('for the job "%s"'), $this->job->title);
elseif ($this->byJobs): $subTitle = $this->translate('to all of your jobs');
else:                   $subTitle = false;
endif;

$this->headTitle($this->translate('Applications') . ($subTitle ? ' ('. $subTitle . ')' : ''));

$this->headScript()->appendFile($this->basePath('js/bloodhound.js'))
                   ->appendFile($this->basePath('js/typeahead.jquery.js'))
                   ->appendFile($this->basePath('/Core/js/core.js'))
                   ->appendFile($this->basePath('/Core/js/multiCheckbox.js'));
$this->headScript()->appendFile($this->basepath('/Core/js/core.pagination.js'));
$this->headScript()->appendFile($this->basePath('Applications/js/applications.index.js'));

?>      
<h1>
  <?=$this->translate('List of all applications')?>
  <? if ($subTitle): ?>
    <small><?php echo $subTitle ?></small>
  <?php endif;?>
</h1>
<div id="apps-modal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h3>header ...</h3>
            </div>
            <div class="modal-body">
                body ...
            </div>
            <div class="modal-footer">
                <button data-dismiss="modal" class="btn btn-default" type="button"><? echo $this->translate('Cancel'); ?></button>
                <button id="modal-submit" class="btn btn-primary"><? echo $this->translate('Send mail'); ?></button>
            </div>
        </div>
    </div>
</div>


<div class="container col-md-12">
<nav class="navbar cam-toolbar"> 
    <form id="search-applications-form" class="form-inline" action="<?php echo $this->basePath('/de/applications')?>" method="get">          
      <div id="search-applications form-group has-feedback" class="row">
        <input class="form-control" id="search-applications-input" 
               placeholder="<?php echo $this->translate('search applications')?> ..." 
               name="search" 
               type="text"
               <?php if ($this->search): ?>value="<?php echo $this->search ?>" <?php endif ?>>
               
        <input class="form-control" type="text" id="job-filter" name="job_title" placeholder="<?php echo $this->translate('Enter job title')?> ..."
        <?php if ($this->job): ?> value="[<?php echo $this->job->applyId ?>] <?php echo $this->job->title ?>"<?php endif ?>>
        <select class="form-control" name="job_status">
<?php foreach ($this->applicationStates as $applicationStatus): ?>
    <option <?php echo $applicationStatus=='all'?'class="yk-icon yk-icon-filter"':'';?>value="<?php echo $applicationStatus; ?>" <?php echo isset($_GET['job_status'])&&$_GET['job_status']==$applicationStatus?'selected="selected" ':''?>>
    <?php echo $this->translate($applicationStatus); ?>
    </option>
<?php endforeach; ?>
        </select>
        <input id="job-filter-value" type="hidden" name="job" <?php if ($this->job):?> value="<?php echo $this->job->id ?>"<?php endif?>>
        <button class="btn btn-primary" type="submit"><?php echo $this->translate('Search')?></button>
        <a href="<?php echo $this->url('lang/applications', array(), array('query' => array('clear' => 1)), true) ?>"
           class="btn btn-default"><?php echo $this->translate('Clear') ?></a>
      </div>
    </form>
  </nav>
</div>
<div class="pagination-container" data-uri="<?php echo $this->url('lang/applications', array(), 
                  array('query' => $this->params()->fromQuery()), true) ?>">
<?php echo $this->render('applications/manage/index.ajax.phtml') ?>
</div>