<?php

$columns = array(
        /*@translate*/ 'Applicant' => array(),
        /*@translate*/ 'Career' 
    => array('class' => 'cam-career'),
        /*@translate*/ 'Attachments' 
    => array('class' => 'cam-attachment'),	
        /*@translate*/ 'Job' 
    => array('class' => 'cam-job'),	
        /*@translate*/ 'Status' 
    => array('sort' => 'status'),
        /*@translate*/ 'Modified' 
    => array('sort' => 'date'),
        /*@translate*/ 'Actions' 
    => array(),
);

if ('-' == $this->sort{0}) {
    $sortBy  = substr($this->sort, 1);
    $sortDir = false;
} else {
    $sortBy  = $this->sort;
    $sortDir = true;
}

echo $this->paginationControl($applications, 'Sliding', 'pagination-control', array('lang' => $this->params('lang'), 'route' => 'lang/applications'));
?>
<table class="cam-table" id="cam-application-list">
<thead>
<tr>
<?php foreach ($columns as $label => $option):?>
    <th <?php echo isset($option['class'])?'class="'.$option['class'].'"':'';?>>
    <?php if (! isset($option['sort'])): echo $this->translate($label); 
          else:
              if ($option['sort'] == $sortBy):
                  $icon = '<span class="text-right cam-icon-sort' . ($sortDir ? '-desc' : '-asc') . '"></span>';
                  $dir = !$sortDir;
              else:
                  $dir = true;
                  $icon = '<span class="pull-right cam-icon-sort"></span>';
              endif;
              $sortParam = array('sort' => ($dir ? '' : '-') . $option['sort']);
              $url = $this->url(
                  'lang/applications', array(), 
                  array('query' => array_merge($this->params()->fromQuery(), $sortParam)),
                  true
              );
            ?>
            <a href="<?php echo $url?>"><?php echo $this->translate($label).$icon?></a>     
    <?php endif; ?>
    </th>
<?php endforeach; ?>
</tr>
</thead>

<tbody>
<?foreach ($applications as $application):
$isUnread = $application->isUnreadBy($this->auth('id'));?>
  <tr<?php echo ($isUnread?' class="cam-new"':"")?>>
    <td>
    <div class="portrait">
    <?php if ($application->contact->image):?>
    <img src="<?php echo $application->contact->image->uri ?>" />
    <?php else:?>
    <span class="cam-icon-portrait"></span>
    <?php endif?>
    </div>    
       <?php echo $this->translate($this->salutation($application->contact->gender))?>
       <?php echo $application->contact->displayName?><br>
       <?php echo $application->contact->city?>
    </td>
    <td class="cam-career">
    <?php if (count($application->cv->educations)>0):?>
      <?php echo $this->translate('education').': '.$this->period($application->cv->educations).' '.$this->translate('years')?><br/>
    <?php endif;?>
    <?php if (count($application->cv->employments)>0):?>
      <?php echo $this->translate('work experience').': '.$this->period($application->cv->employments).' '.$this->translate('years')?><br/>
    <?php endif;?>
    </td>
    <td class="cam-attachment">   
     <?php if(count($application->attachments)>0):?>
     <ul>
     <?php foreach ($application->attachments as $attachment):?>
       <li><a href="<?php echo $attachment->uri?>"><?php echo $attachment->name ?></a></li>
     <?php endforeach;?>
     </ul>
     <?php else:?>
     <?php echo $this->translate('no attachments')?>
     <?php endif;?>
    </td>
    <td class="cam-job">
         <a href="<?php echo $this->url('lang/applications/detail', array('id' => $application->id), /* reuse matched params*/ true)?>">
          <?php echo $application->job->title ?>
         </a>         
    </td>
    <td><?php echo $application->status->name ?></td>
    <td title="Created: <?php echo $this->dateFormat($application->dateCreated,'short');?>">
        <?php echo $this->dateFormat($application->dateModified);?>
    </td>
    <td>
        <div class="btn-group">
            <a href="<?php echo $this->url('lang/applications/detail', array('id' => $application->id), true)?>" class="btn btn-mini btn-default" title="<?php echo $this->translate('edit')?>"><span class="cam-icon-edit"></span></a>
        </div>
    </td>
</tr>

<?endforeach?>
</tbody>

</table>
<?php echo $this->paginationControl($applications, 'Sliding', 'pagination-control', array('lang' => $this->params('lang'), 'route' => 'lang/applications'));?>
