<?php
/**
 * YAWIK
 *
 * @filesource
 * @copyright (c) 2013-2104 Cross Solution (http://cross-solution.de)
 * @license   AGPLv3
 */
?>
<div class="modal-title">
<?php echo $this->profile->name ?>
</div>
<div class="modal-body">
<div class="row"><div class="col-md-12 text-right"><?php echo $this->link($this->profile->link, $this->translate('View online')) ?></div></div>
<div class="row">
<?php if (count($this->profile->educations)):?>
<div class="col-md-12">
<h5><?= $this->translate('education and training')?></h5>
<table class="cam-table"> 

<?php foreach( $this->profile->educations as $education): ?>
  <tr>
    <?php 
        $date = ($education->startDate ? $education->startDate . ' - ' : '')
              . $education->endDate;
        $desc = trim($education->description);
        $tmpl = $desc
              ? '<td>%s<br><strong>%s</strong></td><td>%s</td>'
              : '<td colspan="2">%s<br><strong>%s</strong></td>';
        
        echo sprintf($tmpl, $date, $education->organizationName, $desc);
    ?>
  </tr>
<?php endforeach; // eucations?>    
</table>
</div>
<?php endif;?> 

<?php if(count($this->profile->employments)>0):?>
<div class="col-md-12">
<h5><?= $this->translate('work experience')?></h2>
<table class="cam-table">

<?php foreach( $this->profile->employments as $employment): ?>
    <tr>
    <?php $date = $employment->endDate ? $employment->startDate . ' - ' . $employment->endDate 
                                        : '<span style="white-space:nowrap;">' 
                                          . $this->translate('Since') . ' ' . $employment->startDate
                                          . '</span>';
          $desc = trim($employment->description);
          $tmpl = $desc
                ? '<td>%s<br><strong>%s</strong></td><td>%s</td>'
                : '<td colspan="2">%s<br><strong>%s</strong></td>';
        
          echo sprintf($tmpl, $date, $employment->organizationName, $desc);
    ?>
    </tr>
<?php endforeach; // employments?>
</table>
</div>
<?php endif;?> 


<div class="col-md-12 sp-raw-data-<?php echo $this->profile->id ?>">
<h5 style="cursor:pointer"><?php echo $this->translate('Profile data') ?>.
<span class="pull-right fa fa-chevron-up"></span></h2>
<pre>
<?php //var_export($this->profile->getData());
    function sp_export_data($data, $level=0)
    {
        foreach ($data as $key => $value) {
            $indent = str_pad(' ', $level * 4);
            if (is_array($value)) {
                echo $indent . $key . ": {\n";
                sp_export_data($value, $level+1);
                echo $indent . "}\n";
                continue;
            }
            
            echo $indent . $key . ': ' . $value . "\n";
        }
    } 
    sp_export_data($this->profile->getData());
    
    ?>
</pre>
</div>

<script type="text/javascript">
;(function($) {
	$(function() {
		var $rawDataDiv = $('.sp-raw-data-<?php echo $this->profile->id ?>');
		var $toggle     = $rawDataDiv.find('h5');
		var $display    = $rawDataDiv.find('pre');
		
		$display.hide();
		$toggle.click(function() { 
			$display.slideToggle(); 
			var $icon = $toggle.find('span');
			if ($icon.hasClass('fa-chevron-up')) {
				$icon.removeClass('fa-chevron-up').addClass('fa-chevron-down');
			} else {
				$icon.removeClass('fa-chevron-down').addClass('fa-chevron-up');
			}
			return false; 
		});
	});
})(jQuery);

</script>

</div>
</div>
