<?php
/**
 * YAWIK
 *
 * @filesource
 * @copyright (c) 2013-2104 Cross Solution (http://cross-solution.de)
 * @license   AGPLv3
 */
/**
 * render a linkedin profile
 */
 ?>
<div class="panel panel-default">
<div class="panel-heading"><?php echo $this->translate('personal information'); ?></div>
<div class="panel-body">
<div class="pull-left">
<img class="yk-portrait" src="<?php echo $this->{'picture-url'};?>"/>

</div>
<div>
<b><?php echo $this->{'first-name'};?> <?php echo $this->{'last-name'};?></b>
<br/><?php echo $this->location['name'];?>
<br/>
<?php 


if(isset($this->birth_date['day'])):
  $date=DateTime::createFromFormat('Y-m-d', $this->birth_date['year'] . '-' . 
                                            $this->birth_date['month'] . '-'.
                                            $this->birth_date['day']);
  echo $this->translate('Birthday').': '; 
  echo $this->DateFormat($date,'short','none');
elseif(isset($this->birth_date['month'])):
  echo $this->translate("Year of birth");
  echo $this->birth_date['month'].'/';
  echo $this->birth_date['year'];
elseif(isset($this->birth_date['year'])):
  echo $this->translate("Year of birth").':'; 
  echo $this->birth_date['year'];
endif;
?>

<br/><i class="yk-icon yk-icon-linkedin"></i> <?php echo $this->link($this->{'public-profile-url'}); ?>
</div>
</div>
</div>

<?php if(isset($this->educational_background)):?>
<div class="panel panel-default">
<div class="panel-heading"><?php echo $this->translate("education")?></div>
<table class="table table-bordered table-condensed">
<tr>
<th><?php echo $this->translate("Date")?></th>
<th><?php echo $this->translate("School or university")?></th>
<th><?php echo $this->translate("Notes")?></th>
</tr>
<?php foreach($this->educational_background['schools'] as $edu):?>
<tr>
 <td>
   <?php echo isset($edu['begin_date'])?$edu['begin_date']:'';?>
   <?php echo isset($edu['end_date'])?' - '.$edu['end_date']:'';?>
 </td>
 <td>
   <?php echo isset($edu['name'])?$edu['name']:'';?>
   <?php echo isset($edu['subject'])?'<br/>'.$edu['subject']:'';?>
   <?php echo isset($edu['degree'])?'<br/>'.$edu['degree']:'';?>
 </td> 
 <td>
   <?php echo isset($edu['notes'])?$edu['notes']:'';?>
 </td>
</tr>
<?php endforeach;?>
</table>
</div>
<?php endif;?>

<?php if(isset($this->positions)):?>
<div class="panel panel-default">
<div class="panel-heading"><?php echo $this->translate("work experience");?></div>
<table class="table table-bordered table-condensed">
<tr>
<th><?php echo $this->translate("Date")?></th>
<th><?php echo $this->translate("Employer")?></th>
<th><?php echo $this->translate("Position")?></th>
<th><?php echo $this->translate("Description")?></th>
</tr>
<?php foreach($this->positions as $work_experience):?>
<?php if(isset($work_experience['id'])):?>
<tr>
 <td>
 <?php echo isset($work_experience['start-date']['year'])?$work_experience['start-date']['year']:'';?>
 <?php echo (isset($work_experience['is-current']) and $work_experience['is-current'])?$this->translate('ongoing'):'';?>
 </td>
 <td>
   <?php echo isset($work_experience['company']['name'])?$work_experience['company']['name']:'';?>
   <?php echo isset($work_experience['company']['size'])?'<br/>'.$this->translate('Size'). ': '. $work_experience['company']['size']:'';?>
   <?php echo isset($work_experience['company']['type'])?'<br/>'.$this->translate('Type'). ': '.$work_experience['company']['type']:'';?>
  
 </td>
 <td>
   <?php echo isset($work_experience['title'])?$work_experience['title']:'';?>
 </td>
 <td>
  <?php echo isset($work_experience['company']['industry'])?'<br/>'.$this->translate('Industry'). ': ' .$work_experience['company']['industry']:'';?>
 <?php echo isset($work_experience['description'])?$work_experience['description']:'';?>
 </td>
</tr>
<?php endif;?>
<?php endforeach;?>
</table>
</div>
<?php endif;?>

<?php if(isset($this->languages)):?>
<div class="panel panel-default">
<div class="panel-heading"><?php echo $this->translate("language skills"); ?></div>
<div class="panel-body">
 <br/><?php echo join(", ",array_keys($this->languages))?>
</div>
</div>
<?php endif;?>
