<?php
/**
 * YAWIK
 *
 * @filesource
 * @copyright https://yawik.org/COPYRIGHT.php
 * @license   MIT
 */

$form->setAttributes(array(
    'action' => $_SERVER['REQUEST_URI']
));
$form->get('mailText')->setAttribute('style', 'height: 250px');
?>
<div>
<?php
list ($email, $name) = each ($recipient);
if (is_int($email)) {
    $email = $name;
    $name = '';
}

echo sprintf($this->translate("To") . ': ' . '"%s" &lt;%s&gt;<br>', $name, $email);

?>
</div>
<?php
echo $this->form($form, Core\Form\View\Helper\Form::LAYOUT_HORIZONTAL);