<?php
/**
 * YAWIK
 *
 * @filesource
 * @license MIT
 * @copyright  2013 - 2015 Cross Solution <http://cross-solution.de>
 */
?>

        <?php if (true === $this->ok): ?>
            <p><?php echo $this->translate('The base configuration file was successfully created. You can now start using YAWIK by reloading the browser window.', 'Install') ?></p>
        <?php else: ?>
            <p><?php echo sprintf(
                                $this->translate('The configuration file could not be created automatically. So please create a file called "%s" in the directory "%s" with the following content:', 'Install'),
                                'yawik.config.global.php', 'config/autoload'
                          )?></p>
        <pre><?php echo $this->escapeHtml($this->ok) ?></pre>
                <p><?php echo $this->translate('When you created the file you can start using YAWIK by reloading the browser window.', 'Install') ?></p>
        <?php endif ?>
