<?php $this->headTitle($this->translate("Reset your password")); ?>
    <h1><?php echo $this->translate("Reset your password"); ?></h1>

    <div class="alert alert-info">
        <?php echo $this->translate('Please enter your username or email address. You will receive a link to create a new password via email.'); ?>
    </div>

<?php
/** @var \Auth\Form\ForgotPassword $form */
$form = $this->form;
$form->setAttribute('action', $this->url('lang/forgot-password'));
?>

<?php echo $this->form($form); ?>