<?php

$this->headTitle($this->translate('My profile'));
//$this->headscript()->appendFile($this->basepath('js/Core/core.forms.js'));

?>

<h1><?php echo $this->translate('My profile')?></h1>

<?if ($this->status): ?>
<div id="user-profile-form-response" class="alert alert-<?php echo $this->status?>">
    <?php echo $this->text ?> 
</div>
<?else:?>
<div id="user-profile-form-response" class="alert hide">

</div>
<?endif?>

<?php 
    $this->form->setAttribute('action', $this->url('lang/manage-profile', array(), true));
    echo $this->form($this->form, 'form-inline'); 
    
    //echo $this->formPartial($this->form, 'auth/my-profile')?>

