<?php
/**
 * YAWIK
 * View template of the Login site
 *
 * @copyright (c) 2013-2104 Cross Solution (http://cross-solution.de)
 * @license   MIT
 */
?>
<?php $this->headTitle($this->translate('My password'));?>

<h1><?php echo $this->translate('My password')?></h1>
<?php if ($this->status):?>
<div id="user-profile-form-response" class="alert cam-<?php echo $this->status?>">
    <?php echo $this->text ?> 
    <a class="close" data-dismiss="alert" href="#" aria-hidden="true">&times;</a>
</div>
<?php else:?>
<div id="user-profile-form-response" class="alert hide">

</div>
<?php endif?>
<?php 
    $this->form->setAttribute('action', $this->url('lang/my', array('action' => 'password'), true));
    echo $this->form($this->form, 'form-inline'); 
?>