<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'InstallTest\Controller\Plugin\PrerequisitesTest'      => __DIR__ . '/InstallTest/Controller/Plugin/PrerequisitesTest.php',
  'InstallTest\Controller\Plugin\YawikConfigCreatorTest' => __DIR__ . '/InstallTest/Controller/Plugin/YawikConfigCreatorTest.php',
  'InstallTest\Form\InstallationTest'                    => __DIR__ . '/InstallTest/Form/InstallationTest.php',
  'InstallTest\Validator\MongoDbConnectionStringTest'    => __DIR__ . '/InstallTest/Validator/MongoDbConnectionStringTest.php',
);
