<?php
/**
 * YAWIK
 * View template of the Login site
 *
 * @copyright (c) 2013-2015 Cross Solution (http://cross-solution.de)
 * @license       MIT
 */
?>
<?php if ($this->required): ?>
    <?php $this->headTitle($this->translate('Login required')); ?>
    <h1><?php echo $this->translate('Please authenticate yourself to proceed') ?></h1>
<?php else: ?>
    <?php $this->headTitle($this->translate('Login')); ?>
    <h1><?php echo $this->translate('Login'); ?></h1>
<?php endif; ?>
<?php
$this->form->setAttributes(
    array(
        'method' => 'post',
        'id'     => 'login-form',
        'action' => $this->url(
            'lang/auth',
            array(),
            array('query' => $this->params()->fromQuery()), true
        ),
    )
);
?>

<div id="form-login-with-social-bottons">
    <div class="form-content">
        <?php echo $this->form($this->form); ?>
        <div class="row">
            <div class="col-md-6">
                <a href="<?php echo $this->url('lang/forgot-password'); ?>"
                   title="<?php echo $this->translate('I forgot my password'); ?>" class="small">
                    <?php echo $this->translate('I forgot my password'); ?>
                </a>
            </div>
            <?php if (!isset($this->allowRegister) || $this->allowRegister == true): ?>
                <div class="col-md-6">
                    <a href="<?php echo $this->url('lang/register'); ?>"
                       title="<?php echo $this->translate('Register'); ?>"
                       class="small">
                        <?php echo $this->translate('Register'); ?>
                    </a>
                </div>
            <?php endif; ?>
        </div>
        <?php echo $this->partial('core/social-buttons');?>
    </div>
</div>
