<?php 
/**
 * Cross Applicant Management
 * View template of the Login site
 * 
 * @copyright (c) 2013 Cross Solution (http://cross-solution.de)
 * @license   GPLv3
 */
?>
<?php if ($this->required):?>
    <?php $this->headTitle($this->translate('Login required'));?>
    <h1><?php echo $this->translate('Please authenticate yourself to proceed')?></h1>
<?php else:?>
    <?php $this->headTitle($this->translate('Login'));?>
    <h1><?php echo $this->translate('Login');?></h1>
<?php endif; ?>

<?php if ($this->status): ?>
<div id="login-form-response" class="alert alert-<?php echo $this->status ?>">
<?php echo $this->text ?>
</div>
<?php else: ?>
<div id="login-form-response" class="alert hide">

</div>
<?php endif; ?>

<p><?php 
$this->form->setAttributes(array(
    'action' => $this->url('lang/auth', array(), array('query' => array_map('urlencode', $this->params()->fromQuery())), true),
    'method' => 'post',
    'id' => 'login-form',
));
?>

<?php echo $this->form($this->form); ?>

</p>

