<?php
/**
 * YAWIK
 * View template of the Login site
 *
 * @copyright (c) 2013-2015 Cross Solution (http://cross-solution.de)
 * @license   MIT
 */
?>
<?php if ($this->required):?>
    <?php $this->headTitle($this->translate('Login required'));?>
    <h1><?php echo $this->translate('Please authenticate yourself to proceed')?></h1>
<?php else:?>
    <?php $this->headTitle($this->translate('Login'));?>
    <h1><?php echo $this->translate('Login');?></h1>
<?php endif; ?>

<p><?php
$this->form->setAttributes(array(
    'action' => $this->url('lang/auth', array(), array('query' => $this->params()->fromQuery()), true),
    'method' => 'post',
    'id' => 'login-form',
));
?>
</p>
<?php
/** @var \Auth\Form\Login $form */
$form = $this->form;
?>
<div id="form-login-form" class="form-container">
    <div class="form-content">
        <?= $this->form()->openTag($form); ?>
        <?= $this->formCollection($form->get('credentials')); ?>
        <div class="row">
            <div class="col-md-3">&nbsp;</div>
            <div class="col-md-3">
                <a href="<?= $this->url('lang/forgot-password'); ?>" title="<?= $this->translate('I forgot my password'); ?>" class="small">
                    <?= $this->translate('I forgot my password'); ?>
                </a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <?php
                if (!isset($this->allowRegister) || $this->allowRegister==True ):
                ?>
                <a href="<?= $this->url('lang/register'); ?>" title="<?= $this->translate('Register'); ?>" class="small">
                    <?= $this->translate('Register'); ?>
                </a>
                <?php
                endif;
                ?>
            </div>
        </div>
        <?= $this->formRow($form->get('buttons')); ?>
        <?= $this->form()->closeTag($form); ?>
    </div>
</div>

