<?php
/**
 * YAWIK
 *
 * @copyright (c) 2013-2014 Cross Solution (http://cross-solution.de)
 * @license   MIT
 */

/**
 * Displays the formular to comment an application
 *
 * @package      YAWIK
 * @subpackage   Applications
 * @author       gelhausen@cross-solution.de
 */

if ($this->isSaved) {
    echo 'ok';
    return;
} 
$this->commentForm->setAttribute(
    'action', 
    $this->url('lang/applications/comments', array(), true) 
    . '?mode=' . $this->mode . '&id=' . $this->identifier 
);

echo $this->form($this->commentForm, Core\Form\View\Helper\Form::LAYOUT_HORIZONTAL);



