<?php
/**
 * Cross Applicant Management
 *
 * @filesource
 * @copyright (c) 2013 Cross Solution (http://cross-solution.de)
 * @license   AGPLv3
 */

?>

<?php if (count($this->comments)): ?>

<?php foreach($this->comments as $comment):
    $isOwnComment = $comment->user->id == $this->auth('id');
?>

    <div class="panel panel-default">
        <div class="panel-heading">
            <div class="row">
                <div class="col-md-9">
                <h4 style="margin: 2px 0 0;"><?php echo $comment->user->info->displayName ?></h4>
                <div style="line-height: 10px; font-size: 10px">
                <span class="cam-icon-new" style="font-size: 10px;"></span> <?php echo $this->dateFormat($comment->dateCreated);?>
                
                <?php if ($comment->dateModified) : ?><span class="cam-icon-edit" style="font-size: 10px;"></span> <?php echo $this->dateFormat($comment->dateModified); endif ?>
                
                </div> 
                </div>
                <div class="col-md-3">
                <div class="pull-right panel panel-default" style="margin: 0">
                    <div class="panel-body" style="padding: 5px 10px;">
                
                        <?php echo $this->rating($comment->rating->average, 'compact') ?>
                    </div>
                </div>
                </div>
            </div>
            
        </div>
        <div class="panel-body">
        <?php if ($isOwnComment):?>
                <button class="pull-right comment-edit btn btn-default btn-xs" data-comment-id="<?php echo $comment->id ?>">
                    <span class="cam-icon-edit"></span>
                </button>
                <?php endif?>
            <?php echo nl2br($comment->message) ?>
            
        </div>
        
    </div>
<?php endforeach ?>
    
<?php else: ?>

    <div class="alert alert-info"><p>
        <?php echo $this->translate('There are no comments for this application yet. Be the first to comment by clicking the "Add new comment" button below!')?>
    </p></div>
    
<?php endif ?>