<?php
/**
 * Cross Applicant Management
 *
 * @filesource
 * @copyright (c) 2013 Cross Solution (http://cross-solution.de)
 * @license   AGPLv3
 */

?>

<?php if (count($this->comments)): ?>

<?php foreach($this->comments as $comment):
    $isOwnComment = $comment->user->id == $this->auth('id');
?>

    <div class="panel panel-<?php echo $isOwnComment ? 'primary' : 'default' ?>">
        <div class="panel-heading">
            <div class="row">
                <div class="col-md-6">
            <?php echo $comment->user->info->displayName ?><br>
                <small><?php echo $this->dateFormat($comment->dateCreated); 
                             if ($comment->dateModified) : echo ' (' . $this->dateFormat($comment->dateModified) . ')'; endif ?></small>
                </div>
                <div class="col-md-3">
            
                <?php if ($isOwnComment):?>
                <button class="comment-edit pull-left btn btn-default" data-comment-id="<?php echo $comment->id ?>">
                    <span class="cam-icon-edit"></span>
                </button>
                <?php endif?>
                </div>
                <div class="col-md-3">
                <div style="background-color: white; padding: 4px 20px 5px; border-radius: 2px;">
                <?php echo $this->rating($comment->rating->average, 'compact') ?>
                </div>
                </div>
            </div>
            
        </div>
        <div class="panel-body">
            <?php echo nl2br($comment->message) ?>
        </div>
    </div>
<?php endforeach ?>
    
<?php else: ?>

    <div class="alert alert-info"><p>
        <?php echo $this->translate('There are no comments for this application yet. Be the first to comment by clicking the "Add new comment" button below!')?>
    </p></div>
    
<?php endif ?>