<?php
    $id = $this->element->getEntity()->id;
    $lang = $this->params('lang');
?>
<h3><?php echo $this->translate("Job details")?></h3>
<div class="row">
    <div class="col-md-8">
        <div class="panel panel-default">
            <div class="panel-body">
                <iframe style="width:100%; height:800px;" src="<?php echo $this->url('lang/jobs/editTemplate', array('id' => $this->element->getEntity()->id)); ?>"></iframe>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="alert alert-info">
            <?php echo $this->translate("You are using a default template. You are free to create your own template, just contact the developing team for integration")?>
        </div>
        <div id="template-links">
            <a href="/<?php echo $lang ?>/jobs/template/<?php echo $id ?>/default">default</a><br />
            <a href="/<?php echo $lang ?>/jobs/template/<?php echo $id ?>/classic">classic</a><br />
            <a href="/<?php echo $lang ?>/jobs/template/<?php echo $id ?>/modern">modern</a><br />
            <div id="template-links-loading" style="display: none;">loading</div>
            <?php
                $this->headScript()->appendFile($this->basePath('/Jobs/js/templates.js'));
            ?>
        </div>
    </div>
</div>
<?php


?>
