

<div class="row">
    <div class="col-md-8">
        <div class="panel panel-default">
            <div class="panel-body">
                <iframe style="width:100%; height:800px;" src="<?php echo $this->url('lang/jobs/editTemplate', array('id' => $this->element->getEntity()->id)); ?>"></iframe>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="alert alert-info">
            <?php echo $this->translate("You are using a default template. You are free to create your own template, just contact the developing team for integration")?>
        </div>
    </div>
</div>
<?php


?>
