<?php
/**
 * YAWIK
 *
 * @filesource
 * @license MIT
 * @copyright  2013 - 2015 Cross Solution <http://cross-solution.de>
 */
?>

<div class="alert alert-success">
    <h4><?php echo $this->translate('You have accepted the invitation') ?></h4>
    <p><?php echo sprintf($this->translate('You are now part of the team of <b>%s</b>'), $this->organization) ?></p>
</div>

<?php if ($this->form): $this->form->setAttribute('data-handle-by', 'native')->get('passwordFieldset')->setLabel(null)?>
<div class="alert alert-info">
    <p><?php echo $this->translate('Please choose a password to be able to log in.') ?></p>

    </div>
<?php echo $this->form($this->form);?>


<?php endif;?>
