<?php
/**
 * Cross Applicant Management
 *
 * @filesource
 * @copyright (c) 2013 Cross Solution (http://cross-solution.de)
 * @license   AGPLv3
 */

?>
<div class="cam-panel">
<div class="cam-panel-head">
<h2>
 <a style="text-decoration: none;" href="<?php echo $this->url('lang/applications', array(), array('query' => $linkQuery), true)?>">
  <?php echo $this->translate('Current Applications')?>
 </a>
 <small>
 <?php #if ($hasJobs): ?>
 <?php 
      #$countTmpl = '<span style="font-size:16px; font-weight:bold;">%s</span>';
      #$newCount = $appRepo->countBy($this->auth('id'), /* unread */ true);
      #$totalCount = $appRepo->countBy($this->auth('id'));
      #echo sprintf($this->translate('%1$s new from %2$s total applications'),
      #             sprintf('<span class="badge">'.$countTmpl.'</span>', $newCount), 
      #             sprintf('<span class="badge">'.$countTmpl.'</span>', $totalCount))?>
 <?php #endif ?>
 </small>
</h2>
</div>
<div class="cam-panel-body">

<table class="cam-table" id="cam-application-list">
<thead>
 <tr>
  <th><?php echo $this->translate('Applicant')?></th>
  <th><?php echo $this->translate('Job')?></th>
  <th><?php echo $this->translate('Date')?></th>
 </tr>
</thead>
<?php foreach ($this->applications as $app):?>
    <tr>
      <td>
        <div class="portrait">
          <?php if ($app->contact->image):?>
            <img src="/file/applications/<?php echo $app->contact->image->id ?>" />
          <?php else:?>
            <span class="cam-icon-portrait"></span>
          <?php endif?>
        </div>
        <a href="<?php echo $this->url('lang/applications/detail', array('id' => $app->id), true)?>">
          <?php echo $this->translate($this->salutation($app->contact->gender))?>
          <?php echo $app->contact->displayName?><br>
          <?php echo $app->contact->city?>      
        </a>
      </td>
      <td><a href="<?php echo $app->job->link ?>"><?php echo $app->job->title?></a></td>
      <td><?php echo $this->dateFormat($app->dateCreated, 'short', 'none') ?></td>
    </tr>
<?php endforeach ?>
</table>
</div>
<div class="cam-panel-foot">
<?php
#echo $this->paginationControl($this->applications, 'Sliding', 'pagination-control', array('lang' => $this->params('lang'), 'route' => 'lang/applications'));
?>
</div>
</div>