<?php 
    $this->headTitle($this->translate('Apply'));
    $this->headscript()->appendFile($this->basepath('js/Core/jquery.formcollection.js'));
    $this->headscript()->appendScript('$(function(){$(".form-collection").formcollection();});');
    
    
?>
<h1><?php echo $this->translate('Application')?></h1>
<p class="lead"><?php printf(
    $this->translate('Apply to "%s" from "%s"'), 
    '<a href="/job-url" title="' . $this->translate('Go to job advertisement') . '">' . $this->escapehtml($job->title) . '</a>',
    'TestCompany'
) ?></p>

<?php echo $isApplicationSaved ? 'Yeehaw!' : $this->partial('form/application', array('form' => $form)) ?>