<?php $this->headStyle()->captureStart()?>
fieldset fieldset {padding-left: 30px;}
#image .img-polaroid {max-width: 120px; max-height: 180px;width: 120px;}
<?php $this->headStyle()->captureEnd()?>
<?php
$title = $this->translate('Create a new resume');
$this->headtitle($title);
$this->headscript()->appendFile($this->basepath('Core/js/jquery.formcollection.js'));
?>
<h1><?=$title?></h1>
<?=$this->formContainer($this->container)?>