<?php
    $id = $element->getAttribute('id');
    if (!$id) {
        $id = uniqid();
    }
    
    $label = $element->getLabel();
    
?>
<fieldset id="<?php echo $id?>">
<?php if ($label):?>
    <legend><?php echo $label ?></legend>
<?php endif;
    foreach ($element->getIterator() as $el): 
        
        if ($el instanceOf \Zend\Form\FieldsetInterface):
            $type = preg_replace('~^.*\\\\~', '', get_class($el));
            $type = preg_replace_callback('~[A-Z]~', function($m) { return '-' . strtolower($m[0]); }, lcfirst($type));
        
            $partial = "form/$type";
            if (!$this->resolver($partial)):
                $partial = "form/fieldset";
            endif;
            
        else:
            $type = $el->getAttribute('type');
            $partial = "form/$type";
            if (!$this->resolver($partial)):
                $partial = 'form/element';
            endif;
        endif;
        echo $this->partial($partial, array('element' => $el));
    endforeach ?>
</fieldset>