<?php
$this->formRow()->setShouldWrap(false);
$title = $this->element->getAttribute('title');
$modalboxid = $this->element->getAttribute('modalboxid');
$comment = $this->element->getAttribute('comment');
?>
<h6><?php echo $this->translate($title)?></h6>
<nav class="navbar">   
  <div class="col-md-1">
        <?php $first=true; foreach($this->element as $button):?>
            <?php $button->setAttribute('class', $button->getAttribute('class'));?>
            <?php echo $this->formRow($button);?>
        <?php endforeach;?>
  </div>
        <div class="col-md-11">      
          <?php echo $comment  ?>
        </div>
    <?php if (isset($modalboxid)) { ?>
        <div id="<?php echo $modalboxid ?>" class="modal fade modal-scrollable">
            <div class="modal-dialog modal-lg">
                <div class="modal-content">
                    <div class="modal-body"><?php echo $this->translate("please wait")?> ...</div>
                </div>
            </div>
        </div>
    <?php } ?>
</nav>

