
<?php 
$idPrefix = $element->getAttribute('id');
$name = $element->getName();


?>

<?php if ($title = $element->getAttribute('title')): ?>
<div class="radio-title hidden"><?php echo $title?></div>
<?php endif ?>
<?php foreach ($element->getValueOptions() as $key => $optionSpec): 

            
            $value           = '';
            $label           = '';
            $selected        = false;
            $disabled        = false;
            
            if (is_scalar($optionSpec)) {
                $optionSpec = array(
                    'label' => $optionSpec,
                    'value' => $key
                );
            }
    
            if (isset($optionSpec['value'])) {
                $value = $optionSpec['value'];
            }
            if (isset($optionSpec['label'])) {
                $label = $optionSpec['label'];
            }
            if (isset($optionSpec['selected'])) {
                $selected = $optionSpec['selected'];
            }
            if (isset($optionSpec['disabled'])) {
                $disabled = $optionSpec['disabled'];
            }
            $id = "$idPrefix-$value";
            
            ?>
    <label for=<?php echo "$idPrefix-$value"?>><?php echo $this->translate($label) ?></label>
    <input id="<?php echo "$idPrefix-$value"?>" type="radio" name="<?php echo $name ?>"
           value="<?php echo $value ?>"> 
<?php endforeach ?>
    


    