<?php
    $type = $element->getAttribute('type');
    if ('' == $type) {
        $type = 'text';
    }
    
    
    $id = $element->getAttribute('id');
    if (!$id) {
        $id = uniqid();
        $element->setAttribute('id', $id);
    }
    
    $wrapElement = !in_array($type, array('submit', 'button', 'hidden'));

    $partial = "form/$type";
    if (!$this->resolver($partial)) {
        $partial = false; //"form/element";
    }

    if (!$element->hasAttribute('title') && !$element instanceOf MultiCheckbox && $element->getLabel()) {
        $element->setAttribute('title', $element->getLabel());
    }
?>

<?php if ($wrapElement):?>
<div id="<?php echo $id ?>-wrapper" class="form-element">
<?php endif; ?>
<?php if ($label = $element->getLabel()): ?>
    <label for="<?php echo $id ?>"><?php echo $this->translate($label) ?></label>
<?php endif ?>
    <?php echo $partial 
               ? $this->partial($partial, array('element' => $element))
               : $this->formElement($element); ?>    
<?php if ($wrapElement): ?></div><?php endif ?>




