<?php
/**
 * YAWIK
 *
 * @filesource
 * @license MIT
 * @copyright  2013 - 2016 Cross Solution <http://cross-solution.de>
 */

?>
<div class="yktm-management-fieldset">
<?php echo $this->formCollection($this->element);

?>
<style type="text/css">
    .yk-tree-management-form .panel-body .row {
        margin-bottom: 20px;
    }
    .yk-tree-management-form .panel-body .row:last-child,
    .yk-tree-management-form .panel-body .panel:last-child {
        margin-bottom: 0;
    }

</style>

</div>