<?php 

    $this->headTitle($this->translate('Settings'));
    
    /*
    $this->headLink()->appendStylesheet($this->basePath('/css/Core/forms.css'));
    
    $this->headScript()->appendFile($this->basePath('js/jquery.inlineLabel.js'))
                       ->appendFile($this->basepath('js/Applications/form.js'));
    
    */
?>
<h1><?php echo $this->translate('Settings')?></h1>

<div id="settings-form-response" class="alert hide"></div>
<?php

/*
$form->setAttributes(array(
    'action' => $this->url('lang/settings', array(), true),
    'method' => 'post',
    'id' => 'application-form',
));
 */

echo $this->form($form, 'settings');

?>