<?php
/**
 * YAWIK
 *
 * @filesource
 * @copyright (c) 2013 - 2016 Cross Solution (http://cross-solution.de)
 * @license   MIT
 * @author Mathias Gelhausen <gelhausen@cross-solution.de>
 */

?>
<h1><?php echo $this->translate('job opening is not online anymore') ?></h1>

<p><?php echo $this->translate('you tried to open an application formular for a job opening, which is not online any more.') ?></p>

