<?php
/**
 * YAWIK
 *
 * @filesource
 * @copyright (c) 2013-2014 Cross Solution (http://cross-solution.de)
 * @license   MIT
 * @author Mathias Gelhausen <gelhausen@cross-solution.de>
 */
?>
<h1><?php echo $this->translate('A 410 error occured') ?></h1>

<h2><?php echo $this->translate('Unknown application identifier') ?>.</h2>
<p><?php echo $this->translate('An application with the provided identifier could not be found.') ?></p>
