<?php
$from = 'cross@cross-solution.de';
$fromName = 'cross-solution';
$subject = 'registration at the Cross Applicant Management';
?>
Hallo,

Anbei übersenden wir Ihnen Ihre Zugangsdaten zu Ihrem Bewerbermanagement.

Ihr Benutzername lautet: <?php echo $Anrede ?>,

Ihr Passwort lautet: <?php echo $password ?>,

Loggen Sie sich hier ein: <?php echo $uri ?>


Mit freundlichen Grüßen
Cross-Solution, Open-Source