<?php
/**
 * YAWIK
 *
 * @filesource
 * @copyright (c) 2013-2015 Cross Solution (http://cross-solution.de)
 * @license   MIT
 */

$this->headScript()->appendFile($this->basePath('Geo/js/jquery.geolocationfield.js'));
$this->headScript()->appendFile($this->basePath('Geo/js/typeahead.jquery.min.js'));
$this->headScript()->appendFile($this->basePath('Geo/js/bloodhound.min.js'));

$value = $this->element->getValue();
$label = $this->element->getLabel();
$name  = "job[location]";

if ($this->element->hasAttribute('name')) {
    $name  = $this->element->getAttribute('name');
}
?>
<?php if ($this->renderSummary): ?>
    <div class="row">
        <div class="col-md-3 yk-label"><label><?php echo $this->translate($this->element->getLabel()) ?></label></div>
        <div class="col-md-9"><?php echo $this->element->getValue() ?></div>
    </div>
    <?php return; endif;
$this->headScript()->appendScript('var plugin="' . $this->element->getOption('geoPlugin','photon') . '";');
?>



<label class="sr-only"
       for="<?php echo $this->element->getAttribute('id') ?>"><?php echo $this->translate($this->element->getLabel()) ?>
</label>
<input type="text" value="<?php echo $value; ?>" placeholder="<?php echo $this->translate('Type in a location')?>" class="form-control geolocation" id="job-location" name="<?php echo $name; ?>" data-provide="typeahead" >
<?php
/**
 * @todo move the hidden filed to the GeoTextFormFactory.
 */
?>
<input type="hidden" name="<?php echo $name; ?>[coordinates]" value="<?php echo $this->params('l')?>"  id="<?php echo $this->element->getAttribute('id') ?>coordinates" >