<?php
/**
 * YAWIK
 *
 * @filesource
 * @copyright (c) 2013 - 2016 Cross Solution (http://cross-solution.de)
 * @license   MIT
 */


$sm = $this->getHelperPluginManager()->getServiceLocator();
/* @var \Geo\Options\ModuleOptions $options */
$options = $sm->get('Geo/Options');
$plugin = $options->getPlugin();

if ('photon' == $plugin) {
    $this->headScript()->appendFile($this->basePath('Geo/js/jquery.geolocationfield.photon.js'));
}else{
    $this->headScript()->appendFile($this->basePath('Geo/js/jquery.geolocationfield.geo.js'));
}
$this->headScript()->appendFile($this->basePath('Geo/js/typeahead.jquery.min.js'));
$this->headScript()->appendFile($this->basePath('Geo/js/bloodhound.min.js'));

$value = $this->element->getValue();
$label = $this->element->getLabel();
$name  = "job[location]";

if ($this->element->hasAttribute('name')) {
    $name  = $this->element->getAttribute('name');
}
$id = $this->element->getAttribute('id');
if (!$id) {
    $id = str_replace(array('[', ']'), array('-', ''), $name);
}
?>
<?php if ($this->renderSummary): ?>
    <div class="row">
        <div class="col-md-3 yk-label"><label><?php echo $this->translate($this->element->getLabel()) ?></label></div>
        <div class="col-md-9"><?php echo $this->element->getValue() ?></div>
    </div>
    <?php return; endif;

$this->headScript()->appendScript('var plugin="' . ($plugin ?: 'photon') . '";');
$nameElement = $this->element->getNameElement();
$dataElement = $this->element->getDataElement();
?>



<label class="sr-only"
       for="<?php echo $nameElement->getAttribute('id') ?>"><?php echo $this->translate($this->element->getLabel()) ?>
</label>
<?php

$nameElement->setAttribute("placeholder",$this->translate('Type in a location'));

echo $this->formText($nameElement)

?>
<?php
/**
 * @todo move the hidden filed to the GeoTextFormFactory.
 */
?>
<?php
echo $this->formHidden($dataElement);
echo $this->formHidden($this->element->getTypeElement());