<?php 
/**
 * Cross Applicant Management
 * Layout template file
 * 
 * @copyright (c) 2013 Cross Solution (http://cross-solution.de)
 * @license   GPLv3
 */
?>

<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Cross Applicant Management'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
        
        <?php //echo $this->jquery() ?>
        <?php echo $this->headScript()
                        ->prependFile($this->basepath('js/Core/core.js'))
                        ->prependFile($this->basePath('js/jquery-ui-1.10.2.custom.js'))
                        ->prependFile($this->basePath('js/jquery-1.9.1.js')); ?>
                        
        <?php echo $this->headLink()->prependStylesheet($this->basePath('css/Applications/layout.css'))
                                    ->prependStylesheet($this->basePath() . '/css/Core/layout.css')
                                    ->prependStylesheet($this->basePath('css/smoothness/jquery-ui-1.10.2.custom.min.css')) ?>
                                    
        
        
        <?php echo $this->headStyle() ?>

    </head>
    <body>
        <div id="main">
            <header>
                <h1><?php echo $this->translate('Cross Applicant Management')?> - <?php echo $this->translate('Apply') ?></h1>
                <?php //echo $this->loginInfo ?>
                
                <div class="clear"></div>
            </header>
            <div id="container">
                <?php echo $this->content; ?>

            </div> <!-- /container -->

            <footer>
                <p class="float-left">&copy; 2013 <a href="http://cross-solution.de">Cross Solution</a>. <?php echo $this->translate('All rights reserved.') ?></p>
                <p class="float-right">
                    Powered by <a href="http://framework.zend.com">Zend Framework 2</a>,
                                <a href="http://jquery.com">jQuery</a>,
                                <a href="http://jqueryui.com">jQuery UI</a></p>
                <div class="clear"></div>
            </footer>
        </div> <!-- /main -->
    </body>
</html>
