<?php $contact = $application->contact; $job = $application->job; ?>
<?php $this->setSubject('Ihre Bewerbung vom ' . strftime('%x', $application->dateCreated->getTimestamp()))?>
Sehr geehrte<?php echo 'male' == $contact->gender ? 'r Herr' : ' Frau' ?> <?php echo $contact->firstname . ' ' . $contact->lastName ?>,

Danke für Ihr Interesse an unserem Unternehmen.
Ihre Bewerbung auf unsere freie Stelle
"<?php echo $job->title ?>"
ist bei uns eingegangen und wird umgehend bearbeitet.

Freundliche Grüße,
...

