<?php $contact = $application->contact; $job = $application->job; ?>
<?php $this->setSubject('Ihre Bewerbung vom ' . strftime('%x', $application->dateCreated->getTimestamp()))?>
Sehr geehrte<?php echo 'male' == $contact->gender ? 'r Herr' : 'Frau' ?> <?php echo $contact->firstname . ' ' . $contact->lastName ?>,

Danke für Ihr Interesse an unserem Unternehmen und Ihre Bewerbung auf unsere freie Stelle
"<?php echo $job->title ?>".

Leider haben wir die Stelle zwischenzeitlich schon besetzt.
Ich wünsche Ihnen viel Erfolg bei Ihrer weiteren Suche.


Freundliche Grüße,
...

