<?php
/**
 * YAWIK
 *
 * @filesource
 * @copyright (c) 2013-2015 Cross Solution (http://cross-solution.de)
 * @author bleek@cross-solution.de
 * @license   MIT
 */
 /*
  * Confirmation Mail to the Customer
  */
?>
<p>Sehr geehrte/-r Herr/Frau  <?php echo $this->userName ?>,</p>

<p>
    hiermit bestätigen wir Ihnen den Eingang Ihrer Stellenanzeige mit der Referenz <?php echo $this->ref ?>.
    Sie erhalten von uns eine Nachricht, sobald die Anzeige von uns freigegeben
    und veröffentlicht wurde. Den aktuellen Status können Sie jederzeit in Ihrem Account einsehen.
</p>

<p>Mit freundlichen Grüßen,</p>

<p>ihr <?php echo $this->siteName ?> Team</p>

<?php echo $this->partial('mail/footer'); ?>