<b>Bestätigung:</b><br /><br />
Sehr geehrte/-r Herr/Frau  <?php echo $this->userName ?>,<br />
wir danken Ihnen für den Auftrag <?php echo $this->ref ?>. Sie erhalten von uns eine Nachricht, sobald die Anzeige von uns freigegeben und veröffentlicht wurde.<br />
<br />
Mit freundlichen Grüßen<br />
<?php echo $this->siteName ?> Verwaltungsgesellschaft mbH
Vertrieb<br />

<?php
echo $this->partial('mail/footer');
?>