<?php
/**
 * YAWIK
 *
 * @filesource
 * @copyright https://yawik.org/COPYRIGHT.php
 * @author bleek@cross-solution.de
 * @license   MIT
 */
 /*
  * Confirmation Mail to the Customer
  */
$job = $this->job; /* @var \Jobs\Entity\Job $job */
$user = $job->getUser();
$info = $user->getInfo();
?>
<?php echo $this->partial('mail/header'); ?>
<p><?php echo 'male' == $info->getGender()
         ? 'Sehr geehrter Herr'
         : 'Sehr geehrte Frau' ?>
    <?=$info->getDisplayName(/*emailIfEmpty*/ false); ?>,</p>

<p>
    hiermit bestätigen wir Ihnen den Eingang Ihrer Stellenanzeige <b><?=$job->getTitle() ?></b> mit der
    Referenz <b><?=$job->getReference() ?></b>. Sie erhalten von uns eine Nachricht, sobald die Anzeige von
    freigegeben und veröffentlicht wurde.
</p>
<p>
    Den aktuellen Status können Sie in der <a href="<?php echo $this->serverUrl() . $this->url('lang/jobs', array('lang' => 'de'))?>">Job-Übersicht</a> verfolgen.
</p>

<?php echo $this->partial('mail/footer'); ?>