<?php
/**
 * YAWIK
 *
 * @filesource
 * @copyright (c) 2013-2015 Cross Solution (http://cross-solution.de)
 * @author bleek@cross-solution.de
 * @license   MIT
 */
/*
 * Information Mail to the Approval Team
 */
?>
<?php
$sm = $this->getHelperPluginManager()->getServiceLocator();
$channels = $sm->get('Jobs/Options/Provider');
$options = $sm->get('Core/Options');
$defaultCurrencyCode = $options->defaultCurrencyCode;
$defaultTaxRate = $options->defaultTaxRate;
?>
<h2><?php echo $this->translate("Job details")?></h2>
<table>
    <tr>
        <td><?php echo $this->translate("Title of the job")?></td>
        <td><?php echo $this->job->title ?></td>
    </tr>
    <tr>
        <td><?php echo $this->translate("Location")?></td>
        <td><?php echo $this->job->location ?></td>
    </tr>
    <tr>
        <td><?php echo $this->translate("Companyname")?></td>
        <td><?php echo $this->job->company ?></td>
    </tr>
</table>

<h2><?php echo $this->translate("Publisher details")?></h2>

<table>
    <tr>
        <td><?php echo $this->translate("Name")?></td>
        <td><?php echo $this->job->user->info->displayName ?></td>
    </tr>
    <tr>
        <td><?php echo $this->translate("Email")?></td>
        <td><?php echo $this->job->user->info->email ?></td>
    </tr>
</table>


<?php
/**
 * following Variables are accessible
 * - template string
 * - job JobEntity
 */
?>

<?php
$sum = 0; $total = 0;

?>

<?php if (empty($this->job->portals)) : ?>
    <?php echo $this->translate('no Portal chosen') ?>
<?php else: $c = count($this->job->portals); ?>
    <h2><?php echo $this->translate("Selected Channels") ?></h2>
    <p>
        <?php foreach ($this->job->portals as $portalName): ?>

                <?php $channelData=$channels->getChannel($portalName); ?>
                <?php echo $channelData->label ?>,


                <?php $sum += (int) $channelData->price;
                        if (1 < $c && $sum < $channelData->minPrice && $total < $channelData->minPrice):
                                $total = $channelData->minPrice;
                        endif;
                    $total = $sum > $total ? $sum : $total;?>

        <?php endforeach; ?>
    <table>
        <tr>
            <td><?php echo $this->translate("Price")?>:</td>
            <td><?php echo $this->currencyFormat((round($total,2)), $defaultCurrencyCode) ?></td>
        </tr>
        <tr>
            <td><?php echo $this->translate("plus VAT")?> (<?php echo $defaultTaxRate?>%)</td>
            <td><?php echo $this->currencyFormat((round($total * $defaultTaxRate/100,2)), $defaultCurrencyCode) ?></td>
        </tr>
        <tr>
            <td><?php echo $this->translate("Invoice amount")?>:</td>
            <td><?php echo $this->currencyFormat((round(($total * $defaultTaxRate/100)+$sum,2)), $defaultCurrencyCode) ?></td>
        </tr>
    </table>
<?php endif; ?>

<a href="<?php echo $this->serverUrl() . $this->url('lang/jobs/approval', array(), true)?>?id=<?php echo $this->job->getId()?>"><?php echo $this->translate("Click here to accept or reject the job opening")?></a>


<?php echo $this->partial('mail/footer'); ?>