<html>
<h1><?php echo $this->job->title ?></h1>
Following portals are chosen:<br /><br />
<?php
/**
 * following Variables are accessable
 * - template string
 * - job JobEntity
 */

if (empty($this->job->portals)) {
    // you can use all ViewHelper in the template
    echo $this->translate('no Portal chosen');
}
else {
    foreach ($this->job->portals as $portalName => $portal) {
        if (!empty($portal['active'])) {
            echo $portal['name'] . '<br />';
        }

    }
}

?>
</html>