<?php
/**
 * YAWIK
 *
 * Template for the "Please create your organization first" page.
 *
 * @filesource
 * @license MIT
 * @copyright  2013 - 2015 Cross Solution <http://cross-solution.de>
 *
 * @author Mathias Gelhausen <gelhausen@cross-solution.de>
 */

$job=$this->job; /* @var \Jobs\Entity\Job $job */
?>

<h1><?=$this->translate('The job, you where looking for has expired or was inactivated'); ?></h1>

<ul>
    <li>
        <?=$this->translate("Title");?>: <?=$job->getTitle()?>
    </li>
    <li>
        <?=$this->translate("Company");?>:
        <a href="<?=$this->url('lang/admin/jobs', ['action' => 'edit'], ['query' => [ 'id' => $job->getId()]], true)?>">
            <?=$job->getCompany()?>
        </a>
    </li>
</ul>

