<?php
/**
 * YAWIK
 *
 * @filesource
 * @license MIT
 * @copyright  2013 - 2015 Cross Solution <http://cross-solution.de>
 */
?>
<?php
$sm = $this->getHelperPluginManager()->getServiceLocator();
$channels = $sm->get('Jobs/Options/Provider');
?>
<h3><?php echo $this->translate("Preview of the posting"); ?></h3>
<div class="row">
    <div class="col-md-8">
        <div class="panel panel-default">
            <div class="panel-body">
<?php if (!isset($this->diffSnapshot)): ?>
                <iframe style="width:100%; height:800px;" src="<?php echo $this->viewLink ?>"></iframe>

<?php  else:
    if (empty($this->diffSnapshot)) {
        echo $this->translate('Nothing has changed');
    }
    else {
       foreach(
            array('title' => 'title', 'location' => 'location', 'organization' => 'organization',
                'templateValues.qualifications' => 'templates qualifications', 'templateValues.requirements' => 'templateValues requirements',
                'templateValues.benefits' => '', 'templateValues.title' => '',
                'templateValues._freeValues.description'  => '' ) as $diffKey => $title) {
           if (array_key_exists($diffKey, $this->diffSnapshot)) {
               echo '<h3>' . $this->translate($title) . '</h3>' . PHP_EOL;
               echo '<div class="row">' . PHP_EOL;
               echo '<div class="col-md-6">' . $this->translate('previous content') . '</div>';
               echo '<div class="col-md-6">' . $this->translate('new content') . '</div>';
               echo '</div>' . PHP_EOL . PHP_EOL;
               echo '<div class="row">' . PHP_EOL;
               echo '<div class="col-md-6">' . $this->diffSnapshot[$diffKey][1] . '</div>';
               echo '<div class="col-md-6">' . $this->diffSnapshot[$diffKey][0] . '</div>';
               echo '</div>' . PHP_EOL . PHP_EOL;
           }
       }
    }
endif;
?>

            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="alert alert-info">
<?php if (!isset($this->diffSnapshot)): ?>
            <?php if ($this->job->portals):?>
            <h3><?php echo $this->translate('Summary') ?></h3>
            <?php $total=0 ?>
            <table class="table table-bordered">
                <tr>
                    <th><?php echo $this->translate('Channel')?></th>
                    <th class="text-right"><?php echo $this->translate('Price')?></th>
                </tr>
                <?php foreach($this->job->portals as $channel):?>
                    <?php if($channel):?>
                        <?php $channelData=$channels->getChannel($channel); ?>
                        <tr>
                            <td><?php echo $channelData->label ?></td>
                            <td class="text-right"><?php echo $this->currencyFormat($channelData->price, 'EUR') ?></td>
                        </tr>
                        <?php $total += (int) $channelData->price; ?>
                    <?php endif;?>
                <?php endforeach;?>
                <tr>
                    <td><strong><?php echo $this->translate("Total")?></strong></td>
                    <td class="text-right"><strong><?php echo $this->currencyFormat($total, 'EUR') ?></strong></span></td>
                </tr>
            </table>

            <?php endif; // $this->job->portals ?>
<?php  else: ?>
                <h3 id="history-box-label">
                    <?php echo $this->translate('State history') ?>:
                </h3>
                <table class="table table-striped table-bordered table-hover">
                    <thead>
                    <tr>
                        <th><?php echo $this->translate('Date') ?></th>
                        <th><?php echo $this->translate('State') ?></th>
                        <th><?php echo $this->translate('Comment') ?></th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($this->job->history as $history): ?>
                        <tr>
                            <td><?php echo $this->dateFormat($history->date) ?></td>
                            <td><?php echo $this->translate($history->status) ?></td>
                            <td><?php echo $history->message ?></td>
                        </tr>
                    <?php endforeach ?>
                    </tbody>
                </table>

<?php endif; ?>
            <a class="btn btn-warning" href="<?php echo $this->declineLink ?>"><?php echo $this->translate("Reject Job")?></a>
            <a class="btn btn-success" href="<?php echo $this->approvalLink ?>"><?php echo $this->translate("Accept Job")?></a>
        </div>
    </div>
</div>