<?php
/**
 * YAWIK
 *
 * @filesource
 * @license MIT
 * @copyright  2013 - 2015 Cross Solution <http://cross-solution.de>
 */
?>
<?php
$sm = $this->getHelperPluginManager()->getServiceLocator();
$channels = $sm->get('Jobs/Options/Provider');
?>
<h3><?php echo $this->translate("Preview of the posting"); ?></h3>
<div class="row">
    <div class="col-md-8">
        <?php
            echo $this->partial('jobs/snapshot_or_preview', $this->vars());
        ?>

    </div>
    <div class="col-md-4">
        <div class="alert alert-info">
<?php if (!isset($this->diffSnapshot)): ?>
    <?php
        echo $this->partial('jobs/portalsummary', $this->vars());
    ?>
<?php  else: ?>
    <?php
        echo $this->partial('jobs/history', $this->vars());
    ?>
<?php endif; ?>
            <a class="btn btn-warning" href="<?php echo $this->declineLink ?>"><?php echo $this->translate("Reject Job")?></a>
            <a class="btn btn-success" href="<?php echo $this->approvalLink ?>"><?php echo $this->translate("Accept Job")?></a>
        </div>
    </div>
</div>