<?php
/**
 * YAWIK
 *
 * @filesource
 * @copyright (c) 2013 - 2016 Cross Solution (http://cross-solution.de)
 * @license   MIT
 */
/**
 * renders the form for entering a job opening
 *
 * NOTE: price for jobsintown is currently hardcoded. This will be replaced by
 * a dynamic solution as soon there is a Channels module available
 *
 */

$options = $this->services('Core/Options');
$defaultCurrencyCode = $options->defaultCurrencyCode;
$defaultTaxRate = $options->defaultTaxRate;


$sm = $this->getHelperPluginManager()->getServiceLocator();
$channels = $sm->get('Jobs/Options/Provider');

$this->headscript()->appendFile($this->basepath('Core/js/core.forms.js'));
$this->headscript()->appendFile($this->basepath('Core/js/jquery.summary-form.js'));

$total=0;
$sum=0;

?>
<h1>
    <?php
    if ('new' == $this->action):
        echo $this->translate('Publish a job');
    else:
        echo sprintf($this->translate($this->isDraft?'Create a job':'Edit the job %s'),'<i>'.$this->title.'</i>');
    endif;
    ?>
</h1>

<?php
if ($job->isDraft() || $job->isRejected()) {
    $finishLabel = sprintf($this->translate('Publish job %s'),$total?$this->translate('chargeable'):'');

} else if ($job->isActive()) {
    $finishLabel = 'submit changes';
}


echo $this->formWizardContainer(
                $this->form,'form-horizontal',
                [ 'wizard' => [
                    'finish_label' => $finishLabel,
                    'finish_href' => $this->completionLink,
                    'finish_enabled' => $this->jobvalid,
                ]]
); ?>



        <?php if ($job->isDraft()):?>
            <div id="job_incomplete" class="alert alert-warning " <?php echo (isset($this->jobvalid) && $this->jobvalid == true) ? 'style = "display: none;"' : ''; ?>>
                <?php echo $this->translate('Your job position is incomplete.'); ?>
                <span id="job_errormessages">
                    <?php echo (isset($this->jobvalid) && $this->jobvalid == false && !empty($this->errorMessage)) ? ($this->errorMessage) : '';?>
                </span>
            </div>
	<?php
        /**
         * if job is active, a user can inactivate the job or publish changes
         */
        ?>
        <?php elseif ($job->status == 'active'):?>
            <div class="alert alert-info">
                <?php echo $this->translate('Your job opening is online. You can publish minor changes or you can deactivate the job opening'); ?>
            </div>
	<?php
        /**
         * if job was created and is waiting for approval
         */
        ?>
        <?php elseif ($job->status == 'created'):?>
            <div class="alert alert-info">
                <?php echo $this->translate('Your job opening was successfully created and is waiting for approval.'); ?>
            </div>
	<?php
        /**
         * if is inactive
         */
        ?>
        <?php elseif ($job->status == 'inactive'):?>
            <div class="alert alert-info">
                <?php echo $this->translate('Your job opening is inactive. You can reactivate it. Chargeable channels are not updated.'); ?>
            </div>
	<?php
        /**
         * if is expired
         */
        ?>
        <?php elseif ($job->status == 'expired'):?>
            <div class="alert alert-info">
                <?php echo $this->translate('Your job was expired. You can reactivate you job opening. Chargeable channels are not updated.'); ?>
            </div>
	<?php
        /**
         * if job was rejected
         */
        ?>
        <?php elseif ($job->status == 'rejected'):?>
            <div class="alert alert-warning">
                <?php echo $this->translate('Your job opening was rejected. Please correct the errors and republish it'); ?>
            </div>
        <?php endif?>
        <?php
              /*  echo '<a href="' . $this->pageLinkPrevious . '" class="btn btn-primary">' . $this->translate('Back') . '</a>' . PHP_EOL;
                if ($this->job->isDraft()) {
                    echo '<a id="finalize_jobentry" style="' . ($this->jobvalid?'':'display:none;') . '" href="' . $this->completionLink . '" class="btn btn-primary">' .
                        sprintf($this->translate('Publish job %s'),$total?$this->translate('chargeable'):'') . '</a>' . PHP_EOL;
                } elseif ($this->job->isActive()) {
                    echo '<a id="finalize_jobentry" style="' . ($this->jobvalid?'':'display:none;') . '" href="' . $this->completionLink . '" class="btn btn-primary">' .
                        $this->translate('submit changes') . '</a>' . PHP_EOL;
                    $deactivateLink = $this->url(
                                           'lang/jobs/deactivate',
                                               array(
                                               ),
                                               array(
                                                   'query' => array(
                                                       'id' => $this->job->id
                                                   )
                                               )
                    );
                    echo '<a href="' . $deactivateLink . '" class="btn btn-primary">' . $this->translate('Deactivate') . '</a>' . PHP_EOL;
                }
                else {
                }*/
?>