<?php
/**
 * YAWIK
 *
 * @filesource
 * @copyright (c) 2013 - 2016 Cross Solution (http://cross-solution.de)
 * @license   MIT
 */
?>


<div class="modal-content">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h4 class="modal-title"><?php echo $this->translate('History') . ' ' . $this->title ?></h4>
    </div>
    <div class="modal-body">
        <table class="table table-striped table-bordered table-hover">
            <tr><th><?php echo $this->translate('Date'); ?></th><th><?php echo $this->translate('Comment'); ?></th></tr>
<?php foreach ($this->history as $historyItem): /* @var Jobs\Entity\HistoryInterface $historyItem */?>
            <tr><td><?php echo $this->dateFormat($historyItem->getDate()); ?></td><td><?php echo $historyItem->getMessage(); ?></td></tr>
<?php endforeach; ?>
        </table>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    </div>
</div>