<tr id="info-bar-<?php echo $model->id?>" class="applications-list-row <?php echo $this->partialLoop()->getPartialCounter() % 2 ? 'odd' : 'even' ?>">
    <td><?php echo $model->jobId ?></td>
    <td><a href="<?php echo $this->url('main/applications/detail', array('id' => $model->id))?>"><?php echo $model->name ?></a></td>
    <td><?php echo $model->email ?></td>
    <td>Neu</td>
    <td title="Created: <?php echo $model->createdDate('%x %X');?>">
        <?php echo $model->modifiedDate('%x %X');?>
    </td>
</tr>
<tr id="action-bar-<?php echo $model->id ?>" class="action-bar">
    <td colspan="5">
        <div class="action-bar-wrapper hidden">
        <?php /*<div class="action-bar-loader">
            <img src="<?php echo $this->basepath('/images/loader.gif') ?>" alt="Loading..." />
        </div> */?>
        <div class="action-bar-content">
            <div class="applicant-info">
                <p><?php echo $this->translate(ucfirst($model->title))?> <?php echo $model->name ?></p>
                <p><?php echo $model->street?> <?php echo $model->houseNumber?><br />
                   <?php echo $model->zipCode?> <?php echo $model->location?></p>
                <p>
                    <a href="mailto:<?php echo $model->email?>"><?php echo $model->email?></a><br />
                    <?php echo $model->phoneNumber?><br />
                    <?php echo $model->mobileNumber?></p>
                     
            </div> <!--  /.applicant-info -->
            
            <div class="application-actions">
                <div class="application-actions-status">
                <?php foreach(array('new', 'review', 'approved') as $idx => $status): 
                    $id = $model->id . '-' .$status; ?>
                    <label for="aa-status-<?php echo $id?>"><?=$this->translate(ucfirst($status))?></label>
                    <input type="radio" id="aa-status-<?php echo $id?>" name="status-<?php echo $model->id?>" value="<?php echo $status?>"<?php echo 0 == $idx ? ' checked="checked"' : '' ?> />
                <?php endforeach ?>
                    
                </div>
            </div>
        
        </div> <!--  /.action-bar-content -->
        </div> <!-- /.action-bar-wrapper -->
    </td>
</tr>
