
<tr id="info-bar-<?php echo $model->id?>" class="applications-list-row <?php echo $this->partialLoop()->getPartialCounter() % 2 ? 'odd' : 'even' ?>">
    <td><?php echo $model->jobId ?></td>
    
    <td><?php echo $model->status ?></td>
    <td title="Created: <?php echo strftime('%x %X', $model->dateCreated->getTimestamp());?>">
        <?php echo strftime('%x %X', $model->dateModified->getTimestamp());?>
    </td>
</tr>
