
<?php if ($this->pageCount): 
$query = $this->params()->fromQuery();
?>
<div class="row" id="cam-pagination">
<div class="col-md-6">
<!-- First page link -->
<ul class="pagination">
<?php if (isset($this->previous)): ?>
  <li><a href="<?php $query['page'] = $this->first; echo $this->url($this->route, array('lang' => $this->lang), array('query'=>$query), true); ?>">
    <?= $this->translate('First')?>
  </a></li>
<?php else: ?>
  <li class="disabled"><a><?= $this->translate('First');?></a></li>
<?php endif; ?>
<!-- Previous page link -->
<?php if (isset($this->previous)): ?>
  <li><a href="<?php $query['page'] = $this->previous; echo $this->url($this->route, array('lang' => $this->lang), array('query'=>$query), true); ?>">
    <?= $this->translate('&lt; Previous')?>
  </a></li>
<?php else: ?>
  <li class="disabled"><a><?= $this->translate('&lt; Previous')?></a></li>
<?php endif; ?>
<!-- Next page link -->
<?php if (isset($this->next)): $query['page'] = $this->next; ?>
  <li><a href="<?php echo $this->url($this->route, array('lang' => $this->lang), array('query'=>$query), true); ?>">
    <?= $this->translate('Next &gt;')?>
  </a></li>
<?php else: ?>
  <li class="disabled"><a>Next &gt;</a></li>
<?php endif; ?>
<!-- Last page link -->
<?php if (isset($this->next)): $query['page'] = $this->last; ?>
  <li><a href="<?php echo $this->url($this->route, array('lang' => $this->lang), array('query'=>$query), true); ?>">
    <?= $this->translate('Last')?>
  </a></li>
<?php else: ?>
  <li class="disabled"><a><?= $this->translate('Last')?></a></li>
<?php endif; ?>
</ul>
</div>
<div class="col-md-6 text-right">
<?php echo $this->firstItemNumber; ?> - <?php echo $this->lastItemNumber; ?>
 of <?php echo $this->totalItemCount; ?>
</div>
</div>
<?php endif; ?>
