<?php
/**
 * YAWIK
 *
 * @filesource
 * @copyright (c) 2013-2014 Cross Solution (http://cross-solution.de)
 * @license   MIT
 */

$this->headTitle($this->translate('Apply'));
$job = $this->application->job;

// @TODO own viewhelper
// does serverUrl do the right thing ? basePath und url don't
function getImageRef($url, $self) {
    if (preg_match('/^https?:\/\//',$url)) {
        // pass
    }
    else {
        $url = '/' . ltrim($url, '/');
        $url = $self->serverUrl($url);
    }
    return $url;
}

?>
<h1><?php echo $this->translate('Application')?></h1>
<div class="container">
    <div class="row">
    <div class="col-md-8">
<p class="lead"><?php printf(
    $this->translate('Apply to "%s" from "%s"'), 
    '<a href="'.$job->link.'" title="' . $this->translate('click to open the job ad') . '">' . $this->escapehtml(strip_tags($job->title)) . '</a>',
    $job->company
) ?></p>
    </div>
        <div class="col-md-4">
            <img src="<?php echo getImageRef($this->application->job->logoRef, $this) ?>">
        </div>
    </div>


<?php if ($this->success):
    /*
     * Application was successfully completed. 
     */

?>
<div class="alert alert-success">
    <p><?php echo $this->translate('your application was sent successfully') ?></p> 
</div>
<div class="alert alert-info">
    <?php if ($this->auth()->isLoggedIn()):?>
    <p>
        <?php echo sprintf(
            $this->translate('The application was added to your %slist%s, so you can keep up-to-date with the process.'),
            '<a class="alert-link" href="' . $this->url('lang/applications', array(), true) . '">',
            '</a>'
        )?>
    </p>
    <?php else: ?>
    <p>
        <?php echo $this->translate('Keep up-to-date with the process of your application by bookmarking this link:')?>
    </p>
    <p>
        <?php 
            $href = $this->url('lang/applications/detail', array('id' => $this->application->id), array('force_canonical' => true), true)
                  . '?token=' . $this->auth('token');
            
            echo $this->link($href, array('class' => 'alert-link'));
        ?>
    </p>
    <?php endif ?>
</div>
<?php 

else:

    /*
     * Display application form container and action buttons.
     */

echo $this->formContainer($form, Core\Form\View\Helper\Form::LAYOUT_HORIZONTAL);

echo $this->partial('applications/apply/_buttons', 
                    array('application' => $this->application)
);
?>
<?php endif ?>
</div>