<?php
/**
 * YAWIK
 *
 * @filesource
 * @copyright (c) 2013 - 2016 Cross Solution (http://cross-solution.de)
 * @license   MIT
 */

$title = $this->translate('One click apply');
$this->headTitle($title);
$job = $this->application->job;
?>
<h1><?=$title?></h1>
<div class="row">
    <div class="col-md-8">
        <p class="lead">
            <?php $href = $job->link ? $job->link : $this->url('lang/jobs/view', array(), array('query' => array('id' => $job->id)), true); ?>
            <?php printf($this->translate('Apply to "%s" from "%s"'),
                        '<a href="'.$href.'" title="' .
                                    $this->translate('click to open the job ad') . '">' .
                        $this->escapehtml(strip_tags($job->title)) . '</a>', $job->company ) ?>
        </p>
    </div>
    <div class="col-md-4">
        <?php if (!empty($this->application->job->logoRef)):?>
            <img src="<?php echo getImageRef($this->application->job->logoRef, $this) ?>">
        <?php endif;?>
    </div>
</div>
<h1><?=$this->translate('Choose your profile')?></h1>
<div class="row">
    <div class="col-md-6">
        <?php foreach ($this->networks as $network):?>
            <a href="<?=$this->url('lang/apply-one-click', ['applyId' => $job->getApplyId(), 'network' => $network])?>" class="btn-social btn-<?=$network?> btn-lg"><i class="fa fa-<?=$network?>"></i> <?=$network?></a>
        <?php endforeach;?>
    </div>
    <div class="col-md-6">
        <a href="<?=$this->url('lang/apply', ['applyId' => $job->getApplyId()])?>" class="btn btn-default btn-lg"> <?=$this->translate('I have no profile')?></a>
    </div>
</div>
