<?php
/**
 * YAWIK
 *
 * @filesource
 * @copyright (c) 2013 - 2016 Cross Solution (http://cross-solution.de)
 * @license   MIT
 */
/**
 * generates the list of organizations.
 */
?>
<?php
$columns = [
    /*@translate*/ 'Organization' => [],
    /*@translate*/ 'City' => [
            'class' => 'cam-job',
            'sort' => 'contact.city'
        ],
    /*@translate*/ 'Street' => [
            'sort' => 'contact.street'
        ],
];

if ('-' == $this->sort{0}) {
    $sortBy  = substr($this->sort, 1);
    $sortDir = false;
} else {
    $sortBy  = $this->sort;
    $sortDir = true;
}
?>
<table class="table table-striped table-bordered table-hover" id="cam-organization-list">
    <thead>
    <tr>
        <?php foreach ($columns as $label => $option):?>
            <th <?php echo isset($option['class'])?'class="'.$option['class'].'"':'';?>>
                <?php if (! isset($option['sort'])): echo $this->translate($label);
                else:
                    if ($option['sort'] == $sortBy):
                        $icon = '<span class="pull-right text-right yk-icon yk-icon-sort' . ($sortDir ? '-desc' : '-asc') . '"></span>';
                        $dir = !$sortDir;
                    else:
                        $dir = true;
                        $icon = '<span class="pull-right yk-icon yk-icon-sort"></span>';
                    endif;
                    $sortParam = array('sort' => ($dir ? '' : '-') . $option['sort']);
                    $url = $this->url(
                        'lang/organizations', array(),
                        array('query' => array_merge($this->params()->fromQuery(), $sortParam)),
                        true
                    );
                    ?>
                    <a href="<?php echo $url?>"><?php echo $this->translate($label).$icon?></a>
                <?php endif; ?>
            </th>
        <?php endforeach; ?>
    </tr>
    </thead>
<?php foreach ($this->organizations as $organization): /* @var $organization \Organizations\Entity\Organization */?>
 <tr>
  <td>
      <a href="<?php echo $this->url('lang/organizations/edit', array('id' => $organization->getId())); ?>">
    <?php
        $nameEntity = $organization->getOrganizationName();
        echo isset($nameEntity)?$nameEntity->getName():'**** DRAFT ****';
    ?>
      </a>
      <?php if ($organization->isHiringOrganization()): $parent = $organization->getParent(); ?>
          <br><small><?php echo sprintf(
                $this->translate('Hiring organization of <strong>%s</strong>'),
                '<a href="' . $this->url('lang/organizations/edit', array('id' => $parent->getId())) . '">' . $parent->getOrganizationName()->getName() . '</a>'
          );?></small>

        <?php endif ?>
  </td>
  <td>
      <?php echo $organization->getContact()->getPostalcode();?>
      <?php echo $organization->getContact()->getCity();?>
  </td>
  <td>
      <?php echo $organization->getContact()->getStreet();?>
      <?php echo $organization->getContact()->getHouseNumber();?>
  </td>
 </tr>
<?php endforeach?>
</table>
<?php echo $this->paginationControl($this->organizations, 'Sliding', 'pagination-control', array('lang' => $this->params('lang'), 'route' => 'lang/organizations'));?>