<?php
/**
 * YAWIK
 *
 * @filesource
 * @copyright (c) 2013 - 2016 Cross Solution (http://cross-solution.de)
 * @license   MIT
 */
/**
 * {{rtd: Renders the list of organizations}}
 */

$this->headScript()->appendFile($this->basepath('modules/Core/js/core.pagination-container.js'));
?>
<h1><?php echo $this->translate('Organizations')?></h1>
    <nav class="navbar yk-toolbar" >
        <?php echo $this->searchForm($this->form) ?>
    </nav>

    <div id="organizations-list-container" class="pagination-container" data-uri="<?php
    echo $this->url('lang/organizations', array(), array('query' => $this->params()->fromQuery()), true)?>">

        <div class="pagination-message alert alert-info">
            <?php echo $this->translate('No organization found matching your criteria.') ?>
        </div>

        <div class="pagination-content">
            <?php echo $this->render('organizations/index/index.ajax.phtml')?>
        </div>

    </div>