<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Install\Controller\Index'                     => __DIR__ . '/Controller/Index.php',
  'Install\Controller\Plugin\Prerequisites'      => __DIR__ . '/Controller/Plugin/Prerequisites.php',
  'Install\Controller\Plugin\YawikConfigCreator' => __DIR__ . '/Controller/Plugin/YawikConfigCreator.php',
  'Install\Form\Installation'                    => __DIR__ . '/Form/Installation.php',
  'Install\Listener\LanguageSetter'              => __DIR__ . '/Listener/LanguageSetter.php',
  'Install\Validator\MongoDbConnectionString'    => __DIR__ . '/Validator/MongoDbConnectionString.php',
);
