<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Install\Filter\DbNameExtractor'                              => __DIR__ . '/Filter/DbNameExtractor.php',
  'Install\Form\Installation'                                   => __DIR__ . '/Form/Installation.php',
  'Install\Controller\Index'                                    => __DIR__ . '/Controller/Index.php',
  'Install\Controller\Plugin\Prerequisites'                     => __DIR__ . '/Controller/Plugin/Prerequisites.php',
  'Install\Controller\Plugin\YawikConfigCreator'                => __DIR__ . '/Controller/Plugin/YawikConfigCreator.php',
  'Install\Controller\Plugin\UserCreator'                       => __DIR__ . '/Controller/Plugin/UserCreator.php',
  'Install\Listener\LanguageSetter'                             => __DIR__ . '/Listener/LanguageSetter.php',
  'Install\Validator\MongoDbConnection'                         => __DIR__ . '/Validator/MongoDbConnection.php',
  'Install\Validator\MongoDbConnectionString'                   => __DIR__ . '/Validator/MongoDbConnectionString.php',
  'Install\Factory\Controller\Plugin\UserCreatorFactory'        => __DIR__ . '/Factory/Controller/Plugin/UserCreatorFactory.php',
  'Install\Factory\Controller\Plugin\YawikConfigCreatorFactory' => __DIR__ . '/Factory/Controller/Plugin/YawikConfigCreatorFactory.php',
);
