<!DOCTYPE html>
<html>
<head>
    <title><?php echo $this->titleHead?></title>
    <?=$this->jsonLd($this->job)?>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1.0" />
    <meta property="og:url" content="<?= $this->uriJob;?>" />
    <meta property="og:type" content="article" />
    <meta property="og:title" content="<?= $this->headTitle; ?> - <?= $this->organizationName;?>" />
    <link rel="stylesheet" href="<?= $this->basePath("modules/Jobs/templates/classic/job.css")?>" type="text/css">
    <link href='//fonts.googleapis.com/css?family=Montserrat' rel='stylesheet' type='text/css'>
    <style>
        form > div:hover {
            background-color: #eee;
            -webkit-box-shadow: 0px 0px 9px 3px rgba(0,0,0,0.55);
            -moz-box-shadow: 0px 0px 9px 3px rgba(0,0,0,0.55);
            box-shadow: 0px 0px 9px 3px rgba(0,0,0,0.55);
            cursor: pointer;
        }
    </style>
</head>
<body>
<div class="container">

    <main>
        <!--

          This the *default* Template. Take a look at the sources:

          https://github.com/cross-solution/YAWIK/blob/develop/module/Jobs/public/templates/classic/index.phtml

          Or take a look at the docs
          :
          http://yawik.readthedocs.io/en/latest/modules/jobs/index.html#job-templates

        -->
        <p><?= $this->descriptionEditable ?></p>
        <div class="row">
            <div class="twelve columns">
                <?php echo $this->title; ?>
            </div>
        </div>
        <div class="row">
            <div class="one-half column">
                <div class="panel">
                    <div class="panel-heading"><h4><?= $this->translate($this->labelRequirements);?></h4></div>
                    <div class="panel-body"><?= $this->requirements;?></div>
                </div>
            </div>
            <div class="one-half column">
                <div class="panel">
                    <div class="panel-heading"><h4><?= $this->translate($this->labelQualifications);?></h4></div>
                    <div class="panel-body"><?= $this->qualifications;?></div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="twelve columns">
                <div class="panel">
                    <div class="panel-heading"><h4><?= $this->translate($this->labelBenefits);?></h4></div>
                    <div class="panel-body"><?= $this->benefits;?></div>
                </div>
            </div>
        </div>
        <?=$this->jobApplyButtons($this->applyData)?>
        <div class="row">

            <div class="one-half column">
                <div>
                    <img src="<?= $this->uriLogo?>">
                </div>
            </div>
            <div class="one-half column right">
                <address>
                    <strong><?= $this->organizationName?><br></strong>
                    <?= $this->street?><br>
                    <?= $this->postalCode?> <?= $this->city?><br><br>
                    <?= $this->phone?>
                </address>
            </div>
        </div>
    </main>
    <footer><small>powered by <a href="http://yawik.org">YAWIK</a></small></footer>
</div>
</body>
</html>
