<!DOCTYPE html>
<html>
<head>
    <title><?php echo $this->titleHead?></title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <link rel="stylesheet" href="<?php echo $this->basePath("/Jobs/templates/classic/job.css")?>" type="text/css">
    <link href='http://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet' type='text/css'>
    <style>
        form > div:hover {
            background-color: #eee;
            -webkit-box-shadow: 0px 0px 9px 3px rgba(0,0,0,0.55);
            -moz-box-shadow: 0px 0px 9px 3px rgba(0,0,0,0.55);
            box-shadow: 0px 0px 9px 3px rgba(0,0,0,0.55);
            cursor: pointer;
        }
    </style>
</head>
<body>
<div class="container">

    <main>
        <!--
          This the *classic* Template. Templates are quite easy to create. Take a look at the sources:
 
          https://github.com/cross-solution/YAWIK/blob/develop/module/Jobs/public/templates/classic/index.phtml
        -->
        <p><?php echo $this->descriptionEditable ?></p>
        <div class="row">
            <div class="twelve columns">
                <?php echo $this->title; ?>
            </div>
        </div>
        <div class="row">
            <div class="one-half column">
                <div class="panel">
                    <div class="panel-heading"><h4><?php echo $this->translate($this->labelRequirements);?></h4></div>
                    <div class="panel-body"><?php echo $this->requirements;?></div>
                </div>
            </div>
            <div class="one-half column">
                <div class="panel">
                    <div class="panel-heading"><h4><?php echo $this->translate($this->labelQualifications);?></h4></div>
                    <div class="panel-body"><?php echo $this->qualifications;?></div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="twelve columns">
                <div class="panel">
                    <div class="panel-heading"><h4><?php echo $this->translate($this->labelBenefits);?></h4></div>
                    <div class="panel-body"><?php echo $this->benefits;?></div>
                </div>
            </div>
        </div>
        <?php if ($this->applyButtons): ?>
        <div class="row">
            <div class="twelve columns">
                <div class="apply">
                    <?php foreach ($this->applyButtons as $applyButton):?>
                        <a target="_new" class="button button-primary apply-button-<?=$applyButton['type']?>" href="<?=$applyButton['url']?>" rel="nofollow">
                            <strong><?=$applyButton['label']?></strong>
                        </a>
                    <?php endforeach;?>
                </div>
            </div>
        </div>
        <?php endif; ?>
        <div class="row">

            <div class="one-half column">
                <div>
                    <img src="<?php echo $this->uriLogo?>">
                </div>
            </div>
            <div class="one-half column right">
                <address>
                    <strong><?php echo $this->organizationName?><br></strong>
                    <?php echo $this->street?><br>
                    <?php echo $this->postalCode?> <?php echo $this->city?><br><br>
                    <?php echo $this->phone?>
                </address>
            </div>
        </div>
    </main>
    <footer><small>powered by <a href="http://yawik.org">YAWIK</a></small></footer>
</div>
</body>
</html>
