<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" dir="ltr" lang="de-DE">
<head>
<title><?php echo $this->titleHead?></title>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<link rel="stylesheet" href="<?php echo $this->basePath("/Jobs/templates/classic/style.css")?>" type="text/css" media="screen">
<style>
form > div {
  border:1px solid rgb(84, 152, 215);
}
</style>
</head>
<body>
<div id="page">
 <div id="header">
  <div id="headerimg">
    <img src="<?php echo $this->basePath($this->uriLogo)?>" class="logo" border="0">
    <div class="description">This is a demo Template of a job opening</div>
  </div>
 </div>
<div id="content">
<p>
This is a <b>Classic</b> Template of a jobad. Templates are quite easy to create. Take a look at the <a target="_new" href="https://github.com/cross-solution/YAWIK/blob/develop/module/Jobs/public/templates/classic/index.phtml">sources</a>.
</p>
<p>Click below to enter the Jobtitle</p>
<p><?php echo $this->description ?></p>
<h1><?php echo $this->title; ?></h1>

<h4>Requirements:</h4>
<?php echo $this->requirements;?>
<h4>Qualifications:</h4>
<?php echo $this->qualifications;?>
<h4>Benefits:</h4>
<?php echo $this->benefits;?>

<h2><a target="_new" href="<?php echo $this->uriApply ?>"><strong>Zum Online Bewerbungsformular</strong></a></h2>

<address>
<strong><?php echo $this->organizationName?><br></strong>
<?php echo $this->street?><br>
<?php echo $this->zipcode?> <?php echo $this->city?><br><br>
<?php echo $this->phone?>
</address>
</div>
</div>
</body>
</html>