<?php
/**
 * YAWIK
 *
 * Template for the mail which is send, if an user has logged in the first time via an
 * external application.
 *
 * @filesource
 * @license MIT
 * @copyright  2013 - 2015 Cross Solution <http://cross-solution.de>
 */
?>
<div class="yk-mail">
<?= $this->partial('mail/header'); ?>
<p>Guten Tag,</p>

<p>
    Sie haben sich das erste Mal an "YAWIK Demo" <?= $this->application ? 'über "' . $this->application . '"' : 'über eine externe Applikation' ?>
    angemeldet.
</p>

<p>Damit Sie sich in Zukunft zusätzlich auch bequem direkt am System anmelden können, haben wir Ihnen dafür Zugangsdaten generiert:</p>

<p>
    <strong>Login:</strong> <?= $this->login ?><br>
    <strong>Password:</strong> <?= $this->password ?>
</p>

<p>
    Wir empfehlen Ihnen, nach dem ersten einloggen auf <a href="<?= $this->serverUrl() . $this->url('lang/auth', array('lang' => 'de'))?>">YAWIK Demo</a>
    das Passwort zu ändern. Dazu rufen Sie die Profil-Einstellungen über das Menü auf der rechten oberen Bildschirmseite auf und wählen den Punkt
    "Passwort ändern".
</p>

<?= $this->partial('mail/footer') ?>
</div>