<?php
/**
 * YAWIK
 *
 * Template for the mail which is send, if an user has logged in the first time via an
 * external application.
 *
 * @filesource
 * @license MIT
 * @copyright  2013 - 2015 Cross Solution <http://cross-solution.de>
 */
?>

<p>Guten Tag,</p>

<p>Sie haben sich das erste Mal an "YAWIK Demo" <?php echo
    $this->application ? 'über "' . $this->application . '"' : 'über eine externe Applikation' ?> angemeldet.</p>

<p>Damit Sie sich in Zukunft zusätzlich auch bequem direkt am System anmelden können, haben wir Ihnen dafür Zugangsdaten generiert:</p>

<p>
    <strong>Login:</strong> <?php echo $this->login ?><br>
    <strong>Password:</strong> <?php echo $this->password ?>
</p>

<p>
    Wir empfehlen Ihnen, nach dem ersten einloggen auf <a href="<?php echo $this->serverUrl() . $this->url('lang/auth', array('lang' => 'de'))?>">YAWIK Demo</a>
    das Passwort zu ändern. Dazu rufen Sie die Profil-Einstellungen über das Menü auf der rechten oberen Bildschirmseite auf und wählen den Punkt
    "Passwort ändern".
</p>

<?php echo $this->partial('mail/footer') ?>
