<?php
/**
 * YAWIK
 *
 * Template for the mail which is send, if an user has logged in the first time via a
 * social network (Facebook, LinkedIn, Xing)
 *
 * @filesource
 * @license MIT
 * @copyright  2013 - 2015 Cross Solution <http://cross-solution.de>
 */
?>
<div class="yk-mail">
<?= $this->partial('mail/header'); ?>
<p>Hello <?= $this->displayName?>,</p>

<p>welcome to the YAWIK demo. You've registered the first time via <?= $this->provider?>.</p>

<p>
    Login data were generated, so you can log into YAWIK directly. This should only show you that YAWIK can be used
    completely without social networks.
</p>

<p>
    We've set your role to a recruiter. So you can create jobs and manage applications.
    Changing the role is currently only possible directly on the mongo cli.
</p>


<p>Username: <?= $this->login ?><br>


Secret: <?= $this->password ?></p>


<p>
    Return to YAWIK and log in at:
    <a href="<?php $url = $this->serverUrl() . $this->url('lang/auth', array('lang' => 'en')); echo $url; ?>">
        <?= $url ?>
    </a>
</p>


<?= $this->partial('mail/footer'); ?>
</div>