<p>Hello <?php echo $this->displayName?>,</p>


<p>welcome to the YAWIK demo. You've registered the first time via <?php echo $this->provider?>.</p>


<p>Login data were generated, so you can log into YAWIK directly. This should only show you that YAWIK can be used completely
without social networks. Althought there are no registration forms yet.</p>

<p>We've set your role to a recruiter. So you can create jobs and manage applications. You can change your role in your profile.</p>


<p>Username: <?php echo $this->login ?><br>


Secret: <?php echo $this->password ?></p>


<p>Return to YAWIK and log in at: <?php echo $this->url(array('lang/auth'), array('lang' => 'de')) ?></p>


<p>regards,</p>

<?php
echo $this->partial('mail/footer');
?>