<?php
/**
 * YAWIK
 * Auth Module
 *
 * @copyright (c) 2013 - 2016 Cross Solution (http://cross-solution.de)
 * @license       MIT
 */
/*
 * Sends a mail to the user to reset the password.
 */
/* @var Auth\Entity\User $user */
$user = $this->user;
?>
<div class="yk-mail">
<?php echo $this->partial('mail/header', ['title' => 'reset password']); ?>
<p>
    Dear <?=$user->getInfo()->getLastName(); ?>,
</p>
<p>
    please click on the following Link to reset you password:
</p>

<p>
    <a href="<?= $this->resetlink; ?>"><?= $this->resetlink; ?></a>
</p>

<p>
    If you do not have requested for a new password, please just ignore this mail.
</p>

<?= $this->partial('mail/footer.en', array()); ?>
</div>