<?php
/**
 * YAWIK
 * Auth Module
 *
 * @copyright (c) 2013 - 2016 Cross Solution (http://cross-solution.de)
 * @license   MIT
 */
/*
 * Sends a mail to the user to reset the password.
 */
?>
<?php echo $this->partial('mail/header'); ?>
   <p> Guten Tag <?php echo $this->user->info->lastName; ?>,</p>
<p>
um ein neues Passwort für das Bewerbermanagement zu vergeben, klicken Sie bitte auf folgenden Link:
</p>
<p>
<a href="<?php echo $this->resetlink; ?>"><?php echo $this->resetlink; ?></a>
</p>
<p>
Sollten Sie kein neues Passwort angefordert haben, brauchen Sie nichts weiter zu tun.
<p>
Bitte informieren Sie uns aber, falls Sie Bedenken bezüglich der Sicherheit Ihres Passwortes haben.
</p>

<?php echo $this->partial('mail/footer',array()); ?>