<?php
/**
 * YAWIK
 * Auth Module
 *
 * @copyright (c) 2013 - 2016 Cross Solution (http://cross-solution.de)
 * @license   MIT
 */
/*
 * Sends a mail to the user to reset the password.
 */
/* @var Auth\Entity\User $user */
$user = $this->user;
?>
<div class="yk-mail">
<?= $this->partial('mail/header', ['title' => 'Kennwort zurücksenden']); ?>

<p> Guten Tag <?=$user->getInfo()->getLastName(); ?>,</p>
<p>
um ein neues Passwort für das Bewerbermanagement zu vergeben, klicken Sie bitte auf folgenden Link:
</p>
<p>
<a href="<?= $this->resetlink; ?>"><?= $this->resetlink; ?></a>
</p>
<p>
Sollten Sie kein neues Passwort angefordert haben, brauchen Sie nichts weiter zu tun.
<p>
Bitte informieren Sie uns aber, falls Sie Bedenken bezüglich der Sicherheit Ihres Passwortes haben.
</p>

<?= $this->partial('mail/footer',array()); ?>
</div>