Guten Tag <?php echo $this->user->info->lastName; ?>,<br />
<br />
um ein neues Passwort für das Bewerbermanagement zu vergeben, klicken Sie bitte auf folgenden Link:<br />
<br />
<a href="<?php echo $this->resetlink; ?>"><?php echo $this->resetlink; ?></a>
<br />
<br />
Sollten Sie kein neues Passwort angefordert haben, brauchen Sie nichts weiter zu tun.<br />
<br />
Bitte informieren Sie uns aber, falls Sie Bedenken bezüglich der Sicherheit Ihres Passwortes haben.<br />
<br />
Vielen Dank.<br />
<br />
<?php
    echo $this->partial('mail/footer',array());
?>