<?php
/**
 * YAWIK
 * Auth Module
 *
 * @copyright (c) 2013 - 2016 Cross Solution (http://cross-solution.de)
 * @license       MIT
 */
/*
 * Sends a mail to the user to reset the password.
 */
?>
<?php echo $this->partial('mail/header'); ?>
<p>
    Dear <?php echo $this->user->info->lastName; ?>,
</p>
<p>
    please click on the following Link to reset you password:
</p>

<p>
    <a href="<?php echo $this->resetlink; ?>"><?php echo $this->resetlink; ?></a>
</p>

<p>
    If you do not have requested for a new password, please just ignore this mail.
</p>

<?php echo $this->partial('mail/footer.en', array()); ?>