<?php
/**
 * YAWIK
 * Auth Module
 *
 * @copyright (c) 2013 - 2016 Cross Solution (http://cross-solution.de)
 * @license   MIT
 */
/*
 * Sends a confirmation link to the user, after registration
 */

$this->mail->setSubject('Ein neur Benutzer hat sich registriert.');
?>
<?php echo $this->partial('mail/header'); ?>

    <p>Ein neuer Benutzer hat sich registriert: <?=$this->user->getInfo()->getDisplayName(false) ?>
                              &lt;<?=$this->user->getInfo()->getEmail()?>&gt;</p>

    <p>Die Bestätigung der Registrierung ist noch nicht erfolgt.</p>

<?php echo $this->partial('mail/footer'); ?>
