<?php
/**
 * YAWIK
 * Auth Module
 *
 * @copyright (c) 2013 - 2016 Cross Solution (http://cross-solution.de)
 * @license   MIT
 */
/*
 *
 */

$this->mail->setSubject('Ein Benutzer wurde bestätigt.');
?>
<div class="yk-mail">
<?= $this->partial('mail/header'); ?>

    <p>Ein Benutzer hat seine Registrierung bestätigt: <?=$this->user->getInfo()->getDisplayName(false) ?>
                                  &lt;<?=$this->user->getInfo()->getEmail()?>&gt;</p>

    <p>Der Benutzeraccount ist jetzt vollständig registriert und aktiv.</p>

<?= $this->partial('mail/footer'); ?>
</div>