<?php
/**
 * YAWIK
 * Auth Module
 *
 * @copyright (c) 2013 - 2016 Cross Solution (http://cross-solution.de)
 * @license   MIT
 */
/*
 *
 */

$this->mail->setSubject('A registered user was confirmed.');
?>
<div class="yk-mail">
<?= $this->partial('mail/header'); ?>

    <p>A user was just confirmed: <?=$this->user->getInfo()->getDisplayName(false) ?>
                                  &lt;<?=$this->user->getInfo()->getEmail()?>&gt;</p>

    <p>This user is now fully registered and active.</p>

<?= $this->partial('mail/footer.en'); ?>
</div>