<?php
/**
 * YAWIK
 *
 * @filesource
 * @copyright (c) 2013-2015 Cross Solution (http://cross-solution.de)
 * @author cbleek
 * @license   AGPLv3
 */
?>
<h1>Social Networks</h1>

This Page will set the things needed for hybrid auth

<pre>
     'hybridauth' => array(
        "Facebook" => array (
            "enabled" => "true",
            "keys"    => array ( "id" => "xxx", "secret" => "yyy" ),
            "scope"   => "email, user_about_me, user_birthday, user_hometown, user_work_history, user_education_history",// optional
            "display" => "popup"
        ),
        "LinkedIn" => array (
            "enabled" => "true",
            "keys"    => array ( "key" => "xxx", "secret" => "yyy" ),
            "scope"   => "r_fullprofile"
        ),
        "XING" => array(
            "enabled" => "true",
            'keys'    => array ( "key" => 'xxx', 'secret' => 'yyy'),
            "scope"   => ''
        ),
</pre>