<?php
/**
 * YAWIK
 *
 * @filesource
 * @copyright (c) 2013-2015 Cross Solution (http://cross-solution.de)
 * @author cbleek
 * @license   AGPLv3
 */
?>
<h1><?php echo $this->translate('Mail Settings');?></h1>

<div class="alert alert-danger">
    <b><?php echo $this->translate('Module is in development. Formular data are currently not processed');?></b>
</div>
<br/>


This Page will contain a form fo global mail settings

<pre>
mail.from.email=test@yawik.org
mail.from.name=YAWIK
</pre>