<?php
/**
 * YAWIK
 *
 * @filesource
 * @copyright (c) 2013-2015 Cross Solution (http://cross-solution.de)
 * @author cbleek
 * @license   AGPLv3
 */
?>
<h1><?php echo $this->translate('Modules');?></h1>

<div class="alert alert-danger">
    <b><?php echo $this->translate('Module is in development. Formular data are currently not processed');?></b>
</div>
<br/>


This Page will list aktivated Modules.


