<?php
/**
 * YAWIK
 *
 * @filesource
 * @copyright (c) 2013-2015 Cross Solution (http://cross-solution.de)
 * @author cbleek
 * @license   AGPLv3
 */
?>
<h1>Static Pages</h1>

<p>This Page will list static pages like "imprint", "privacy policies, "terms & conditions"

currently, these static pages exist.</p>

<ul>
    <li>term & conditions</li>
    <li>imprint</li>
    <li>privacy policy</li>
</ul>


