<?php
$translator = $this->plugin('translate')->getTranslator();
?>
<h1><?=$this->translate('Account removal confirmation') ?></h1>
<?php foreach ($this->dependencies as $dependency): /* @var $dependency \Auth\Dependency\ModuleInterface */?>
	<?php $count = $dependency->getCount($this->user);?>
	<div class="panel panel-default">
    	<div class="panel-heading"><?=$dependency->getTitle($translator)?> <span class="badge pull-right"><?=$count?></span></div>
    	<?php if ($count > 0):?>
    		<ul class="list-group">
                <?php foreach ($dependency->getItems($this->user, $this->router) as $item):?>
                	<?php $url = $item->getUrl();?>
                	<li class="list-group-item">
                		<?php if ($url):?><a href="<?=$url?>"><?php endif;?>
                		<?=$item->getTitle()?>
                		<?php if ($url):?></a><?php endif;?>
                	</li>
                <?php endforeach;?>
    		</ul>
    	<?php endif;?>
	</div>
<?php endforeach;?>
<form method="post" action="">
	<button type="submit" class="btn btn-primary" name="confirm" value="1"><?=$this->translate('Remove my account')?></button>
	<button type="button" class="btn btn-default"><?=$this->translate('Cancel account removal')?></button>
</form>