<?php
/**
 * Cross Applicant Management
 *
 * @filesource
 * @copyright (c) 2013 Cross Solution (http://cross-solution.de)
 * @license   AGPLv3
 */

$this->headScript()->appendFile($this->basePath('Jobs/js/form.apply-identifier.js'));
$value = $this->element->getValue();
?>
<div class="apply-identifier-wrapper">
<?php 
 echo str_replace('class="controls', 'class="apply-identifier-input controls', $this->formRow($this->element));
?>

<div class="controls controls-row row apply-identifier-display hidden" id="<?php echo $this->element->getAttribute('id') ?>-display">
    <div class="col-md-3 text-right"><label class="text-muted"><?php echo $this->translate('Apply link') ?></label></div>
    <div class="col-md-9"><div class="panel panel-default form-control">
        <span class="text-muted apply-identifier-link"><?php echo $this->serverurl($this->url('lang/apply/form', array('jobId' => $value), true)) ?>
        </span>
    </div></div>
</div>
</div>