<?php
/**
 * YAWIK
 *
 * @filesource
 * @copyright (c) 2013-2104 Cross Solution (http://cross-solution.de)
 * @license   MIT
 */
$this->headScript()->appendFile($this->basePath('Jobs/js/index.list-filter-form.js'));
$translate = $this->plugin('translate');

$createRadioGroup = function ($element, $id) use ($translate) {
    $input = '';
    ?>
    <div id="params-<?php echo $id ?>-group" class="btn-group btn-group-sm" data-toggle="buttons">
    <?php foreach ($element->getValueOptions() as $value => $label):
        $checked = $value == $element->getValue();?>
        
        <label class="btn btn-default<?php echo ($checked) ? ' active': ''?>">
            <input id="params-<?php echo "$id-$value" ?>" type="radio" name="<?php echo $element->getName() ?>" value="<?php echo $value ?>"<?php echo $checked ? ' checked' : ''?>>
            <?php echo $translate($label) ?>
        </label>
        
        
    <?php endforeach; ?>
    
    </div>
    <?php //return $input;
};
/*$createDropdown = function ($element, $id) {
    
    $input = '';
    ?><div class="dropdown"><button class="btn btn-small dropdown-toggle" data-target="#" data-toggle="dropdown" id="params-<?php echo $id ?>">
        <?php echo $element->getLabel() ?>: <?php echo $element->getValue() ?> <span class="caret"></span>
    </button>
    <ul class="dropdown-menu">
        <?foreach ($element->getValueOptions() as $value => $label):?>
        <li id="params-<?php echo "$id-$value" ?>" class="<?php $value == $element->getValue() ? "inactive" : "" ?>">
            <a href="#"><?php echo $label ?></a>
        </li>
        <?php endforeach ?>
    </ul></div>
    <?php $input = '<input id="params-' . $id . '-value" type="hidden" name="' . $element->getName() . '" value="' . $element->getValue() .'" />';
    return $input;
};*/


$form   = $this->element;
$params = $this->element->get('params'); 
$form->setAttributes(array(
    'action' => $this->url('lang/jobs', array(), true),
    'method' => 'GET',
));

echo $this->form()->openTag($form);
echo $this->formHidden($params->get('page'));

$byElement = $params->get('by');
$statusElement = $params->get('status');
?>
<div id="params-search-wrapper" class="cam-input-group input-group">
    <span class="input-group-addon">?</span>
    <?php echo $this->formText($params->get('search')->setAttributes(array('class' => 'form-control ','placeholder' =>  /* @translate */ 'search for jobs' ))) ?>
    <span class="input-group-btn">
        <button class="btn btn-primary" type="submit"><?php echo $this->translate('Search') ?></button>
    </span>
</div>
<?php if ($params->has('by') && $this->acl()->isRole('recruiter')):?>
<div class="btn-toolbar navbar-right">
  <?php $createRadioGroup($params->get('by'), 'by') ?>
  <?php $createRadioGroup($params->get('status'), 'status') ?>
</div>
<?php endif; ?>

<?php 
echo $this->form()->closeTag();

?>
