<?php
/**
 * YAWIK
 *
 * @filesource
 * @license MIT
 * @copyright  2013 - 2015 Cross Solution <http://cross-solution.de>
 */


if ($this->renderSummary):?>
<div class="row">
    <div class="col-md-3 yk-label">
        <label><?php echo $this->translate($this->element->getLabel())?></label>
    </div>
    <div class="col-md-9">
        <?php
        $options = $this->element->getValueOptions();
        $valueKey= $this->element->getValue();

        $activePortals = array();
        if ($valueKey && !empty($valueKey)):
            foreach ($options as $category => $categoryOptions):
                foreach ($categoryOptions['options'] as $channelName => $channel):
                    if (in_array($channelName, $valueKey)):
                        $activePortals[$category][$channelName] = $channel;
                    endif;
                endforeach;
            endforeach;

            foreach ($activePortals as $category => $channels):

                ?><h6><?php echo $category ?></h6>
                <?php foreach ($channels as $name => $spec):
                    $data = explode('|', $spec);
                    ?><p><strong><?php echo $data[0] ?> &mdash; <?php echo $data[1] ?></strong><br>
                      <small><?php echo sprintf($data[2], '<a href="' . $data[4] . '">' . $data[3] . '</a>') ?></small>
                </p><?php endforeach;
            endforeach;



        endif; ?>
    </div>
</div>

<?php else: echo $this->formRow()->render($this->element, /* ignoreViewPartial */ true);
endif; // ($this->renderSummary) ?>