<?php
/**
 * YAWIK
 *
 * @filesource
 * @license MIT
 * @copyright  2013 - 2015 Cross Solution <http://cross-solution.de>
 */

$options = $this->services('Core/Options');
$defaultCurrencyCode = $options->defaultCurrencyCode;
$defaultTaxRate = $options->defaultTaxRate;


if ($this->renderSummary):?>
    <div class="row">
        <div class="col-md-12">
            <?php
            $options = $this->element->getValueOptions();
            $valueKey= $this->element->getValue();

            $activePortals = array();
            if ($valueKey && !empty($valueKey)):

               $this->plugin('currencyformat')->setCurrencyCode($defaultCurrencyCode);

                $total = 0; $sum = 0; $channelCount = count($valueKey);
                foreach ($options as $category => $categoryOptions):
                    foreach ($categoryOptions['options'] as $channelName => $channel):
                        if (in_array($channelName, $valueKey)):
                            $activePortals[$category][$channelName] = $channel;
                        endif;
                    endforeach;
                endforeach; ?>
                <div class="panel panel-default">
                    <div class="panel-body">
                    <?php foreach ($activePortals as $category => $channels):?>
                        <h5><?php echo $category ?></h5>
                        <div class="row">
                        <?php foreach ($channels as $name => $spec):
                            $data = explode('|', $spec);
                            $sum += $data[7];
                            if (1 < $channelCount):

                                if ($sum < $data[9] && $total < $data[9]): $total = $data[9];
                                endif;
                            else:
                                //echo $this->currencyFormat($data[7]);
                            endif;
                            $total = $sum > $total ? $sum : $total;
                            ?>
                            <div class="col-md-6" style="height: 34px; padding:  5px 15px;">

                                <a href="<?php echo $data[4] ?>">

                                    <?php if ($data[10]):?>
                                    <img src="<?php echo $data[10] ?>" alt="<?php echo $data[1] ?>" class="img-thumbnail" style="max-width: 60px; max-height: 24px;">
                                    <?php endif; ?> <?php echo $data[0] ?></a></div>
                        <?php endforeach; ?>
                        </div>
                    <?php endforeach; ?>
                        </div>
                    <table class="table table-condensed table-bordered">
                    <thead>
                        <tr>
                            <th><?php echo $this->translate('Price') ?></th>
                            <th class="text-right"><?php echo $this->currencyFormat($total); ?></th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td><?php echo $this->translate('plus VAT') ?> (<?php echo $defaultTaxRate ?>%)</td>
                            <td class="text-right"><?php echo $this->currencyFormat($total * ( $defaultTaxRate /100)); ?></td>
                        </tr>
                    </tbody>
                    <tfoot>
                        <tr>
                            <th><?php echo $this->translate('Invoice amount') ?></th>
                            <th class="text-right"><?php echo $this->currencyFormat($total * (1 + $defaultTaxRate /100)); ?></th>
                        </tr>
                    </tfoot>
                </table>
                </div>
            <?php endif; ?>
        </div>
    </div>

<?php else:
    echo $this->formRow()->render($this->element, /* ignoreViewPartial */ true);
    ?>
    <div class="row">
        <div id="<?php echo $this->element->getAttribute('id') ?>-total" class="text-right col-md-9 col-md-offset-3">
            <div class="panel panel-default">
                <div class="panel-body"><strong><span></span> <?php echo $defaultCurrencyCode?></strong><br>
                <small><?php echo $this->translate('plus VAT') ?></small></div>
            </div>
        </div>
    </div>
    <?php
    // Element Templates
    $resultTmpl = '
    <div class="clearfix">
        <div class="pull-left">
            <strong>%name - %headline</strong><br>
            <small>%desc</small>
        </div>
        <div class="pull-right">
            <strong>%nicePrice</strong>
        </div>
    </div>
    ';

    $selectTmpl = '
        %name (  %duration ) [ %nicePrice (%minNicePrice) ]
    ';

    ?>
    <span id="<?php echo $this->element->getAttribute('id') ?>-result-tmpl" data-template="<?php echo $this->escapeHtmlAttr($resultTmpl) ?>"></span>
    <span id="<?php echo $this->element->getAttribute('id') ?>-select-tmpl" data-template="<?php echo $this->escapeHtmlAttr($selectTmpl) ?>"></span>
    <span id="<?php echo $this->element->getAttribute('id') ?>-currency-tmpl" data-template="<?php echo $this->numberFormat(1234.56) ?>"></span>
<?php endif; // (else > $this->renderSummary) ?>