<?php
/**
 * YAWIK
 *
 * @filesource
 * @license MIT
 * @copyright  2013 - 2016 Cross Solution <http://cross-solution.de>
 */

$job = $this->element->getObject();

$viewLink = $this->url(
    'lang/jobs/view',
    array(),
    array(
        'query' => array(
            'id' => $job->id
        )
    )
);

$multipostLink = $this->url(
    'lang/jobs/manage',
    array(),
    array(
        'query' => array(
           'id' => $job->id,
           'page' => 0
        ),
    )
);



$options = $this->services('Core/Options');
$defaultCurrencyCode = $options->defaultCurrencyCode;
$defaultTaxRate = $options->defaultTaxRate;

?>
<h3><?php echo $this->translate("Preview of your job posting"); ?></h3>
<div class="row">
    <div class="col-md-8">
        <div class="panel panel-default">
            <div class="panel-body">
                <iframe id="previewJob" style="width:100%; height:800px;" src="<?php echo $viewLink ?>"></iframe>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="alert alert-info">
            <script type="text/javascript">
                function printIframe(id)
                {
                    var iframe = document.frames ? document.frames[id] : document.getElementById(id);
                    var ifWin = iframe.contentWindow || iframe;
                    iframe.focus();
                    ifWin.yawikPrintJob();
                    return false;
                }
            </script>
            <?php echo sprintf($this->translate('Please check the preview of your job position. Click %s to open the preview in a new window'),
                               '<a target="_blank" href="'.$viewLink.'">'.$this->translate("here").'</a>'); ?><br/>
            <a target="_blank" href="<?=$viewLink?>" class="btn btn-info" role="button"><i class="fa fa-external-link"></i> Open new Window</a>
            <a href="#" onclick="javascript:printIframe('previewJob');return false;" class="btn btn-info" role="button"><i class="fa fa-print"></i> Print</a>
        </div>
    </div>
</div>

    <div id="product-list-wrapper">
        <?php if ($job->getPortals()): ?>
            <?php echo $this->partial('jobs/partials/channel-list', [
                                                                          'portals'             => $job->getPortals(),
                                                                          'channels'            => $this->services('Jobs/Options/Provider'),
                                                                          'defaultCurrencyCode' => $defaultCurrencyCode,
                                                                          'defaultTaxRate'      => $defaultTaxRate,
                                                                          'jobId'               => $job->getId(),
                                                                      ]);
            ?>

        <?php endif; // $this->job->portals ?>
    </div>

<?php echo $this->formCollection($this->element); ?>
