<h3 id="history-box-label">
    <?php echo $this->translate('State history') ?>:
</h3>
<table class="table table-striped table-bordered table-hover">
    <thead>
    <tr>
        <th><?php echo $this->translate('Date') ?></th>
        <th><?php echo $this->translate('State') ?></th>
        <th><?php echo $this->translate('Comment') ?></th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($this->job->history as $history): ?>
        <tr>
            <td><?php echo $this->dateFormat($history->date) ?></td>
            <td><?php echo $this->translate($history->status) ?></td>
            <td><?php echo $history->message ?></td>
        </tr>
    <?php endforeach ?>
    </tbody>
</table>