<?php
/**
 * YAWIK
 *
 * @filesource
 * @license MIT
 * @copyright  2013 - 2015 Cross Solution <http://cross-solution.de>
 */
$job=$this->job; /* @var \Jobs\Entity\Job $job */
?>
<h3 id="history-box-label">
    <?php echo $this->translate('Status history') ?>:
</h3>
<table class="table table-striped table-bordered table-hover">
    <thead>
    <tr>
        <th><?=$this->translate('Date') ?></th>
        <th><?=$this->translate('State') ?></th>
        <th><?=$this->translate('Comment') ?></th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($job->getHistory() as $history):  /* @var \Jobs\Entity\History $history */ ?>
        <tr>
            <td><?php echo $this->dateFormat($history->getDate()) ?></td>
            <td><?php echo $this->translate($history->getStatus()) ?></td>
            <td><?php echo $history->getMessage() ?></td>
        </tr>
    <?php endforeach ?>
    </tbody>
</table>