<?php
/**
 * YAWIK
 *
 * @filesource
 * @license MIT
 * @copyright  2013 - 2015 Cross Solution <http://cross-solution.de>
 */
?>
<?php
$sm = $this->getHelperPluginManager()->getServiceLocator();
$channels = $sm->get('Jobs/Options/Provider');
?>
<?php if ($this->job->portals):?>
    <h3><?php echo $this->translate('Summary') ?></h3>
    <?php $total=0 ?>
    <table class="table table-bordered">
        <tr>
            <th><?php echo $this->translate('Channel')?></th>
        </tr>
        <?php foreach($this->job->portals as $channel):?>
            <?php if($channel):?>
                <?php $channelData=$channels->getChannel($channel); ?>
                <tr>
                    <td><?php echo $channelData->label ?></td>
                </tr>
            <?php endif;?>
        <?php endforeach;?>
    </table>
<?php endif; // $this->job->portals ?>