<?php
/**
 * YAWIK
 *
 * @filesource
 * @license MIT
 * @copyright  2013 - 2015 Cross Solution <http://cross-solution.de>
 */
?>
<?php
$sm = $this->getHelperPluginManager()->getServiceLocator();
$channels = $sm->get('Jobs/Options/Provider'); /* @var \Jobs\Options\ProviderOptions $channels */
$job=$this->job; /* @var \Jobs\Entity\Job $job */
?>
<?php if ($job->getPortals()):?>
    <h3><?php echo $this->translate('Summary') ?></h3>
    <?php $total=0 ?>
    <table class="table table-bordered">
        <tr>
            <th><?php echo $this->translate('Channel')?></th>
        </tr>
        <?php foreach($job->getPortals() as $channel):?>
            <?php if($channel):?>
                <?php $channelData=$channels->getChannel($channel); ?>
                <tr>
                    <td><?php echo $channelData->getLabel() ?></td>
                </tr>
            <?php endif;?>
        <?php endforeach;?>
    </table>
<?php endif; // $this->job->portals ?>