
<table class="table table-striped table-bordered table-hover" id="cv-list">
<thead>
<tr>
    <th><?php echo $this->translate('Id')?></th>
</tr>
</thead>

<tbody>
<?php foreach ($resumes as $resume):?>
<tr>
    <td><?php echo $resume->id ?></td>
</tr>
<?php endforeach?>
</tbody>

</table>
<?php #echo $this->paginationControl($jobs, 'Sliding', 'pagination-control', array('lang' => $this->params('lang'), 'route' => 'lang/jobs'));?>
