<?php $this->headTitle($this->translate('Resumes'));
      $this->headScript()->appendFile($this->basepath('/Core/js/core.pagination.js'));
      /*$this->headLink()->appendStylesheet($this->basePath('Core/css/forms.css'))
                       ->appendStylesheet($this->basepath('/Applications/css/manage.css'));
      $this->headScript()->appendFile($this->basepath('/Applications/js/manage.js'))?>*/?>

<h1><?php echo $this->translate("list of all resumes")?></h1>
<div id="applications-list-container" class="pagination-container">
<?php echo $this->render('cv/index/index.recruiter.ajax.phtml') ?>
</div>