<?php //description: Renders the list of jobs. used by applicants and recruiters ?>
<?php $this->headTitle($this->translate('Jobs'));
      $this->headScript()->appendFile($this->basepath('/Core/js/core.pagination-container.js'))
                         ->appendFile($this->basePath('/assets/bootstrap3-dialog/js/bootstrap-dialog.min.js'))
                         ->appendFile($this->basePath('/Jobs/js/index.assign-users.js'))
                         ->appendFile($this->basePath('/assets/select2/js/select2.min.js'));
$this->headScript()->captureStart() ?>
/* This code is generated in jobs/index/approval.phtml
 *
 * It forces the history modal to loose its data on close.
 */
(function($) {
    var loadingText;
    $(function() {
        var $modal = $('#job-application-history');
        loadingText = $modal.find('.modal-header h4').html();

        $modal.on('hidden.bs.modal', function() {
            $modal.find('.modal-body').empty();
            $modal.find('.modal-header h4').html(loadingText);
            $modal.removeData('bs.modal');

        });
    });
})(jQuery);
<?php $this->headScript()->captureEnd();
      $this->headLink()->appendStylesheet($this->basePath('/css/bootstrap-dialog.min.css'))?>

<h1><?php echo $this->translate('Jobs waiting for approval') ?></h1>

<?php echo $this->flashMessenger()->render('default', array('alert', 'alert-success')) ?>

<nav class="navbar yk-toolbar" id="jobs-list-filter-wrapper">
<?php echo $this->form($this->filterForm)  ?>
</nav>
<div id="jobs-list-container" class="pagination-container" data-uri="<?php
    echo $this->url('lang/jobs/listOpenJobs', array(), array('query' => $this->params()->fromQuery()), true)?>">

    <div class="pagination-message alert alert-info">
        <?php echo $this->translate('No job is waiting for approval at the moment.') ?>
    </div>

    <div class="pagination-content">
<?php echo $this->render('jobs/index/approval.ajax.phtml')?>
    </div>

</div>

<!-- Modal Box for Job-History -->
<div class="modal fade" id="job-application-history" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="exampleModalLabel"><i class="yk-icon yk-icon-spinner fa-spin"></i><?php echo $this->translate('please wait') ?></h4>
            </div>
            <div class="modal-body">
            </div>
        </div>
    </div>
</div>
