<?php
/**
 * YAWIK
 *
 * @filesource
 * @copyright (c) 2013 - 2016 Cross Solution (http://cross-solution.de)
 * @license   MIT
 */
if (count($this->jobs)):
$isRecruiter = $this->acl()->isRole( Auth\Entity\User::ROLE_RECRUITER );

?>
<table class="table table-striped table-bordered table-hover" id="jobs-list">
<thead>
<tr>
    <th><?php echo $this->translate('Date of receipt')?></th>
    <th><?php echo $this->translate('Title of the job')?></th>
    <th><?php echo $this->translate('Location')?></th> 
    <th><?php echo $this->translate('Companyname')?></th>
    <th><?php echo $this->translate('Reference')?></th>
    <?php if ($isRecruiter):?>
       <th><?php echo $this->translate('Applications')?></th>
       <th><?php echo $this->translate('Status')?></th>
       <th><?php echo $this->translate('Action')?></th>
    <?php else: ?>
       <th><?php echo $this->translate('Action')?></th>
    <?php endif;?>
</tr>
</thead>

<tbody>
<?php foreach ($jobs as $job): /* @var  \Jobs\Entity\Job $job */?>
<tr>
    <td><?php if ($job->datePublishStart): echo $this->dateFormat($job->datePublishStart, 'short', 'none'); 
              elseif ($job->dateCreated): echo $this->dateFormat($job->dateCreated, 'short', 'none'); endif?>
        <?php if ($isRecruiter):?>
        <br>(<?php
            $displayName = '';
            $user = $job->getUser();
            if (isset($user)) {
                $displayName = $user->getInfo()->getDisplayName();
            }
            echo $displayName

            ?>)
        <?php endif ?></td>
              
    <td>
        <?=$this->jobUrl($job,['showPendingJobs' => $this->showPendingJobs ]) ?>
        <br />
        <small><?=$job->getClassifications()->getProfessions()?></small> |
        <small><?=$job->getClassifications()->getEmploymentTypes()?></small>
    </td>
    <td><?php echo $job->location?></td>
    <td><?php echo $job->company?></td>
    <td><?php echo empty($job->reference)? $job->applyId:$job->reference ?></td>

      <?php if ($isRecruiter):?>
          <td>
         <?php if ($job->applications->count()>0):?>
            <a title="<?php echo $this->translate("total")?>" href="<?php echo $this->url( 'lang/applications', array(), array('query' => 'job=' . $job->id), true) ?>">
            <span class="badge"><?php echo $job->applications->count() ;?></span>
            </a>
         <?php endif;?>
         <?php if ($job->unreadApplications->count()):?>       
            / 
            <a title="<?php echo $this->translate("unread")?>" 
               href="<?php echo $this->url( 'lang/applications', array(), array('query' => 'job=' . $job->id . '&unread=1'), true) ?>">
            <span class="badge"> <?php echo $job->unreadApplications->count()?></span>
            </a>
             </td>
         <?php endif;?>
         <td>
         <?php
            $status = array();
            if (!empty($job->getStatus())) {
                $status[] = $this->translate($job->getStatus()->getName());
            }
            if ($job->isDraft()) {
                $status[] = $this->translate('draft');
            }
            echo implode('<br />', $status);
         ?>
         </td>
         <td class="btn-group btn-toolbar"><?php if ($this->acl($job, 'edit')): ?>
             <?php $org = $job->getOrganization(); if ($org && $org->getUser()):?>
             <a href="<?php echo $this->url('lang/jobs/assign-user', array(), array('query' => array('id' => $job->id)), true)?>"
                data-id="<?php echo $job->id ?>"
                data-i18n='{"title":"<?php echo $this->escapeHtmlAttr(sprintf(
                                            $this->translate('Change responsible user for job \\"%s\\"'),
                                            $job->title
                                       ))?>"}'
                class="btn btn-default btn-xs assign-user-button"><span class="yk-icon yk-icon-user"></span></a>
                     <?php endif; ?>

         <a data-title="title"
            data-toggle="modal"
            class="btn btn-default btn-xs"
            data-target="#job-application-history"
            href="<?php echo $this->url( 'lang/jobs/history', array('id' => $job->getId() , 'lang' => $this->params('lang'))); ?>"
            title="<?php echo $this->translate('Status history')?>">
             <i class="yk-icon yk-icon-history"></i>
         </a>

         <a href="<?php echo $this->url('lang/jobs/manage', array('action' => 'edit'), array('query' => array('id' => $job->id)), true) ?>" class="btn btn-default btn-xs"><span class="yk-icon yk-icon-edit"></span></a>
         <?php endif; ?>
         </td>
      <?php else:?>
          <?= $this->urlApply($job)?>
      <?php endif ?>
     </td>
</tr>
<?php endforeach?>
</tbody>

</table>
<?php echo $this->paginationControl($jobs, 'Sliding', 'pagination-control', array('lang' => $this->params('lang'), 'route' => 'lang/jobs'));?>


<?php endif ?>