<?php $this->headTitle($this->translate('Jobs'));
      $this->headScript()->appendFile($this->basepath('/Core/js/core.pagination.js'))?>

<h1><?=$this->translate('List of all jobs')?></h1>

<div id="jobs-list-filter-wrapper">
<?php echo $this->form($this->filterForm)  ?>
</div>
<div id="jobs-list-container" class="pagination-container">
<?php echo $this->render('jobs/index/index.ajax.phtml')?>
</div>

<?php echo $this->partial('core/loading-popup') ?>
