
<table class="table table-striped table-bordered table-hover" id="jobs-list">
<thead>
<tr>
    <th><?=$this->translate('Date of receipt')?></th>
    <th><?=$this->translate('Title of the job')?></th>
    <th><?=$this->translate('Location')?></th> 
    <th><?=$this->translate('Companyname')?></th>
    <th><?=$this->translate('Reference')?></th>
</tr>
</thead>

<tbody>
<?foreach ($jobs as $job):?>
<tr>
    <td><?php echo $job->datePublishStart?></td>
    <td><a href="<?php echo $job->link?>"><?php echo $job->title?></a></td>
    <td><?php echo $job->location?></td>
    <td><?php echo $job->company?></td>
    <td><?php echo $job->applyId?></td>
</tr>
<?endforeach?>
</tbody>

</table>
<?php echo $this->paginationControl($jobs, 'Sliding', 'pagination-control', array('lang' => $this->params('lang'), 'route' => 'lang/jobs'));?>
