<?php 
/**
 * YAWIK
 * View template of the Home site
 * 
 * @copyright (c) 2013-2104 Cross Solution (http://cross-solution.de)
 * @license   GPLv3
 */
?>


<div class="col-md-6">
<?

if ($this->script): 
        try {
            echo $this->render($this->script);
        } catch (\Exception $e) {
            ?><?php echo $this->translate('Error loading widget.')?>
            <br><br>
            <?php echo $e->getMessage() ?>
        <?}

elseif ($this->content): 
    echo $this->content; 
endif;
?> 
</div>
