<?php 
/**
 * YAWIK
 * View template of the Home site
 * 
 * @copyright (c) 2013 - 2016 Cross Solution (http://cross-solution.de)
 * @license   MIT
 */
?>

<?php $this->headTitle($this->translate('Dashboard'));?>


<h1><?php echo $this->translate('Dashboard'); ?></h1>

<div class="row">
<?php foreach ($this->viewModel()->getCurrent()->getChildren() as $model):
    if (0 !== strpos($model->captureTo(), 'dashboard_')) { continue; }

    ?>
    
        <?php echo $this->{$model->captureTo()};?>
    
    <?php endforeach ?>

</div>


