<?php 
/**
 * YAWIK
 * View template of the Home site
 * 
 * @copyright (c) 2013 - 2016 Cross Solution (http://cross-solution.de)
 * @license   MIT
 */
?>


<div class="col-md-6">
<?php

if ($this->script): 
        try {
            echo $this->render($this->script);
        } catch (\Exception $e) {
            ?><?php echo $this->translate('Error loading widget.')?>
            <br><br>
            <?php echo $e->getMessage() ?>
        <?php }

elseif ($this->content): 
    echo $this->content; 
endif;
?> 
</div>
