<?php
/**
 * YAWIK
 *
 * View template for changing the password
 *
 * @copyright (c) 2013 - 2016 Cross Solution (http://cross-solution.de)
 * @license   MIT
 */

$this->headTitle($this->translate('My password'));

/*
 * you can modify the action
 */ 
$this->form->setAttribute('action', $this->url('lang/my-password', array(), true));

/*
 * you can enable Descriptions 
 */
$this->form->setIsDescriptionsEnabled(true);
$this->form->setDescription($this->translate('Here you can change your password'));

?>
<h1><?php echo $this->translate('My password') ?></h1>
<div class="col-md-12">
<?php echo  $this->form($this->form, Core\Form\View\Helper\Form::LAYOUT_HORIZONTAL); ?>
<?php echo  $this->inlineScript()->appendFile($this->basePath('modules/Auth/js/form.change-password.js')); ?>
</div>