<?php
/**
 * YAWIK
 *
 * @filesource
 * @license MIT
 * @copyright  2013 - 2017 Cross Solution <http://cross-solution.de>
 */
  
/** */
namespace Geo\Form;

use Core\Form\HeadscriptProviderInterface;
use Core\Form\Hydrator\HydratorStrategyProviderInterface;
use Core\Form\Hydrator\HydratorStrategyProviderTrait;
use Traversable;
use Zend\Form\Element\Select;
use Zend\Form\Element;
use Zend\Form\ElementInterface;
use Zend\Form\Exception\InvalidArgumentException;

/**
 * ${CARET}
 * 
 * @author Mathias Gelhausen <gelhausen@cross-solution.de>
 * @todo write test 
 */
class GeoSelect extends Select implements HeadscriptProviderInterface, HydratorStrategyProviderInterface
{
    use HydratorStrategyProviderTrait;

    /**
     * @var bool
     */
    protected $disableInArrayValidator = true;

    private $headscripts = [
        'Geo/js/geoselect.js'
    ];

    public function setOptions($options)
    {
        parent::setOptions($options);

        if (isset($options['location_entity'])) {
            $this->getHydratorStrategy()->setLocationEntityPrototype($options['location_entity']);
        }
    }

    public function setValue($value)
    {
        $this->setAttribute('data-val', $value);

        return parent::setValue($value); // TODO: Change the autogenerated stub
    }


    /**
     * Sets the array of script names.
     *
     * @param string[] $scripts
     *
     * @return self
     */
    public function setHeadscripts(array $scripts)
    {
        $this->headscripts = $scripts;

        return $this;
    }

    /**
     * Gets the array of script names.
     *
     * @return string[]
     */
    public function getHeadscripts()
    {
        return $this->headscripts;
    }


    public function init()
    {
        $this->setAttributes([
                'data-placeholder' => /*@translate*/ 'Location',
                'data-autoinit' => false,
                'class' => 'geoselect',
        ]);

    }
}