<?php
/**
 * YAWIK
 *
 * @filesource
 * @license MIT
 * @copyright  2013 - 2015 Cross Solution <http://cross-solution.de>
 */
$this->headTitle('500');
?>


<h1><?php echo $this->translate('Missing Configuration') ?></h1>
<h2><?php echo $this->translate('Unfortunately there seems to be missing configuration.') ?></h2>

<div class="panel panel-default">
    <div class="panel-body">
        <p>
            <?php echo $this->translate('The login via social networks does not work at the moment due to the missing of some crucial configuration data.') ?>
        </p>

    </div>
</div>