<?php 
/**
 * Cross Applicant Management
 * Layout template file
 * 
 * @copyright (c) 2013 Cross Solution (http://cross-solution.de)
 * @license   GPLv3
 */
?>

<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Cross Applicant Management'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
        
        <?php echo $this->headScript()
                        ->prependFile($this->basepath('Core/js/core.init.js'))
                        ->prependFile($this->basePath('bootstrap/js/bootstrap.js'))
                        ->prependFile($this->basePath('js/jquery-1.9.1.js')) 
                        
                        ->appendScript('var lang="' . $this->params('lang') . '";');
        ?>
        
        <?php echo $this->headLink() ->prependStylesheet($this->basePath() . '/css/cam.css');?>

        <?php echo $this->headStyle() ?>
    </head>
    <body>
	<a class="sr-only" href="#content">Skip to main content</a>
	<header id="cam-topbar" role="banner">
         <div class="cam-container">
   	       <div class="navbar-header">
                    <button class="navbar-toggle collapsed" data-target=".cam-navbar-collapse" data-toggle="collapse" type="button">
			<span class="sr-only">Toggle navigation</span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand hidden-xs" href="<?php echo $this->basepath('/' . $this->params('lang'))?>"><?php echo $this->translate('Cross Applicant Management')?></a>
                    <a class="navbar-brand visible-xs" href="<?php echo $this->basepath('/' . $this->params('lang'))?>"><?php echo $this->translate('CAM')?></a>
               </div>
                  <nav id="cam-main-navigation" class="navbar-collapse collapse cam-navbar-collapse" role="navigation">
                     <?php 
                        echo $this->navigation('main_navigation')
                                  ->setAcl($this->services('acl'))
                                  ->setRole($this->auth('role'))
                                  ->menu()
                                  ->setMaxDepth(0)
                                  ->setUlClass('nav navbar-nav pull-left')//renderPartial(null, 'main-navigation')?>

                     <?php echo $this->loginInfo ?>
                 </nav> <!-- /main-navigation -->
		</div>
            </header>
          <div class="container row col-md-2">
<!-- SIDEBAR -->
<nav id="sidebar">
<div class="btn-group" data-toggle="buttons-radio" id="language-switcher">
    <?php $lang = $this->params('lang');
    foreach (array('en', 'de') as $availableLang): ?>
    <button type="button" class="btn btn-default<?php echo $availableLang == $lang ? ' active' : ''?>" id="language-switcher-<?php echo $availableLang ?>">
    <?php echo strtoupper($availableLang) ?></button>
    <?php endforeach ?>
</div>
     
<div id="sub-nav">               
<?php
    echo $this->navigation()->menu()
              ->setOnlyActiveBranch()
              ->setMaxDepth(null)
              ->setMinDepth(1)
              ->setRenderParents(false)
              ->setUlClass('nav nav-pills nav-stacked');
?>


<?foreach ($this->layout()->getChildren() as $child):
    if (0 === strpos($child->captureTo(), "sidebar_")):
        echo $this->{$child->captureTo()};
    endif;
endforeach;?>

</div>
</nav>
<!-- /SIDEBAR -->
                    </div>
                    
<main id="content" class="col-md-10">
<?php echo $this->content; ?>
</main> 
<!-- /container -->
            <footer id="cam-footer">
                <div class="container">
                <span class="pull-left"><small>&copy; 2013-2014 <a href="http://cross-solution.de">Cross Solution</a>. <?php echo $this->translate('All rights reserved.') ?>
                    | <?php passthru('git describe') ?> [<?php passthru('git rev-parse --abbrev-ref HEAD') ?>]</small></span>
                
                <span class="pull-right"><small>
                    Powered by <a href="http://framework.zend.com">Zend Framework 2</a>,
                                <a href="http://getbootstrap.com/2.3.2/">Bootstrap</a>,
                                <a href="http://jquery.com">jQuery</a>
                               </small> </span>
                
                </div>
            </footer>
    </body>
</html>
