<?php 
/**
 * Cross Applicant Management
 * Layout template file
 * 
 * @copyright (c) 2013 Cross Solution (http://cross-solution.de)
 * @license   GPLv3
 */
?>

<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Cross Applicant Management'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
        
        <?php echo $this->headScript()
                        ->prependFile($this->basePath('bootstrap/js/bootstrap.js'))
                        ->prependFile($this->basePath('js/jquery-1.9.1.js')) 
                        ->appendFile($this->basepath('js/Core/core.init.js'))
                        ->appendScript('var lang="' . $this->params('lang') . '";');
        ?>
        
        <?php echo $this->headLink()->prependStylesheet($this->basePath() . '/css/Core/layout.css')
                                    ->prependStylesheet($this->basePath('bootstrap/css/bootstrap.css'));?>

    </head>
    <body>
        <div id="main">
            <header id="topbar" class="navbar navbar-fixed-top">
                <div class="navbar-inner">
                <div class="container">
                <a class="brand" href="<?php echo $this->basepath('/' . $this->params('lang'))?>"><?php echo $this->translate('Cross Applicant Management')?></a>
                

                <div class="nav-collapse collapse" id="main-navigation">
                    <?php 
                        echo $this->navigation('main_navigation')->menu()->setUlClass('nav')?>

                    <?php echo $this->loginInfo ?>
                </div> <!-- /main-navigation -->
                </div>
                </div>
                
            </header>
            
            <div id="container" class="container">
                <div class="btn-group pull-right" data-toggle="buttons-radio" id="language-switcher">
                    <?php $lang = $this->params('lang');
                    foreach (array('en', 'de') as $availableLang): ?>
                    <button type="button" class="btn<?php echo $availableLang == $lang ? ' active' : ''?>" id="language-switcher-<?php echo $availableLang ?>">
                    <?php echo strtoupper($availableLang) ?></button>
                    <?php endforeach ?>
                </div>
                <?php echo $this->content; ?>

            </div> <!-- /container -->

            <footer class="modal-footer navbar">
                <div class="container-fluid"><small>
                <p class="pull-left">&copy; 2013 <a href="http://cross-solution.de">Cross Solution</a>. <?php echo $this->translate('All rights reserved.') ?>
                    | <?php passthru('git describe') ?> [<?php passthru('git rev-parse --abbrev-ref HEAD') ?>]</p>
                
                <p class="pull-right">
                    Powered by <a href="http://framework.zend.com">Zend Framework 2</a>,
                                <a href="http://getbootstrap.com/2.3.2/">Bootstrap</a>,
                                <a href="http://jquery.com">jQuery</a>
                                </p>
                </small>
                </div>
            </footer>
        </div> <!-- /main -->
    </body>
</html>
