<?php
$this->headScript()->appendFile($this->basepath('modules/Core/js/core.pagination-container.js'));
$this->headScript()->appendFile($this->basepath('modules/Core/js/core.pagination.js'));
/* @var \Organizations\Entity\Organization $organization */
$contact = $organization->getContact();
?>
<div class="row">
    <div class="col-md-2">
        <?php if($organization->getImages()->notEmpty('images')): ?>
            <img src="<?php echo $this->basePath($this->organizationImageCache->getUri($organization->getImages()->get('thumbnail'))) ?>">
        <?php else: ?>
            <span class="yk-icon fa-file-image-o fa-5x"></span>
        <?php endif;?>
    </div>
    <div class="col-md-10">
        <h1><?php echo $organization->getName()?></h1>
        <address>
            <?php echo $contact->getStreet()?> <?php echo $contact->getHouseNumber()?><br/>
            <?php echo $contact->getCity()?> <?php echo $contact->getPostalcode()?><br/>
            <?php echo $contact->getCountry()?><br/>
            <?php echo is_null($contact->getPhone()) ? "":"Phone: ".$contact->getPhone()."<br/>" ?>
            <?php echo is_null($contact->getFax()) ? "":"Fax: ".$contact->getFax()."<br/>" ?>
        </address>
    </div>
</div>
<div id="jobs-list-container" class="pagination-container"
    <div class="pagination-content">
        <?php echo $this->render('organizations/profile/detail.ajax.phtml')?>
    </div>
</div>
