<?php
/**
 * YAWIK
 *
 * @filesource
 * @copyright (c) 2013-2015 Cross Solution (http://cross-solution.de)
 * @author bleek@cross-solution.de
 * @license   MIT
 */
/*
 * Mail footer used in various mails via <?php echo $this->partial('mail/footer'); ?>
 */

$options = $this->services('Core/Options');
$siteName = $options->siteName;

?>
<p>Mit freundlichen Grüßen,</p>

<br /><br />ihr <?php echo $siteName ?>-Team